WIP: Add credit memo transaction allocations
Rebilly/api-definitions pull request #1003
Opened 2022-09-05 09:47 UTC by Boydbueno

## Summary

## Links

## Checklist

- [ ] Writing style
- [ ] API design standards

2022-09-07 15:35 UTC, noon-dawg reviewed
Very minor suggestions

2022-09-07 15:35 UTC, noon-dawg commented on openapi/paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
> +    description: Transaction ID.
nitpick: where possible, we should give more detail on ID fields

(I'm not sure if my suggestion is correct here) 

```suggestion
    description: ID of a transaction on which a credit memo has been applied.
```

2022-09-07 15:35 UTC, noon-dawg commented on openapi/paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
> +    Gets the amount allocated from the given credit memo to the given transaction.
nitpick: I think we should start getter descriptions with "Retrieves"

```suggestion
    Retrieves the amount allocated from the given credit memo to the given transaction.
```

2022-09-07 15:35 UTC, noon-dawg commented on openapi/paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
> +      description: Credit memo transaction allocation was deleted.
nitpick: I don't think "was" is needed here

```suggestion
      description: Credit memo transaction allocation deleted.
```

2022-09-07 15:35 UTC, noon-dawg commented on openapi/paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
> +      description: Credit memo transaction allocation successfully created.
suggestion: I'm not sure if it is complete at this point, or if it is created first and completed at a later point

```suggestion
      description: Credit memo transaction allocation successfully completed.
```

2022-09-07 17:09 UTC, Boydbueno commented
@noon-dawg, thanks a bunch for the great comments!

2022-09-07 17:11 UTC, noon-dawg commented
LTGM!

2022-09-07 17:28 UTC, adamaltman commented on openapi/openapi.yaml
> +      $ref: ./paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
```suggestion
  /credit-memos/{id}/transaction-allocations:
    $ref: ./paths/credit-memos@{id}@allocations.yaml
  /credit-memos/{id}/allocations/{transactionId}:
      $ref: ./paths/credit-memos@{id}@allocations@{transactionId}.yaml
```
Can we rename like this?

2022-09-07 17:43 UTC, Boydbueno commented on openapi/openapi.yaml
> +      $ref: ./paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
I am afraid that this will suggest that this is for both invoice and transaction allocations. Instead of only allocations to transactions. What do you think @adamaltman?

2022-09-07 19:09 UTC, adamaltman commented on openapi/openapi.yaml
> +      $ref: ./paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
I'm confused. There is no invoice allocation, so how would it suggest that?

2022-09-08 05:13 UTC, 2e3s commented on openapi/openapi.yaml
> +      $ref: ./paths/credit-memos@{id}@transaction-allocations@{transactionId}.yaml
There are allocations from credit memo to invoices: `/invoices/{id}/credit-memo-allocations`. Granted, it's on a different resource path, but non-specific path for transactions may be confusing about what is meant. Having "transaction" gives the idea right away.

2022-09-08 12:04 UTC, adamaltman requested changes
Overall, I believe the design of this API is wrong because I do not believe the allocation is a sub-resource.

Let's discuss it further before proceeding.

2022-09-13 20:38 UTC, closed without merging

2022-09-13 20:39 UTC, Boydbueno commented
Closed in favor of the alternative approach: https://github.com/Rebilly/api-definitions/pull/1014