Add transaction allocations to credit memo resource
Rebilly/api-definitions pull request #1014
Opened 2022-09-08 13:25 UTC by Boydbueno

## Summary

Add transaction allocations to the credit memo resource

❗ Not to be merged before implementation is finished

## Checklist

- [x] Writing style
- [x] API design standards

2022-09-08 14:53 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        transactions:
I don't understand the purpose of this level.

```
{
"allocations": [
   {
     "transactionId": "abc-123",
     "amount": 27.95,
     "currency": "USD"
   },
     "transactionId": "def-456",
     "amount": 13.22,
     "currency": "USD"
   }
],
...
 }
 ```
 
 Wouldn't this be the desired structure?

2022-09-08 15:05 UTC, Boydbueno commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        transactions:
Yes, the idea is to add the invoice allocations here later.

A credit memo can already be allocated to multiple invoices: https://api-reference.rebilly.com/tag/Invoices/operation/GetInvoiceCreditMemoAllocationCollection

The `invoiceId` on a CreditMemo is as a reference why the Credit Memo is created, this doesn't have any to do with allocations of the credit memo. `ID of the invoice which the credit memo is issued upon.`

2022-09-08 20:56 UTC, 2e3s commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        transactions:
> But a credit memo is only connected to one and only one invoice according to the current credit memo design.

It's connected to 1 invoice only in terms of which invoice was the source of the credit memo. Credit memo can allocate to many invoices.

2022-09-09 11:20 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        transactions:
This doesn't make sense.

2022-09-09 11:21 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        transactions:
Ahhh. I understand. I think we may need to improve the naming.

2022-09-09 11:22 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +                  This value can not exceed the unused amount of the credit memo or the transaction amount.
```suggestion
                  This value cannot exceed the unused amount of the credit memo or the transaction amount.
```

2022-09-09 13:21 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +  allocations:
I think for GET requests and thus retrieving, `allocations` sounds fine. But maybe for PUT request will be better to use verb like `allocate`?

2022-09-12 07:45 UTC, Boydbueno commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        transactions:
@adamaltman, what naming do you think needs to be improved? Of the new allocations or of the existing `invoiceId`?

2022-09-12 07:52 UTC, Boydbueno commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +  allocations:
Using the verb `allocate` would suggest it's only for allocating. In this case `allocations` is for updating the allocations to the provided lists. This means updating, deleting and creating allocations.

2022-09-13 19:20 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        transactions:
I think we should stick with it as allocations.

2022-09-13 19:26 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +  allocations:
Using a verb in naming is generally against our standards. Yes, there are deviations.

2022-09-14 10:30 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +  allocations:
Okay, let it be `allocations` then, thank you

2022-09-19 13:57 UTC, nanobash approved these changes, later dismissed

2022-09-19 20:58 UTC, 2e3s commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +                  - $ref: ../ResourceId.yaml
What's the point of having this credit memo ID again within the credit memo payload?
```suggestion
```

2022-09-19 21:19 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +                  - $ref: ../ResourceId.yaml
I believe here it's just because of response part, we did not intent to include it into the payload, but just to get credit-memo id on response

2022-09-19 21:55 UTC, 2e3s commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +                  - $ref: ../ResourceId.yaml
I frankly can't understand the reason for this field.

2022-09-20 07:21 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +                  - $ref: ../ResourceId.yaml
Okay, let's remove it, thanks

2022-09-20 07:51 UTC, nanobash approved these changes, later dismissed

2022-09-27 09:10 UTC, nanobash commented
@Rebilly/php @Rebilly/docs please review

2022-09-27 09:17 UTC, adamaltman requested changes

2022-09-27 09:17 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +    type: array
I don't understand why this is an array. It doesn't make sense to me.

```
allocations:
  transactions: [
    # this array makes sense
  ]
```

2022-09-27 09:34 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +    type: array
Updated, thanks

2022-09-27 09:35 UTC, nanobash commented
@Rebilly/php @Rebilly/docs please review

2022-09-27 09:44 UTC, adamaltman requested changes

2022-09-27 09:44 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +              readOnly: true
https://github.com/Rebilly/api-definitions/blob/main/openapi/components/schemas/ServerTimestamp.yaml is already read only.
```suggestion
```

2022-09-27 09:56 UTC, adamaltman requested changes

2022-09-27 09:56 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +        type: array
This is missing a description.
```suggestion
        type: array
        description: |-
          List of transactions (typically refunds, credits, and chargebacks) that are allocated to reducing the credit memo's unused amount. 
```

2022-09-27 10:02 UTC, adamaltman approved these changes

2022-09-27 10:04 UTC, adamaltman requested changes

2022-09-27 10:04 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +    type: object
```suggestion
    type: object
    description: Allocations reduce the credit memo's unused amount.
```

2022-09-27 10:07 UTC, adamaltman approved these changes

2022-09-27 10:27 UTC, nanobash approved these changes

2022-09-29 11:06 UTC, merged