Rework customer descriptions
Rebilly/api-definitions pull request #1031
Opened 2022-09-16 15:56 UTC by noon-dawg

## Summary

This pull request reworks the customer and customer timeline descriptions, and related files, to conform to the [writing style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md).

## Links

N/A

## Checklist

- [x] Writing style
- [x] API design standards

2022-09-21 08:09 UTC, Boydbueno commented on openapi/paths/customers@{id}@edd-timeline.yaml
> +    Creates an EDD timeline comment or custom defined event.
It is not possible to create custom defined events with this endpoint
```suggestion
    Creates an EDD timeline comment.
```

2022-09-21 08:45 UTC, noon-dawg commented on openapi/components/schemas/Edd/Edd.yaml
> +    description: Date and time at which the next EDD score is scheduled.
Looks good!

2022-09-21 09:09 UTC, noon-dawg commented on openapi/components/schemas/Timelines/CustomerTimeline.yaml
> +      event type_ operation.
Added in [3788b03](https://github.com/Rebilly/api-definitions/pull/1031/commits/3788b03a75801c3c09938d1eeacc0263b95497de)

It took me longer than it should have to figure out how to do this 😅 

([You can check out here](https://preview.redoc.ly/openapi-api/rework-descriptions-7/tag/Customers-timeline/operation/PostCustomerTimeline#!path=customEventType&t=request))

2022-09-21 12:29 UTC, Boydbueno approved these changes, later dismissed

2022-09-21 20:32 UTC, Boydbueno approved these changes, later dismissed

2022-09-26 08:36 UTC, Boydbueno approved these changes, later dismissed

2022-09-26 12:53 UTC, Boydbueno submitted a review, later dismissed

2022-09-27 09:39 UTC, adamaltman requested changes

2022-09-27 09:39 UTC, adamaltman commented on openapi/components/schemas/CurrencyCode.yaml
> +  Currency code in ISO 4217 format. Examples: `USD`, `EUR`, `CNY`.
```suggestion
  Currency code in ISO 4217 format.
```
The docs generate examples from defined examples already. We should generally not include examples in description.

2022-09-27 09:39 UTC, adamaltman commented on openapi/components/schemas/CustomerInformation.yaml
> +      Currency code in ISO 4217 format. Examples: `USD`, `EUR`, `CNY`.
```suggestion
      Currency code in ISO 4217 format.
    minLength: 3
    maxLength: 3
    example: USD
```

2022-09-27 09:39 UTC, adamaltman commented on openapi/components/schemas/SubscriptionSummaryMetrics.yaml
> +      Currency code in ISO 4217 format. Examples: `USD`, `EUR`, `CNY`.
```suggestion
      Currency code in ISO 4217 format.
    minLength: 3
    maxLength: 3
    example: USD
```

2022-09-27 10:32 UTC, adamaltman commented on openapi/components/schemas/Edd/Edd.yaml
> +    description: Date and time at which the EDD score is updated.
```suggestion
    description: Date and time in ISO 8601 format when the EDD score is updated.
```

2022-09-27 12:54 UTC, adamaltman approved these changes

2022-09-28 08:05 UTC, ashkarpetin approved these changes

2022-09-28 08:14 UTC, merged