Rework balance transaction descriptions
Rebilly/api-definitions pull request #1044
Opened 2022-09-23 13:10 UTC by noon-dawg

## Summary

This pull request reworks the balance transaction descriptions, and related files, to conform to the [writing style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md).

### [Preview generated docs]()

## Links

N/A

## Checklist

- [x] Writing style
- [x] API design standards

2022-09-23 13:52 UTC, n-fasano commented on openapi/components/requestBodies/Webhooks/BalanceTransactionSettled.yaml
> +          description: Balance transaction ID.
```suggestion
          description: ID of the balance transaction.
```

2022-09-23 13:52 UTC, n-fasano commented on openapi/components/requestBodies/Webhooks/InvoiceRevenueRecognized.yaml
> +          description: Revenue recognition ID of the invoice.
```suggestion
          description: ID of the revenue recognition.
```

2022-09-23 13:52 UTC, n-fasano commented on openapi/components/schemas/BalanceTransactions/BalanceTransaction.yaml
> +    description: ID of the transaction entry.
```suggestion
    description: ID of the balance transaction.
```

2022-09-23 13:52 UTC, n-fasano commented on openapi/components/schemas/BalanceTransactions/BalanceTransaction.yaml
> +    description: Type of entry.
```suggestion
    description: Type of the balance transaction.
```

2022-09-23 14:35 UTC, noon-dawg commented on openapi/components/requestBodies/Webhooks/InvoiceRevenueRecognized.yaml
> +          description: Revenue recognition ID of the invoice.
Are losing information here on the invoice aspect?

2022-09-23 14:38 UTC, n-fasano commented on openapi/components/requestBodies/Webhooks/InvoiceRevenueRecognized.yaml
> +          description: Revenue recognition ID of the invoice.
```suggestion
          description: ID of the invoice revenue recognition.
```

Maybe this would be better.

2022-09-23 16:58 UTC, noon-dawg commented on openapi/components/requestBodies/Webhooks/InvoiceRevenueRecognized.yaml
> +          description: Revenue recognition ID of the invoice.
Updated to: `ID of the recognized revenue.`

 ([2abb663](https://github.com/Rebilly/api-definitions/pull/1044/commits/2abb6634ffc00945798ff1331669f64df1566dd1))

2022-09-24 06:44 UTC, n-fasano approved these changes, later dismissed

2022-09-26 08:02 UTC, Boydbueno commented on openapi/openapi.yaml
> +      > **Important:** These operation is experimental and may not be
```suggestion
      > **Important:** This operation is experimental and may not be
```

2022-09-26 08:02 UTC, Boydbueno commented on openapi/openapi.yaml
> +      > **Important:** These operation is experimental and may not be
```suggestion
      > **Important:** This operation is experimental and may not be
```

2022-09-26 08:35 UTC, Boydbueno submitted a review, later dismissed

2022-09-27 09:29 UTC, adamaltman requested changes
The accepted phrase is query parameters today.

Source: OpenAPI specification 3.0 and Google Trends

<img width="1173" alt="2022-09-27_04-28-50" src="https://user-images.githubusercontent.com/1161871/192489478-03464282-281a-4b30-bb47-0730a8bc2459.png">

2022-09-27 09:29 UTC, adamaltman commented on openapi/components/requestBodies/Webhooks/BalanceTransactionSettled.yaml
> +            querystring parameter.
```suggestion
            query parameter.
```

2022-09-27 09:29 UTC, adamaltman commented on openapi/components/requestBodies/Webhooks/InvoiceRevenueRecognized.yaml
> +            expand querystring parameter.
```suggestion
            expand query parameter.
```

2022-09-27 09:29 UTC, adamaltman commented on openapi/components/requestBodies/Webhooks/InvoiceWebhook.yaml
> +            expand querystring parameter.
```suggestion
            expand query parameter.
```

2022-09-27 09:29 UTC, adamaltman commented on openapi/components/schemas/BalanceTransactions/BalanceTransactionLinks.yaml
> +      querystring parameter.
```suggestion
      query parameter.
```

2022-09-27 10:29 UTC, adamaltman requested changes, later dismissed

2022-09-27 10:29 UTC, adamaltman commented on openapi/openapi.yaml
> +      backward compatible.
```suggestion
      > **Important:** This operation is experimental and may change.
```

2022-09-27 10:29 UTC, adamaltman commented on openapi/openapi.yaml
> +      backward compatible.
```suggestion
      > **Important:** This operation is experimental and may change.
```

2022-09-27 10:29 UTC, adamaltman commented on openapi/paths/balance-transactions.yaml
> +    backward compatible.
```suggestion
    > **Important:** This operation is experimental and may change.
```

2022-09-27 10:29 UTC, adamaltman commented on openapi/paths/balance-transactions@{id}.yaml
> +    backward compatible.
```suggestion
    > **Important:** This operation is experimental and may change.
```

2022-09-28 13:42 UTC, n-fasano submitted a review, later dismissed

2022-09-28 13:42 UTC, n-fasano commented on openapi/paths/balance-transactions@{id}.yaml
> +      description: Balance transaction entry retrieved.
```suggestion
      description: Balance transaction retrieved.
```

Not sure if the word `entry` adds anything here?

2022-09-28 13:44 UTC, n-fasano submitted a review, later dismissed

2022-09-28 13:48 UTC, ashkarpetin commented on openapi/openapi.yaml
> +      > **Important:** This operation is experimental and may change.
```suggestion
      > **Important:** These operations are experimental and may change.
```

There are several `Fees` operations

2022-09-28 14:19 UTC, ashkarpetin commented on openapi/openapi.yaml
> +      > **Important:** This operation is experimental and may change.
```suggestion
      > **Important:** These operations are experimental and may change.
```

2022-09-28 14:20 UTC, ashkarpetin approved these changes

2022-09-28 14:23 UTC, dara123 approved these changes

2022-09-28 14:24 UTC, merged