Implement patch credit memo endpoint defs
Rebilly/api-definitions pull request #1046
Opened 2022-09-26 08:07 UTC by nanobash

## Summary

- [x] Implement patch credit memo endpoint definitions
- [x] Make PATCH /credit-memos/{creditMemoId} properties optional

## Checklist

- [x] Writing style
- [x] API design standards

2022-09-26 14:14 UTC, nanobash commented on openapi/paths/credit-memos@{id}.yaml
> +      description: CreditMemo and/or allocations were/was updated.
The idea is that, this endpoint can update credit-memo and credit-memo allocations, or separately credit memo only or allocations only. That's why used `and/or`, however I also don't like writing this way

2022-09-26 14:43 UTC, noon-dawg commented on openapi/paths/credit-memos@{id}.yaml
> +  summary: Patch a credit memo and/or allocations with specified ID
nitpick: It’s best to avoid using the same verb as the HTTP request in the summary and descriptions (based on our style)
```suggestion
  summary: Update credit memo, allocation, or both
```

2022-09-26 14:43 UTC, noon-dawg commented on openapi/paths/credit-memos@{id}.yaml
> +    Patch a credit memo and/or allocations with specified identifier string.
```suggestion
  description: |-
    Updates a credit memo, credit memo allocation, or both credit memo and allocation based a specified ID.
```

2022-09-26 14:50 UTC, noon-dawg commented on openapi/paths/credit-memos@{id}.yaml
> +    Updates a credit memo, credit memo allocation, or both credit memo and allocation based a specified ID.
sorry, I made a typo here
```suggestion
    Updates a credit memo, credit memo allocation, or both credit memo and allocation with a specified ID.
```

2022-09-26 17:58 UTC, noon-dawg commented
LGTM!

2022-09-26 18:43 UTC, noon-dawg reviewed
All very minor suggestions

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: An invoice item's ID that the credit item is referenced to.
nitpick: suggestion to avoid ending in a preposition
```suggestion
        description: ID of the invoice item on which the the credit item is referenced.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: Credit memo item's description.
nitpick: suggestion to avoid possessive ('s)
```suggestion
        description: Description of the credit memo item.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: Credit memo item's price.
nitpick: suggestion to avoid possessive ('s)
```suggestion
        description: Price of the credit memo item.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: Credit memo item's quantity.
nitpick: suggestion to avoid possessive ('s)
```suggestion
        description: Quantity of the credit memo item.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: Credit memo item's total price.
nitpick: suggestion to avoid possessive ('s)
```suggestion
        description: Total price of the credit memo item.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: The related product's ID.
nitpick: suggestion to avoid possessive ('s)
```suggestion
        description: ID of the related product.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: The related plan's ID.
nitpick: suggestion to avoid possessive ('s)
```suggestion
        description: ID of the related plan ID.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: Credit memo created time.
nitpick: suggestion to use this style for timestamps
```suggestion
  description: Date and time at which the credit memo was created.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: Increments when the credit memo is modified.
nitpick: suggestion to add detail
```suggestion
  description: Number of times the credit memo has been modified.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +    partially-applied: >-
```suggestion
    partially-applied: |-
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +      credit of amount `unusedAmount` can be created from it.
nitpick: suggestion to help make it more concise 
```suggestion
      A partial amount of the credit memo has been applied.
      A credit can be created from the remaining amount.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: Credit memo reason code.
nitpick: suggestion based on style
```suggestion
  description: Reason for the credit memo.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: A public description (visible to customers) clarifying the purpose of the credit memo.
nitpick:  where possible, we should avoid adding text in parenthesis

```suggestion
  description: Public description, that is visible to customers, which describes the purpose of the credit memo.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: The sum of all credits in the credit memo (items, shipping, tax).
nitpick: suggestion to avoid possessive parenthesis 

```suggestion
  description: Total amount of all credits in the credit memo, including: items, shipping, and tax.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: The amount of `totalAmount` which hasn't been allocated anywhere yet.
nitpick: suggestion to help make it more concise
```suggestion
  description: Unused credit memo amount that has not been allocated.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +              description: ID of the transaction that the credit memo is allocated to.
nitpick: suggestion to avoid ending in a preposition
```suggestion
              description: ID of the transaction on which the credit memo is allocated.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: ID of the invoice which the credit memo is issued upon.
nitpick: suggestion to avoid ending in a preposition
 
```suggestion
  description: ID of the invoice on which the credit memo is issued.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +              description: Credit memo allocation time.
nitpick: suggestion to use this style for timestamps

```suggestion
              description: Date and time at which the credit memo is allocated.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: Credit memo item ID.
nitpick: suggestion based on style
```suggestion
        description: ID of the credit memo item.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +    applied: All the amount of the credit memo has been applied, no more credit can be created from it.
```suggestion
    applied: The full amount of the credit memo has been applied. No more credit can be created from it.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +      but the credit memo cannot be used anymore.
nitpick: suggestion to remove part of this description

As a reader, `credit has or hasn't been created from the credit memo` does not tell me something. I think it's best to leave this line out

```suggestion
    voided: |-
       Credit memo has been voided and cannot be used anymore.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: The (invoice's) shipping amount to credit.
nitpick: suggestion to avoid possessive ('s) & parenthesis 
```suggestion
  description: Shipping amount of an invoice to credit.
```

2022-09-26 18:43 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: The (invoice's) tax amount to credit.
nitpick: suggestion to avoid possessive ('s) & parenthesis 
```suggestion
  description: Tax amount of an invoice to credit.
```

2022-09-27 09:22 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +              readOnly: true
Isn't the server timestamp already read-only?

2022-09-27 09:23 UTC, adamaltman requested changes

2022-09-27 09:23 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  type: array
This doesn't make sense to me as an array. Let's discuss it.

2022-09-27 10:39 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +              readOnly: true
These params were just moved to separate .yaml file, though updated as suggested, thank you

2022-09-27 10:39 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  type: array
These params were just moved to separate .yaml file, though updated as suggested, thank you

2022-09-27 12:59 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        List of transactions (typically refunds, credits, and chargebacks) that are allocated to reducing unused amount of the credit memo.
suggestion: possible typo
```suggestion
        List of transactions (typically refunds, credits, and chargebacks) that are allocated to reduce the unused amount of a credit memo.
```

2022-09-27 13:35 UTC, noon-dawg commented
LGTM!

2022-09-27 20:22 UTC, nanobash commented
@Rebilly/php please review

2022-09-28 08:05 UTC, adamaltman commented on openapi/paths/credit-memos@{id}.yaml
> +            $ref: ../components/schemas/CreditMemos/CreditMemo.yaml
What is the difference between these two schemas:

CreditMemoProperties and CreditMemo?

2022-09-28 14:36 UTC, nanobash commented on openapi/paths/credit-memos@{id}.yaml
> +            $ref: ../components/schemas/CreditMemos/CreditMemo.yaml
The difference comes with the required properties. **CreditMemoProperties.yaml** is included inside **CreditMemo.yaml**. `CreditMemo.yaml` defines two properties as required. I needed to separate properties in order to use them on **PATCH /credit-memos/{creditMemoId}** endpoint but without required properties.

We decided to implement **PATCH /credit-memos/{creditMemoId}** endpoint for only updating either credit memo or allocations or both of them (updating both of them has the same behaviour as **PUT /credit-memos/{creditMemoId}**).

On **PATCH** endpoint credit-memo editing payload is not mandatory, therefore **customerId** and **currency** properties are not required anymore. Thus, I am just reusing `CreditMemoProperties.yaml` on PATCH endpoint definitions not to repeat entire properties definitions code.

2022-09-29 08:12 UTC, adamaltman commented on openapi/paths/credit-memos@{id}.yaml
> +            $ref: ../components/schemas/CreditMemos/CreditMemoProperties.yaml
It should have `type: object`.

2022-09-29 14:37 UTC, nanobash commented on openapi/paths/credit-memos@{id}.yaml
> +            $ref: ../components/schemas/CreditMemos/CreditMemoProperties.yaml
Added, thank you

2022-09-29 21:11 UTC, nanobash commented
@Rebilly/php please review

2022-10-02 12:03 UTC, adamaltman approved these changes, later dismissed

2022-10-04 12:12 UTC, nanobash commented
@Rebilly/php please review

2022-10-05 01:54 UTC, ninjasimon submitted a review, later dismissed

2022-10-11 20:07 UTC, nanobash commented
@Rebilly/php please review

2022-10-12 11:43 UTC, adamaltman commented
@nanobash there is a conflict.

2022-10-12 15:32 UTC, nanobash commented
@Rebilly/php please review

2022-10-12 15:33 UTC, ninjasimon approved these changes, later dismissed

2022-10-13 11:02 UTC, nanobash commented
@Rebilly/php please review

2022-10-13 15:34 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemo.yaml
> +    description: ID of the invoice on which the credit memo is issued.
typo: I think I may have added this one

```suggestion
    description: ID of the invoice to which the credit memo is issued.
```

2022-10-13 15:35 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +  description: Allocations reduce unused amount of the credit memo.
typo
```suggestion
  description: Allocations reduce the unused amount of a credit memo.
```

2022-10-13 15:36 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +        description: ID of the related plan ID.
issue: possible typo
```suggestion
        description: ID of the related plan.
```

2022-10-13 15:38 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CreditMemoProperties.yaml
> +            description: ID of the transaction that the credit memo is allocated to.
nitpick: suggestion to avoid ending in with a preposition
```suggestion
            description: ID of the transaction to which the credit memo is allocated.
```

2022-10-13 15:41 UTC, noon-dawg commented
LGTM!

2022-10-13 15:42 UTC, nanobash commented
@Rebilly/php please review

2022-10-13 17:24 UTC, vykhrystiuk approved these changes

2022-10-13 17:29 UTC, ashkarpetin approved these changes

2022-10-14 10:03 UTC, merged