Update billing portal descriptions
Rebilly/api-definitions pull request #1048
Opened 2022-09-26 13:25 UTC by noon-dawg

## Summary

This pull request reworks the billing portal descriptions, and related files, to conform to the [writing style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md).

### [Preview generated docs](https://preview.redoc.ly/openapi-api/rework-description-10/tag/Billing-portals)

## Links

N/A

## Checklist

- [x] Writing style
- [x] API design standards

2022-09-26 13:54 UTC, ashkarpetin submitted a review, later dismissed

2022-09-27 09:18 UTC, adamaltman commented on openapi/components/schemas/Common/CommonBillingPortal.yaml
> +      also the processor account and billing descriptor used for payment
```suggestion
      also the gateway account and billing descriptor used for payment
```
Is this what ou mean?

2022-09-27 09:31 UTC, adamaltman requested changes

2022-09-27 09:31 UTC, adamaltman commented on openapi/components/schemas/Common/CommonBillingPortal.yaml
> +      make it human-readable. Example: `https://company.com/billing-portal/{slug}`.
```suggestion
      make it human-readable. Example: `https://example.com/billing-portal/{slug}`.
```
We should not use a real URL in the example unless we have permission.

2022-09-27 10:21 UTC, adamaltman commented on openapi/paths/billing-portals.yaml
> +    Retrieves a list of billing portals.
```suggestion
  description: Retrieves a list of billing portals.
```
In this case of a one-liner, the block syntax isn't needed.

2022-09-27 10:21 UTC, adamaltman commented on openapi/paths/billing-portals.yaml
> +    Creates a billing portal.
```suggestion
  description: Creates a billing portal.
```

2022-09-27 10:22 UTC, adamaltman commented on openapi/paths/billing-portals@{id}.yaml
> +    Retrieves a billing portal with a specified identifier string.
```suggestion
  description: Retrieves a billing portal with a specified identifier string.
```

2022-09-27 10:22 UTC, adamaltman commented on openapi/paths/billing-portals@{id}.yaml
> +    identifier string.
```suggestion
  description: Creates or updates (upserts) a billing portal with a specified identifier string.
```

2022-09-27 10:23 UTC, adamaltman commented on openapi/paths/billing-portals@{id}.yaml
> +    Deletes a billing portal with a specified identifier string.
```suggestion
  description: Deletes a billing portal with a specified identifier string.
```

2022-09-27 22:02 UTC, Boydbueno approved these changes

2022-09-28 05:26 UTC, n-fasano approved these changes

2022-09-28 08:03 UTC, adamaltman approved these changes

2022-09-28 08:22 UTC, merged