Add scheme for webId and organizationID
Rebilly/api-definitions pull request #1073
Opened 2022-10-12 18:26 UTC by noon-dawg

## Summary

This pull request adds a scheme for webId and organizationID.

In an earlier commit, server content broke server URLs, and the commit and was reverted. 

This pull request re-adds schemes for `webId` and `organizationID` from that commit, but the problematic server content.

## Links

- https://github.com/Rebilly/api-definitions/pull/1062
- https://github.com/Rebilly/api-definitions/pull/1069

## Checklist

- [x] Writing style
- [x] API design standards

2022-10-12 19:02 UTC, ashkarpetin commented on openapi/components/schemas/Applications/OwnerApplicationInstance.yaml
> +          -  $ref: ../../schemas/Organizations/OrganizationId.yaml
```suggestion
          - $ref: ../../schemas/Organizations/OrganizationId.yaml
```

2022-10-12 19:03 UTC, ashkarpetin commented on openapi/components/schemas/Subscription/OrderTypes/SubscriptionOrder.yaml
> +          -  $ref: ../../../schemas/Organizations/OrganizationId.yaml
```suggestion
          - $ref: ../../../schemas/Organizations/OrganizationId.yaml
```

2022-10-12 19:03 UTC, ashkarpetin commented on openapi/components/schemas/Websites/Website.yaml
> +      -  $ref: ../Websites/WebsiteId.yaml
```suggestion
      - $ref: ../Websites/WebsiteId.yaml
```

2022-10-13 07:47 UTC, ashkarpetin submitted a review, later dismissed

2022-10-13 16:24 UTC, ashkarpetin commented on openapi/components/schemas/Applications/OwnerApplicationInstance.yaml
> +          - $ref: ../../schemas/Organizations/OrganizationId.yaml
```suggestion
          - $ref: ../Organizations/OrganizationId.yaml
```

2022-10-13 16:25 UTC, ashkarpetin commented on openapi/components/schemas/GatewayAccountConfig/SecureTrading.yaml
> +            $ref: ../../schemas/Websites/WebsiteId.yaml
```suggestion
            $ref: ../Websites/WebsiteId.yaml
```

2022-10-13 16:28 UTC, ashkarpetin commented on openapi/components/schemas/GatewayAccountConfig/SecureTrading.yaml
> +            $ref: ../../schemas/Websites/WebsiteId.yaml
I think this should be reverted, this property is not related with Rebilly website

2022-10-13 16:31 UTC, ashkarpetin commented on openapi/components/schemas/Subscription/OrderTypes/OneTimeOrder.yaml
> +          - $ref: ../../../schemas/Organizations/OrganizationId.yaml
```suggestion
          - $ref: ../../Organizations/OrganizationId.yaml
```

2022-10-13 16:31 UTC, ashkarpetin commented on openapi/components/schemas/Subscription/OrderTypes/SubscriptionOrder.yaml
> +          - $ref: ../../../schemas/Organizations/OrganizationId.yaml
```suggestion
          - $ref: ../../Organizations/OrganizationId.yaml
```

2022-10-13 16:33 UTC, ashkarpetin commented on openapi/components/schemas/Websites/Website.yaml
> +      - $ref: ../../schemas/Organizations/OrganizationId.yaml
```suggestion
      - $ref: ../Organizations/OrganizationId.yaml
```

2022-10-13 16:33 UTC, ashkarpetin commented on openapi/components/schemas/Websites/WebsiteId.yaml
> +  - $ref: ../../schemas/ResourceId.yaml
```suggestion
  - $ref: ../ResourceId.yaml
```

2022-10-13 16:42 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/SecureTrading.yaml
> +            $ref: ../../schemas/Websites/WebsiteId.yaml
Updated in [f1c68a9](https://github.com/Rebilly/api-definitions/pull/1073/commits/f1c68a95a137f5cb1c9e7b6ca5bbfbd3dfc73449)

2022-10-13 16:45 UTC, noon-dawg commented
Thanks for reviewing, and for your patience @ashkarpetin! 
In future, I will take better care to ensure that the references are correct

2022-10-13 16:48 UTC, ashkarpetin approved these changes, later dismissed

2022-10-14 16:25 UTC, adamaltman requested changes

2022-10-14 16:25 UTC, adamaltman commented on openapi/components/schemas/Organizations/OrganizationId.yaml
> +    - $ref: ../ResourceId.yaml
It will be much cleaner without the `allOf` here.

2022-10-14 16:25 UTC, adamaltman commented on openapi/components/schemas/Websites/WebsiteId.yaml
> +  - $ref: ../ResourceId.yaml
And without the `allOf` here too. Sometimes reuse adds more complexity than value. I like `WebsiteId` and I don't like that it reuses `ResourceId`.

2022-10-17 10:53 UTC, noon-dawg commented on openapi/components/schemas/Websites/WebsiteId.yaml
> +  - $ref: ../ResourceId.yaml
Good point, this was overly complex. I've updated updated the references to reuse the descriptions only

2022-10-17 12:34 UTC, ashkarpetin commented on openapi/components/schemas/Websites/WebsiteId.yaml
> +  [Obtain an organization ID and website ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
```suggestion
type: string
description: |-
  Unique website identifier string. A website is where an
  organization obtains a customer through a subscription. For more
  information, see
  [Obtain an organization ID and website ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
maxLength: 50
example: 4f6cf35x-2c4y-483z-a0a9-158621f77a21
```

@noon-dawg [This](https://github.com/Rebilly/api-definitions/pull/1073/commits/12030886e46bfa0567ec8d6ec2ee0738e4e3fded) commit doesn't seem correct.

Please check customerId schema: https://github.com/Rebilly/api-definitions/blob/main/openapi/components/schemas/Cust

2022-10-17 12:35 UTC, ashkarpetin commented on openapi/components/schemas/Organizations/OrganizationId.yaml
> +  For more information, see [Obtain an organization ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
```suggestion
type: string
description: |-
  Unique organization identifier.
  An organization is an entity that represents a company.
  For more information, see [Obtain an organization ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
maxLength: 50
example: 4f6cf35x-2c4y-483z-a0a9-158621f77a21
```

2022-10-17 15:29 UTC, noon-dawg commented on openapi/components/schemas/Websites/WebsiteId.yaml
> +  [Obtain an organization ID and website ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
Thanks for your help @ashkarpetin. I've removed references to ResourceId in [this commit ](https://github.com/Rebilly/api-definitions/pull/1073/commits/58d2fe96415b57fdeda5ca4aeb883e6b69c60f0d)

2022-10-17 15:56 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrder.yaml
> +    $ref: ../Websites/WebsiteId.yaml
Missing allOf

2022-10-17 15:57 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrderPreview.yaml
> +    $ref: ../Websites/WebsiteId.yaml
Missing allOf

2022-10-17 15:57 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonTransaction.yaml
>      readOnly: true
Missing allOf

2022-10-17 15:57 UTC, ashkarpetin commented on openapi/components/schemas/Customer.yaml
> +    $ref: ./Websites/WebsiteId.yaml
Missing allOf

2022-10-17 15:57 UTC, ashkarpetin commented on openapi/components/schemas/GatewayAccount.yaml
>      readOnly: true
Missing allOf

2022-10-17 15:57 UTC, ashkarpetin commented on openapi/components/schemas/Storefront/Account.yaml
>      readOnly: true
Missing allOf

2022-10-17 15:57 UTC, ashkarpetin commented on openapi/components/schemas/Storefront/Purchase.yaml
>      writeOnly: true
Missing allOf

2022-10-17 15:57 UTC, ashkarpetin commented on openapi/components/schemas/Subscription/OrderTypes/OneTimeOrder.yaml
>          readOnly: true
Missing allOf

2022-10-18 07:35 UTC, noon-dawg commented on openapi/components/schemas/Applications/OwnerApplicationInstance.yaml
> +        $ref: ../Organizations/OrganizationId.yaml
Updated missing allOf fields in [078d166](https://github.com/Rebilly/api-definitions/pull/1073/commits/078d166c1be10f129a715b068ac9f0886fb87131)

2022-10-18 09:35 UTC, ashkarpetin commented on openapi/components/schemas/Applications/OwnerApplicationInstance.yaml
>            - $ref: ../ResourceId.yaml
No need to combine with ResourceId schema

2022-10-18 12:08 UTC, ashkarpetin commented on openapi/components/schemas/Applications/OwnerApplicationInstance.yaml
> +        $ref: ../Organizations/OrganizationId.yaml
Please use allOf

2022-10-18 12:09 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrder.yaml
> +    $ref: ../Websites/WebsiteId.yaml
Please use allOf

2022-10-18 12:09 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrder.yaml
>        - $ref: ../ResourceId.yaml
Please remove ResourceId

2022-10-18 12:10 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrder.yaml
> +    $ref: ../Websites/WebsiteId.yaml
```suggestion
```

2022-10-18 12:10 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrder.yaml
>        - $ref: ../ResourceId.yaml
```suggestion
      - $ref: ../Websites/WebsiteId.yaml
```

2022-10-18 12:10 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrderPreview.yaml
> +    $ref: ../Websites/WebsiteId.yaml
```suggestion
```

2022-10-18 12:11 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonOrderPreview.yaml
>        - $ref: ../ResourceId.yaml
```suggestion
      - $ref: ../Websites/WebsiteId.yaml
```

2022-10-18 12:11 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonTransaction.yaml
> +    $ref: ../Websites/WebsiteId.yaml
```suggestion
```

2022-10-18 12:11 UTC, ashkarpetin commented on openapi/components/schemas/Common/CommonTransaction.yaml
>        - $ref: ../ResourceId.yaml
```suggestion
      - $ref: ../Websites/WebsiteId.yaml
```

2022-10-18 12:27 UTC, ashkarpetin approved these changes, later dismissed

2022-10-18 15:56 UTC, vykhrystiuk commented on openapi/components/schemas/Websites/WebsiteId.yaml
> +  [Obtain an organization ID and website ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
```suggestion
  Unique website identifier string.
  A website is where an organization obtains a customer through a subscription. For more
  information, see
  [Obtain an organization ID and website ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
```

https://github.com/Rebilly/api-definitions/pull/1077#discussion_r996302156

2022-10-18 16:04 UTC, ashkarpetin approved these changes, later dismissed

2022-10-18 16:19 UTC, vykhrystiuk approved these changes, later dismissed

2022-10-20 01:56 UTC, adamaltman commented on openapi/components/schemas/Websites/WebsiteId.yaml
> +example: 4f6cf35x-2c4y-483z-a0a9-158621f77a21
```suggestion
example: example.com
```
I'm making this identifier different than the others, or they all blend together.

2022-10-20 06:57 UTC, ashkarpetin approved these changes

2022-10-20 09:01 UTC, Boydbueno approved these changes

2022-10-20 19:17 UTC, vykhrystiuk approved these changes

2022-11-05 11:46 UTC, adamaltman approved these changes

2022-11-05 11:51 UTC, merged