Rework broadcast message descriptions
Rebilly/api-definitions pull request #1077
Opened 2022-10-14 15:17 UTC by noon-dawg

## Summary

This pull request reworks the broadcast message descriptions, and related files, to conform to the [writing style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md).

### [Preview generated docs](https://preview.redoc.ly/openapi-api/rework-descriptions-11/tag/Invoices)

## Links

N/A

## Checklist

- [x] Writing style
- [x] API design standards

2022-10-14 16:48 UTC, vykhrystiuk commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +    description: Date and time at which the message is schedule to send.
```suggestion
    description: Date and time at which the message is scheduled to send.
```

2022-10-15 12:52 UTC, adamaltman requested changes

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +      the `filter=` prefix. Examples: `firstName:John`, `firstName:John;lastName:Doe`.
https://sembr.org/
```suggestion
      This field uses the same syntax as the `query` filter,
      but without the `filter=` prefix. Examples: `firstName:John`, `firstName:John;lastName:Doe`.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +    description: Title of the message. This title is displayed in reports.
```suggestion
    description: Title of the message. This title displays in reports.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +            there are no versions, this field is empty.
```suggestion
            Version number of the message.
            Use this field to distinguish between multiple messages by name and version number.
            If there are no versions, this field is empty.
```
https://sembr.org/

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +            the message template will be used.
```suggestion
            Weight distribution value that is assigned to a template for a split test.
            Each template in a split test can be assigned a weight.
            The higher the weight value, the more likely the message template will be used.
```
https://sembr.org/

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +            making a weighted template selection.
```suggestion
            The split test algorithm does not assess locale when making a weighted template selection.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +            to the remaining customers or leads.
```suggestion
            Split tests send variations of the same message to different customers or leads.
            You can then send the winning message to the remaining customers or leads.
```
https://sembr.org/

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +                    In the response, you receive the email and a token.
```suggestion
                      In the response, you receive the email and a token.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +                    token as the path parameter.
```suggestion
                    1. [Verify the email delivery](../../Email-delivery-settings/operation/PutEmailDeliverySettingsVerification) by passing the token as the path parameter.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +                  is permitted for this field.
```suggestion
                description: |-
                  Subject of the message.
                  The use of template placeholders is permitted for this field.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +                  template placeholders is permitted for this field.
```suggestion
                  Text body of the message.
                  To use content from the `html` field, leave this field empty.
                  The use of template placeholders is permitted for this field.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +                  template placeholders is permitted for this field.
```suggestion
                  HTML body of the message.
                  To use content from the `text` field, leave this field empty.
                  The use of template placeholders is permitted for this field.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +                  5646](https://tools.ietf.org/html/rfc5646) format.
```suggestion
                  Language locale identifier in [RFC 5646](https://tools.ietf.org/html/rfc5646) format.
```

2022-10-15 12:52 UTC, adamaltman commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +      processing.
```suggestion
      Use this filter to select customers during broadcast message processing.
```

2022-10-17 08:12 UTC, noon-dawg commented on openapi/components/schemas/BroadcastMessages/BroadcastMessage.yaml
> +      the `filter=` prefix. Examples: `firstName:John`, `firstName:John;lastName:Doe`.
Thanks for sharing! I wasn't aware of this convention

2022-10-17 08:18 UTC, noon-dawg commented
Thanks for the review @adamaltman and @vykhrystiuk!

2022-10-17 19:25 UTC, vykhrystiuk approved these changes

2022-10-18 12:42 UTC, ashkarpetin approved these changes

2022-10-20 01:54 UTC, adamaltman approved these changes

2022-10-20 08:42 UTC, merged