Credit memo invoice allocations rework
Rebilly/api-definitions pull request #1083
Opened 2022-10-18 12:55 UTC by Boydbueno

## Summary

## Links

## Checklist

- [x] Writing style
- [x] API design standards

2022-11-17 08:50 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
nitpick: multi-line is not needed here (I'm aware that I may have added this in the first place 😅)
```suggestion
        description: List of invoices that the credit memo is allocated to.
```

2022-11-17 08:54 UTC, ashkarpetin submitted a review, later dismissed

2022-11-17 09:07 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
Yup, I think you did :D But I like it, it looks good, don't you think so?

![image](https://user-images.githubusercontent.com/6716383/202403665-bba302e9-8b9a-4632-8d6e-56fdbe521f7a.png)

2022-11-17 09:08 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
We have the same format for transaction amount description, shown on the picture

2022-11-17 09:20 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
Also for readability on IDE, I think it's better to be on multi line as it's too long. I will leave as is if you don't mind

2022-11-17 09:38 UTC, noon-dawg commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
yeah, that's cool. This is more of a note to myself 😄

2022-11-17 09:38 UTC, noon-dawg submitted a review, later dismissed

2022-11-19 00:38 UTC, adamaltman requested changes

2022-11-19 00:38 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
No, this is a hard no for me @nanobash . If it's one line, don't use a block scalar.

2022-11-22 12:27 UTC, adamaltman commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +            currency:
I think it should.

2022-11-23 12:46 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
Removed, thanks

2022-11-23 12:53 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +            currency:
Yes, currencies are the same.

2022-11-23 16:52 UTC, nanobash commented
@Rebilly/php please review

2022-11-23 17:35 UTC, nanobash commented on openapi/components/schemas/CreditMemos/CommonCreditMemo.yaml
> +          List of invoices that the credit memo is allocated to.
Actually I mixed up at first, I meant amount descriptions, they have multi line descriptions with two `-` options.

2022-11-24 14:25 UTC, nanobash commented
@Rebilly/php please review

2022-11-25 12:32 UTC, nanobash commented
@Rebilly/php @Rebilly/docs please review

2022-11-25 13:33 UTC, ashkarpetin approved these changes

2022-11-25 13:39 UTC, noon-dawg approved these changes

2022-11-27 15:14 UTC, adamaltman approved these changes

2022-11-28 08:18 UTC, merged