Journal
Rebilly/api-definitions pull request #1085
Opened 2022-10-19 12:24 UTC by justnero

## Summary

This is a suggested draft for journal

## Checklist

- [ ] Writing style
- [ ] API design standards

2022-10-20 01:58 UTC, adamaltman commented on openapi/openapi.yaml
> +      generated revenue.
```suggestion
```

2022-10-20 01:59 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +properties:
What about createdTime and updatedTime?

2022-10-20 09:58 UTC, justnero commented on openapi/components/schemas/Common/CommonPlan.yaml
> +  recognition:
We can add it to the product-level as well. Right now, the granularity used in QuickBooks integration is plan-level.

2022-10-27 11:10 UTC, adamaltman commented on openapi/components/schemas/Common/CommonPlan.yaml
> +  recognition:
I think that needs to be reworked. The granularity of the tax-level is on the product-level. I think it should be consistent. I don't think it should be an "as well" but an only.

2022-11-05 15:17 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    nullable: true
Incorrect use of nullable (see #1106 )

2022-11-05 15:17 UTC, adamaltman commented on openapi/components/schemas/Product.yaml
> +            nullable: true
Incorrect use of nullable

2022-11-05 15:18 UTC, adamaltman commented on openapi/components/schemas/Product.yaml
> +            nullable: true
Incorrect use of nullable.

2022-11-05 15:18 UTC, adamaltman commented on openapi/paths/journal-accounts.yaml
> +  description: |
```suggestion
  description: |-
```

2022-11-05 17:23 UTC, 2e3s commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    nullable: true
Isn't the type `string` here given by `allOf`? So if we want to specify that `null` is an acceptable type, we would need `nullable` anyway.

2022-11-05 17:24 UTC, 2e3s commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    nullable: true
It's incorrect that those options look rather optional than nullable, but I don't agree with the particular argument.

2022-11-06 12:34 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    nullable: true
No, it is not given by `allOf`. From the OpenAPI 3.0 spec:

> A true value adds "null" to the allowed type specified by the type keyword, only if type is explicitly defined within the same Schema Object. Other Schema Object constraints retain their defined behavior, and therefore may disallow the use of null as a value. A false value leaves the specified or default type unmodified. The default value is false.

2022-11-27 15:18 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalEntry.yaml
> +      - $ref: ../CurrencyCode.yaml
I'm confused. Is this only a revenue journal? What about other journal entries like credits and refunds, payments, and unearned revenue?

2022-11-27 15:18 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalEntry.yaml
> +      - $ref: ../ServerTimestamp.yaml
```suggestion
    $ref: ../CreatedTime.yaml
```

2022-11-27 15:19 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +      Amount of revenue estimated to be recognized at the scheduling date.
```suggestion
      Amount of revenue estimated to be recognized at the schedule date.
```

2022-11-27 15:21 UTC, adamaltman commented on openapi/paths/journal-entries.yaml
> +    Retrieve a list of journal entries.
```suggestion
  description: Retrieves a list of journal entries.
```

2022-11-27 15:22 UTC, adamaltman commented on openapi/paths/journal-entries.yaml
> +    Create a journal entry.
```suggestion
  description: Creates a journal entry.
```

2022-11-27 15:22 UTC, adamaltman commented on openapi/paths/journal-entries@{id}.yaml
> +    Retrieve a journal entry with a predefined identifier.
```suggestion
  description: Retrieves a journal entry with a predefined identifier.
```

2022-11-27 15:22 UTC, adamaltman commented on openapi/paths/journal-entries@{id}.yaml
> +    Update a journal entry.
```suggestion
  description: Updates a journal entry.
```

2022-11-27 15:23 UTC, adamaltman commented on openapi/paths/journal-entries@{id}@records.yaml
> +    Retrieve a list of journal records.
```suggestion
  description: Retrieves a list of journal records.
```

2022-11-27 15:23 UTC, adamaltman commented on openapi/paths/journal-entries@{id}@records.yaml
> +    Create a journal record.
```suggestion
  description: Creates a journal record.
```

2022-11-27 15:23 UTC, adamaltman commented on openapi/paths/journal-entries@{id}@records@{journalRecordId}.yaml
> +    Retrieve a journal record with a predefined identifier.
```suggestion
  description: Retrieves a journal record with a specified identifier.
```

2022-11-27 15:24 UTC, adamaltman commented on openapi/paths/journal-entries@{id}@records@{journalRecordId}.yaml
> +    Update a journal record.
```suggestion
  description: Updates a journal record.
```

2022-11-27 15:24 UTC, adamaltman commented on openapi/paths/journal-entries@{id}@records@{journalRecordId}.yaml
> +    Delete a journal record.
```suggestion
  description: Deletes a journal record.
```

2022-11-27 15:30 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    nullable: true
Incorrect use of nullable here. How can this be nullable though?

2022-11-27 15:31 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +  - creditAccount
where are these properties defined?

2022-11-27 15:33 UTC, adamaltman commented on openapi/components/schemas/Product.yaml
> +        type: object
```suggestion
        type: object
        nullable: true
```
How about making the object nullable?

2022-11-27 15:33 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +      - $ref: ../ServerTimestamp.yaml
```suggestion
    $ref: ../CreatedTime.yaml
```

2022-11-27 15:33 UTC, adamaltman commented on openapi/paths/journal-accounts.yaml
> +    Retrieve a list of journal accounts.
```suggestion
  description: Retrieves a list of journal accounts.
```

2022-11-27 15:34 UTC, adamaltman commented on openapi/paths/journal-accounts.yaml
> +    Create a journal account.
```suggestion
  description: Creates a journal account.
```

2022-11-27 15:34 UTC, adamaltman commented on openapi/paths/journal-accounts@{id}.yaml
> +    Retrieve a journal account with a predefined identifier.
```suggestion
  description: Retrieves a journal account with a specified identifier.
```

2022-11-27 15:34 UTC, adamaltman commented on openapi/paths/journal-accounts@{id}.yaml
> +    Update a journal account.
```suggestion
  description: Updates a journal account.
```

2022-11-27 15:35 UTC, adamaltman requested changes
Overall, I'm not sure about the name journal "record". Also, it doesn't seem correctly designed.

2022-12-01 21:24 UTC, 2e3s commented
> Also, it doesn't seem correctly designed.

@adamaltman do you mean the design in general, or only what you've highlighted in your comments?

2022-12-02 15:51 UTC, justnero commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +  - creditAccount
```suggestion
  - debitAccountId
  - creditAccountId
```

2022-12-02 17:49 UTC, justnero commented on openapi/components/schemas/Journal/JournalEntry.yaml
> +      - $ref: ../CurrencyCode.yaml
They all follow the same debit/credit logic, right now automation is scoped to revenue only, but can be extended in future.

2022-12-13 22:24 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    minItems: 1
```suggestion
    minItems: 0
```
?

2022-12-14 01:36 UTC, 2e3s commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    minItems: 1
I think it was copypasted, this constraint looks confusing for this property at all.

2022-12-14 03:45 UTC, adamaltman commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    type: array
Seems like this is actually an object (if it is similar to our other APIs).

2022-12-14 03:47 UTC, adamaltman submitted a review, later dismissed
There is the problem with the _embedded object (it's not an array), but this is otherwise good.

2022-12-15 08:32 UTC, noon-dawg reviewed
Nice use of our writing style!
I added a few minor suggestions

2022-12-15 08:32 UTC, noon-dawg commented on openapi/components/parameters/journalRecordId.yaml
> +description: Journal record identifier string.
nitpick: based on our style
```suggestion
description: ID of the journal record.
```

2022-12-15 08:32 UTC, noon-dawg commented on openapi/components/schemas/Journal/JournalAccount.yaml
> +    description: Creation date/time.
issue: [Timestamp fields](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#timestamp-fields)
```suggestion
    description: Date and time when the journal record was created.
```

2022-12-15 08:32 UTC, noon-dawg commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +      Value is ignored when updating a journal record with `type` of `automated`.
suggestion: suggestion for readability 
```suggestion
      This value is ignored when updating a journal record with a `type` of `automated`.
```

2022-12-15 08:32 UTC, noon-dawg commented on openapi/components/schemas/Journal/JournalRecord.yaml
> +    description: Related resource links.
nitpick: based on our style
```suggestion
    description: Related links.
```

2022-12-15 08:32 UTC, noon-dawg commented on openapi/paths/journal-accounts@{id}.yaml
> +  description: Retrieves a journal account with a predefined identifier.
nitpick: based on our style
```suggestion
  description: Retrieves a journal account with a specified ID.
```

2022-12-15 08:32 UTC, noon-dawg commented on openapi/paths/journal-entries@{id}.yaml
> +  description: Retrieves a journal entry with a predefined identifier.
nitpick: based on our style
```suggestion
  description: Retrieves a journal entry with a specified ID.
```

2022-12-15 08:32 UTC, noon-dawg commented on openapi/paths/journal-entries@{id}@records@{journalRecordId}.yaml
> +  description: Retrieves a journal record with a predefined identifier.
nitpick: based on our style
```suggestion
  description: Retrieves a journal record with a specified ID.
```

2022-12-15 17:57 UTC, 2e3s commented on openapi/components/schemas/Journal/JournalAccount.yaml
> +    description: Creation date/time.
Past time is prohibited :wink:

2022-12-15 18:17 UTC, 2e3s commented
devs please review

2022-12-15 19:16 UTC, noon-dawg commented on openapi/components/schemas/Journal/JournalAccount.yaml
> +    description: Creation date/time.
Thanks for spotting this 🙏

2022-12-15 19:17 UTC, noon-dawg commented
Looks good to me!

2022-12-15 19:24 UTC, 2e3s approved these changes
On @noon-dawg behalf

2022-12-15 19:25 UTC, ashkarpetin approved these changes

2022-12-15 19:43 UTC, merged