Cashier feature proposal
Rebilly/api-definitions pull request #1092
Opened 2022-10-24 12:00 UTC by justnero

## Summary

This is a draft proposal for cashier feature

## Checklist

- [ ] Writing style
- [ ] API design standards

2022-11-04 08:06 UTC, ikram-patah commented on plugins/products-bundler/mapping/Core.yaml
> +      - Cashier
question: 

In `Combined.yaml` file, Cashier is listed under Payments. Why is this not the case in `Core.yaml`. There is an existing Payments group.

2022-11-04 09:08 UTC, ikram-patah commented
Question: 

For Cashier Request status, 2 of the statuses are:
- `created`: Created, but not visited by the customer. Temporary state.
- `pending`: Visited, but no funds have been deposited yet. Temporary state.

Will BE be responsible for the update from status `created` to `pending` (detecting that the page is visited)?

I don’t see any PUT operation on a cashier request, so I don’t think client-side will be able to update the status. The status property is also a read-only.

2022-11-04 10:46 UTC, justnero commented on plugins/products-bundler/mapping/Core.yaml
> +      - Cashier
Just a mistake, feel free to move it to payments

2022-11-04 10:47 UTC, justnero commented
> Will BE be responsible for the update from status `created` to `pending` (detecting that the page is visited)?
> 
> I don’t see any PUT operation on a cashier request, so I don’t think client-side will be able to update the status. The status property is also a read-only.

First call to `StorefrontGetCashierRequest` will change the status implicitly

2022-11-07 18:54 UTC, lexerom commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +  multipleOf:
May be "**step**" is a better name here? 
```suggestion
  step:

2022-11-08 08:06 UTC, ikram-patah commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +  multipleOf:
suggestion: how about `multiplier` instead?

2022-11-08 08:15 UTC, jvc9109 commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +  multipleOf:
I agree with @lexerom . `multiplier` can be misleading since, without reading description, I would assume the progression will follow as:
```php
$minimum = 2.4;
$multiplier = 2;
$result = [2.4, 4.8, 9.6 ...];
```

2022-11-08 11:11 UTC, noon-dawg commented on openapi/components/schemas/Cashier/CashierStrategyAmounts.yaml
> +- If the calculator is set to `percent`: the amounts displayed to the customer are `[10, 12, 15, 20]`.
I may have added bad indentation here 😬 Sorry! 

```suggestion
    description: |-
        Cashier amounts calculator.
        This field specifies whether amounts are calculated using an absolute or percentage calculation.
        
        Amounts are specified in `baseAmount`, and increments are specified in `increments`.
        
        Example: `baseAmount: 10` and `increments: [20, 50, 100]`.
        
        - If the calculator is set to `absolute`: the amounts displayed to the customer are `[10, 30, 60, 110]`.
        - If the calculator is set to `percent`: the amounts displayed to the customer are `[10, 12, 15, 20]`.
```

2022-11-09 04:39 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      - $ref: ../ResourceId.yaml
Is it really an array?

Also, I would get rid of the `allOf`. What exactly are we using from there? An example? maxLength 50?

2022-11-09 04:40 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      query parameter.
```suggestion
    description: Embedded objects that are requested by the `expand` query parameter.
```

2022-11-09 04:41 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +    minItems: 1
This seems wrong. Can't we also have 0 items embedded?

2022-11-09 04:41 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +    description: >-
```suggestion
    description: |-
```

2022-11-09 04:41 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +      - $ref: ../ServerTimestamp.yaml
```suggestion
    $ref: ../CreatedTime.yaml
```

2022-11-09 04:42 UTC, adamaltman commented on openapi/openapi.yaml
> +      responsive design, built-in error messaging and validation.
https://sembr.org/

2022-11-09 04:43 UTC, adamaltman commented on openapi/openapi.yaml
> +      Use these operations to create and manage cashier requests and strategies.
```suggestion
      Use these operations to create and manage cashier requests and strategies for determining which amounts to display.
```

2022-11-09 04:45 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      - $ref: ../ResourceId.yaml
Comment meant for line 19.

2022-11-09 04:45 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      - $ref: ./CashierStrategyCustomAmount.yaml
This is invalid OpenAPI.

2022-11-09 04:46 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +    nullable: true
This is invalid OpenAPI -- type missing.

2022-11-09 04:46 UTC, adamaltman requested changes
A few changes

2022-11-11 03:06 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      - $ref: ../ResourceId.yaml
Don't use `allOf` here. You are missing maxLength and an example?

2022-11-11 03:11 UTC, adamaltman requested changes

2022-11-11 03:11 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +type: object
```suggestion
type: object
description: |-
      Custom amount restrictions.
      If this value is `null`,  custom amounts are prohibited.
      If `customAmount` is not specified when a cashier is created,
      amount restrictions are determined from a randomly selected strategy with a matching `filter` value.
nullable: true
```

2022-11-11 03:11 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      - $ref: ./CashierStrategyCustomAmount.yaml
```suggestion
    $ref: ./CashierStrategyCustomAmount.yaml
```

2022-11-11 03:11 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +      - $ref: ./CashierStrategyCustomAmount.yaml
```suggestion
  customAmount:
    $ref: ./CashierStrategyCustomAmount.yaml
```

2022-11-14 19:11 UTC, lexerom commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +      - $ref: ./CashierStrategyCustomAmount.yaml
I left it with allOf as suggested here https://redocly.com/docs/resources/ref-guide/#no-siblings, it can be done just with $ref from OpenApi 3.1 thou.

2022-11-15 13:43 UTC, adamaltman commented on openapi/openapi.yaml
> +      deposit funds.
```suggestion
      Rebilly hosted cashiers provide secure and compliant way to deposit funds.
```
https://sembr.org/

2022-11-15 13:44 UTC, adamaltman commented on openapi/paths/cashier-strategies@{id}.yaml
> +    Creates or updates (upserts) a cashier strategy with specified ID.
```suggestion
  description: Creates or updates (upserts) a cashier strategy with specified ID.
```

2022-11-15 13:48 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +      - $ref: ./CashierStrategyCustomAmount.yaml
```suggestion
    $ref: ./CashierStrategyCustomAmount.yaml
```

I've had to make extensive amounts of suggestions on this PR where I should not have had to do that.

This is disappointing. You mark my comments as addressed, but they are not.

2022-11-15 14:08 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +      - $ref: ./CashierStrategyCustomAmount.yaml
And you think this description above is better than the description in the original object? Such that it requires overriding to make it less complete? Do you realize this object above is used to create a cashier?

      Custom amount restrictions.
      If this value is `null`,  custom amounts are prohibited.
      If `customAmount` is not specified when a cashier is created,
      amount restrictions are determined from a randomly selected strategy with a matching `filter` value.

2022-11-15 14:26 UTC, lexerom commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +      - $ref: ./CashierStrategyCustomAmount.yaml
I think I missed the point "when a cashier is created", so it clarifies the purpose of it. Was thinking about recursive reference to cashier strategies, which is incorrect.

2022-11-24 07:35 UTC, noon-dawg commented on openapi/openapi.yaml
> +      Rebilly hosted cashiers provide secure and compliant way to deposit funds.
issue: typo
```suggestion
      Rebilly hosted cashiers provide a secure and compliant way to deposit funds.
```

2022-11-24 07:37 UTC, noon-dawg commented on openapi/paths/storefront/cashier-deposit.yaml
> +  description: Create a cashier deposit transaction.
nitpick: based on our style
```suggestion
  description: Creates a cashier deposit transaction.
```

2022-11-27 14:56 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategy.yaml
> +      - $ref: ../FilterString.yaml
This doesn't make sense. Does it?
```suggestion
```

2022-11-27 15:06 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      exclusiveMinimum: true
If it is exclusive, then change the minimum to 1.
```suggestion
```

2022-11-27 15:09 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      minimum: 0
```suggestion
      minimum: 0.01
```

2022-11-27 15:09 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      exclusiveMinimum: true
This word changes its meaning based on the version of JSON Schema. Let's avoid confusion and bugs when we upgrade by not using it.

2022-11-27 15:10 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategyAmounts.yaml
> +    exclusiveMinimum: true
```suggestion
    minimum: 0.01
```

2022-11-27 15:10 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategyAmounts.yaml
> +      exclusiveMinimum: true
```suggestion
      minimum: 0.01
```

2022-11-27 15:10 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +    exclusiveMinimum: true
```suggestion
    minimum: 0.01
```

2022-11-27 15:10 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +    exclusiveMinimum: true
```suggestion
    minimum: 0.01
```

2022-11-27 15:11 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +      For example, if `minimum` is equal to 5.3, and `multipleOf` is 0.5, the valid custom amount is 5.3, 5.8, 6.3, 6.8 and so on until the `maximum` value is reached.
```suggestion
      For example, if `minimum` is equal to 5.30, and `multipleOf` is 0.50, the valid custom amount is 5.30, 5.80, 6.30, 6.80 and so on until the `maximum` value is reached.
```

2022-11-27 15:11 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierStrategyCustomAmount.yaml
> +    exclusiveMinimum: true
```suggestion
    minimum: 0.01
```

2022-11-27 15:12 UTC, adamaltman commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      minimum: 0
```suggestion
      minimum: 0.01
```

2022-11-27 15:12 UTC, adamaltman requested changes
The word `exclusiveMinimum` changes its meaning based on the version of JSON Schema. Let's avoid confusion and bugs when we upgrade by not using it.

Reference: https://json-schema.org/understanding-json-schema/reference/numeric.html

2022-11-29 13:24 UTC, adamaltman approved these changes, later dismissed

2022-11-29 13:54 UTC, ikram-patah commented on openapi/paths/storefront/cashier-deposit.yaml
> +  x-sdk-operation-name: deposit
```suggestion
  x-sdk-operation-name: create
```

suggestion (non-blocking): 

I haven't seen any operation called `deposit`. I think the convention is to use `create` here.

2022-11-30 02:48 UTC, adamaltman commented on openapi/paths/storefront/cashier-deposit.yaml
> +  x-sdk-operation-name: deposit
Good catch. Maybe we should enforce a discrete amount of possible values in the linter?

2022-11-30 13:28 UTC, adamaltman approved these changes, later dismissed

2022-12-07 02:43 UTC, ikram-patah submitted a review, later dismissed

2022-12-07 07:36 UTC, lexerom submitted a review, later dismissed

2022-12-07 10:21 UTC, noon-dawg commented on openapi/components/requestBodies/storefront/PostCashierDeposit.yaml
> +          description: Cashier Request ID. Created transaction is based on this cashier request properties.
nitpick:
```suggestion
          description: ID of the cashier request. The created transaction is based on the properties of this cashier request.
```

2022-12-07 10:44 UTC, lexerom approved these changes

2022-12-07 10:45 UTC, ikram-patah approved these changes

2022-12-07 11:00 UTC, merged