Quotes
Rebilly/api-definitions pull request #1093
Opened 2022-10-26 13:11 UTC by justnero

## Summary

This is a suggested draft for quotes

## Checklist

- [ ] Writing style
- [ ] API design standards

2022-11-05 10:41 UTC, adamaltman requested changes

2022-11-05 10:41 UTC, adamaltman commented on openapi/components/schemas/Quote/CommonQuote.yaml
> +      - $ref: ../ServerTimestamp.yaml
This type of schema definition ends up being invalid because the `nullable` conflicts with the `allOf`. Using server timestamp is wrong in almost all cases. This isn't really acceptable reuse. Besides being incorrect, it introduces obscurity and doesn't even save lines.
```suggestion
  acceptedTime:
    description: Date and time at which the quote was accepted.
    nullable: true
    readOnly: true
    type: string
    format: date-time
```

2022-11-05 10:41 UTC, adamaltman commented on openapi/components/schemas/Quote/Quote.yaml
> +type: object
This is incorrect. It should be on line 4.

2022-11-05 10:41 UTC, adamaltman commented on openapi/components/schemas/Quote/Quote.yaml
> +  - properties:
```suggestion
  - type: object
    properties:
```

2022-11-05 10:41 UTC, adamaltman commented on openapi/components/schemas/Quote/Quote.yaml
> +          here](https://docs.rebilly.com/docs/dashboard/marketing/coupons-and-discounts/).
This link seems outdated?

2022-11-05 10:41 UTC, adamaltman commented on openapi/openapi.yaml
> +      become an actual order.
```suggestion
      Share pricing with customers before creating an order.
      A quote can contain subscription and one-time sale items.
      When a quote contains one or more subscription items, it is a subscription order quote.

      A quote contains an initial invoice preview and can be accepted to become an actual order.
```
https://sembr.org/

2022-11-05 10:41 UTC, adamaltman commented on openapi/paths/quotes@{id}.yaml
> +  description: |
```suggestion
  description: |-
```

2022-11-05 10:41 UTC, adamaltman commented on openapi/paths/quotes@{id}@issue.yaml
> +  description: |
```suggestion
  description: |-
```

2022-11-05 10:41 UTC, adamaltman commented on openapi/paths/quotes@{id}@reject.yaml
> +  description: |
```suggestion
  description: |-
```

2022-11-05 10:41 UTC, adamaltman commented on openapi/paths/storefront/quotes@{id}.yaml
> +  description: |
```suggestion
  description: |-
```

2022-11-05 10:41 UTC, adamaltman commented on openapi/paths/storefront/quotes@{id}@accept.yaml
> +  description: |
```suggestion
  description: |-
```

2022-11-05 10:41 UTC, adamaltman commented on openapi/paths/storefront/quotes@{id}@reject.yaml
> +  description: |
```suggestion
  description: |-
```

2023-02-22 16:29 UTC, jvc9109 commented on openapi/components/schemas/Quote/CommonQuote.yaml
> +  signature:
Would it be useful to add `cancelledTime` ?

2023-02-22 20:07 UTC, noon-dawg requested changes
I think I started a review on this some time ago but forgot to submit it (review was in pending state).

I've left some comments here based on the [writing style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md) (I think the style may not have been in use when this PR was created)

2023-02-22 20:07 UTC, noon-dawg commented on openapi/components/schemas/Quote/Quote.yaml
> +          might differ.
issue: this description is out of date
```suggestion
          List of coupons to redeem on the customer and restrict to this order.
          
          For more information, see [Coupons](https://www.rebilly.com/docs/settings/coupons-and-discounts/).
          
          This parameter uses the following logic:
          - If this parameter is not supplied, applied coupons are not changed.
          - If an empty array is supplied, all applied coupon redemptions are canceled.
          - If a list of coupons is supplied, unapplied coupons in the list are applied.
          Coupons that have already been applied do not change state.
          Applied coupons that are not supplied in list are canceled.
          
          If the list of applied coupons on a pending order is changed by this parameter during an order update, the invoice for the order is reissued.
```

2023-02-23 09:26 UTC, noon-dawg commented on openapi/openapi.yaml
> +      become an actual order.
suggestion: suggestion to use the same style as the other descriptions in `openapi.yaml`
```suggestion
      Use quote operations to create and manage quotations.
      Quotations describe the cost of goods or services to potential customers before they commit to a purchase.
      A quote contains an initial invoice preview that can be accepted to become an order.
      
      A quote can contain subscription and one-time sale items.
      When a quote contains one or more subscription items, it is a subscription order quote
```

2023-04-19 11:34 UTC, closed without merging