Rework event descriptions
Rebilly/api-definitions pull request #1097
Opened 2022-10-31 15:53 UTC by noon-dawg

## Summary

This pull request reworks event descriptions, and related files, to conform to the [writing style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md).

### [Preview generated docs](https://preview.redoc.ly/openapi-api/events-rework/)

## Links

N/A

## Checklist

- [x] Writing style
- [x] API design standards

2022-10-31 17:09 UTC, vykhrystiuk commented on openapi/components/parameters/rulesVersion.yaml
> +  Version of the ruleset
```suggestion
  Version of the ruleset.
```

2022-10-31 17:10 UTC, vykhrystiuk commented on openapi/components/parameters/rulesVersion.yaml
> +  [Expand to include embedded objects](https://api-reference.rebilly.com/#section/Expand-to-include-embedded-objects).
Should we use a relative link instead?

2022-10-31 17:10 UTC, vykhrystiuk commented on openapi/components/schemas/Events/SystemEvent.yaml
> +      A Binds is a configuration of an event and one or more actions.
```suggestion
      A bind is a configuration of an event and one or more actions.
```

2022-10-31 17:11 UTC, vykhrystiuk commented on openapi/components/schemas/Events/SystemEvent.yaml
> +      A bind is a configuration of an event and one or more actions.
```suggestion
```

2022-10-31 17:12 UTC, vykhrystiuk commented on openapi/components/schemas/Rules/Bind.yaml
> +      Use `;` for multiple fields.
```suggestion
      Filters the collection items.
      This field requires a special format. Use `,` for multiple allowed values.
      Use `;` for multiple fields.
```

2022-10-31 17:16 UTC, vykhrystiuk commented on openapi/components/schemas/Rules/RulesEmailNotification.yaml
> +            It is used by the editor to reproduce the message for future updates.
```suggestion
            Source of the message.
            This value is required for the email editor.
            This value is not used for sending emails.
            It is used by the editor to reproduce the message for future updates.
```

2022-10-31 17:16 UTC, vykhrystiuk commented on openapi/components/schemas/Rules/RulesEmailNotification.yaml
> +                  placeholders are permitted.
```suggestion
                  ID of the attachment resource.
                  Template placeholders are permitted.
```

2022-11-04 14:21 UTC, noon-dawg commented on openapi/components/parameters/rulesVersion.yaml
> +  [Expand to include embedded objects](https://api-reference.rebilly.com/#section/Expand-to-include-embedded-objects).
Good point! Updated in [b1eac32](https://github.com/Rebilly/api-definitions/pull/1097/commits/b1eac32f81fd119a99875e0269cbf6dbf344b989)

2022-11-04 17:38 UTC, vykhrystiuk commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +      The value of this field informational only, it is not assigned to the active ruleset.
```suggestion
      Ruleset version on which the draft ruleset is based.
      Generally, a draft ruleset is cloned from an existing ruleset.
      Use this field to determine how the active ruleset has changed since the draft was created.
      `0` denotes a draft ruleset that was not created from an existing ruleset.
      The value of this field is informational only, it is not assigned to the active ruleset.
```

2022-11-05 10:25 UTC, adamaltman requested changes

2022-11-05 10:25 UTC, adamaltman commented on openapi/components/parameters/rulesVersion.yaml
> +  [Expand to include embedded objects](#section/Expand-to-include-embedded-objects).
https://sembr.org/

2022-11-05 10:25 UTC, adamaltman commented on openapi/components/schemas/Rules/Rule.yaml
> +          Specifies whether the rule stops subsequent rules in the event list from being executed.
```suggestion
        description: Specifies whether the rule stops subsequent rules in the event list from being executed.
```

2022-11-05 14:33 UTC, noon-dawg commented on openapi/components/parameters/rulesVersion.yaml
> +  [Expand to include embedded objects](#section/Expand-to-include-embedded-objects).
Updated in [378cb26](https://github.com/Rebilly/api-definitions/pull/1097/commits/378cb26c4a43af1d9ff64f240abc3e0afce602b4)

2022-11-05 15:16 UTC, adamaltman approved these changes

2022-11-05 21:54 UTC, vykhrystiuk approved these changes

2022-11-06 12:32 UTC, merged