Add Avalara endpoints
Rebilly/api-definitions pull request #1102
Opened 2022-11-03 07:47 UTC by subenson

## Checklist

- [x] Writing style
- [x] API design standards

2022-11-04 14:25 UTC, noon-dawg commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
> +        description: Related resource links.
nitpick: suggestion to help make the description more concise
```suggestion
        description: Related links.
```

2022-11-04 14:25 UTC, noon-dawg commented on openapi/components/schemas/Invoices/TaxTypes/rebilly-avalara.yaml
> +          on the related product's `taxCategoryId`.
issue: [Possessive apostrophes](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#possessive-apostrophes)


```suggestion
          on the related product `taxCategoryId`.
```

2022-11-05 10:20 UTC, adamaltman submitted a review, later dismissed

2022-11-05 10:20 UTC, adamaltman commented on openapi/components/schemas/Invoices/InvoiceTax.yaml
> +    rebilly-avalara: ./TaxTypes/rebilly-avalara.yaml
This file is incorrect. You didn't break it. But, the object that defines the discriminator must use anyOf, oneOf, or allOf and the discriminated property cannot be defined inline.

https://redocly.com/docs/resources/discriminator/

2022-11-09 04:36 UTC, adamaltman commented on openapi/openapi.yaml
> +      transactions in your Avalara account. For more information, see
https://sembr.org/
```suggestion
      The Avalara integration enables you to calculate taxes and create transactions in your Avalara account.
      For more information, see
```

2022-11-09 04:36 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara.yaml
> +  summary: Create a Avalara credential
```suggestion
  summary: Create an Avalara credential
```

2022-11-09 04:36 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara.yaml
> +    Creates a Avalara credential.
```suggestion
    Creates an Avalara credential.
```

2022-11-09 04:37 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara.yaml
> +    Creates a Avalara credential.
```suggestion
  description: Creates an Avalara credential.
```

2022-11-09 04:37 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara@{hash}.yaml
> +  summary: Retrieve a Avalara credential
```suggestion
  summary: Retrieve an Avalara credential
```

2022-11-09 04:37 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara@{hash}.yaml
> +    Retrieves a Avalara credential with a specified token ID.
```suggestion
  description: Retrieves an Avalara credential with a specified token ID.
```

2022-11-09 04:37 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara@{hash}.yaml
> +    Updates a Avalara credential with a specified token ID.
```suggestion
  description: Updates an Avalara credential with a specified token ID.
```

2022-11-09 04:38 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara@{hash}.yaml
> +  summary: Update a Avalara credential
```suggestion
  summary: Update an Avalara credential
```

2022-11-09 08:46 UTC, subenson commented on openapi/components/schemas/Invoices/InvoiceTax.yaml
> +    rebilly-avalara: ./TaxTypes/rebilly-avalara.yaml
I added anyOf and removed the inline definition. Thank you.

2022-11-10 13:36 UTC, adamaltman submitted a review, later dismissed

2022-11-10 13:36 UTC, adamaltman commented on plugins/products-bundler/mapping/Combined.yaml
> +      - Avalara credentials
Not sure about the positioning in this list. Should this list be alphabetized?

2022-11-14 03:42 UTC, subenson commented on plugins/products-bundler/mapping/Combined.yaml
> +      - Avalara credentials
I think that makes more sense.

2022-11-14 03:46 UTC, subenson commented on plugins/products-bundler/mapping/Combined.yaml
> +      - Avalara credentials
Actually the list itself is a little bit meaningless to me. I'm not sure where it's used, but can we extract the credentials and create a new list for it?

2022-11-14 03:49 UTC, subenson commented on plugins/products-bundler/mapping/Combined.yaml
> +      - Avalara credentials
https://github.com/Rebilly/api-definitions/pull/1118/files

2022-11-15 09:23 UTC, subenson commented
@Rebilly/js @Rebilly/php please review

2022-11-15 09:36 UTC, ashkarpetin commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
> +      apiToken:
It seems incorrect? Shouldn't it be licenseKey and accountId?

2022-11-15 13:00 UTC, adamaltman commented on openapi/components/schemas/Invoices/TaxTypes/rebilly-avalara.yaml
> +description: Avalara-based taxes.
This isn't good. It has no type declaration and then pairs with an `allOf`. Remove it.
```suggestion
```

2022-11-15 13:01 UTC, adamaltman commented on openapi/paths/credential-hashes@avalara.yaml
> +    Retrieves a list of Avalara credentials.
```suggestion
  description: Retrieves a list of Avalara credentials.
```
The purpose of the block scalar is multi-line descriptions.

2022-11-16 00:31 UTC, subenson commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
> +      apiToken:
Yes it's incorrect

2022-11-16 00:33 UTC, subenson commented
@php please review

2022-11-25 04:13 UTC, subenson commented on openapi/components/schemas/Invoices/TaxTypes/rebilly-avalara.yaml
> +          on the related product `taxCategoryId`.
```suggestion
        description: Taxes that are applied to this invoice and calculated based on the related product `taxCategoryId`.
```

2022-11-25 04:50 UTC, subenson commented
@Rebilly/php @Rebilly/docs please review

2022-11-25 06:39 UTC, ashkarpetin approved these changes, later dismissed

2022-11-25 09:11 UTC, noon-dawg commented on openapi/openapi.yaml
> +      For more information, see [Avalara integration](https://www.rebilly.com/docs/automations/avalara-integration/#avalara-integration).
issue: we don't have these docs yet

I think we should remove this line for now and add the link when we have them

When we create these docs, I think we should add them to `/docs/app-store/` and not `/docs/automations/` ([see the App Store for an example](https://www.rebilly.com/docs/app-store/app-store/))
```suggestion
```

2022-11-25 09:13 UTC, noon-dawg commented on openapi/components/schemas/Invoices/TaxTypes/rebilly-taxjar.yaml
> +        description: Taxes that are applied to this invoice and calculated based on the related product's `taxCategoryId`.
issue: where possible, avoid [possessive apostrophes](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#possessive-apostrophes)
```suggestion
        description: Taxes that are applied to this invoice and calculated based on the `taxCategoryId` of the related product .
```

2022-11-25 09:16 UTC, noon-dawg commented on openapi/components/schemas/Invoices/TaxTypes/rebilly-avalara.yaml
> +        description: Taxes that are applied to this invoice and calculated based on the related product `taxCategoryId`.
nitpick: for consistency with the description in `/schemas/Invoices/TaxTypes/rebilly-taxjar.yaml`
```suggestion
        description: Taxes that are applied to this invoice and calculated based on the `taxCategoryId` of the related product.
```

2022-11-27 14:50 UTC, adamaltman requested changes, later dismissed
Do not make new folders. I'll adjust the guidance. But making folders for one file hurts.

2022-11-27 14:50 UTC, adamaltman commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
> +allOf:
This folder structure doesn't make sense.

2022-12-01 06:41 UTC, subenson commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
> +allOf:
Shall I move every specific Credential.yaml out of it's subdirectory into `/Credentials/`, while keeping the selected ones in the screenshot below? 

![image](https://user-images.githubusercontent.com/34373534/204983331-c6fa4515-e84e-4167-bf24-d052d70e2ce8.png)

2022-12-09 00:16 UTC, subenson commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
> +allOf:
I just restructured the Avalara Credential as this PR is blocking. On approval, we can apply the changes to the other credentials as well.

2022-12-09 00:19 UTC, subenson commented
@Rebilly/php @Rebilly/docs @Rebilly/js please review

2022-12-09 08:14 UTC, noon-dawg reviewed
Looks good to me!

2022-12-09 18:33 UTC, mikerebilly approved these changes, later dismissed

2022-12-12 07:04 UTC, subenson commented
@Rebilly/php @Rebilly/js please review

2022-12-12 07:20 UTC, lexerom approved these changes

2022-12-12 21:20 UTC, ninjasimon approved these changes

2022-12-12 22:28 UTC, merged

2023-01-06 15:29 UTC, adamaltman commented
FYI this violates the style guide. Tags should be alphabetical. But even more important, there should not be an avalara tag. This is bad organization -- imagine if we made a tag for each gateway integration?