Add VAT to contact object
Rebilly/api-definitions pull request #1119
Opened 2022-11-15 08:48 UTC by VladimirBerdnik

## Summary
This PR will add a VAT property to the `ContactObject` schema

## Checklist

- [ ] Writing style
- [ ] API design standards

2022-11-15 12:55 UTC, adamaltman requested changes, later dismissed

2022-11-15 12:55 UTC, adamaltman commented on openapi/components/schemas/Contact/ContactObject.yaml
> +      at the EU's official [VIES website](https://ec.europa.eu/taxation_customs/vies/#/vat-validation).
https://sembr.org/

2022-11-15 13:28 UTC, ashkarpetin commented
No Writing style and API design standards checks?

2022-11-15 13:40 UTC, adamaltman commented on openapi/components/schemas/Contact/ContactObject.yaml
> +      A value-added tax identification number.
```suggestion
      An EU value-added tax identification number.
```

2022-11-15 13:40 UTC, adamaltman commented on openapi/components/schemas/Contact/ContactObject.yaml
> +      Valid VAT number that passes a check at the EU's official [VIES website](https://ec.europa.eu/taxation_customs/vies/#/vat-validation).
```suggestion
      It must pass the official EU official [VIES validation](https://ec.europa.eu/taxation_customs/vies/#/vat-validation).
```

2022-11-15 15:26 UTC, adamaltman commented on openapi/components/schemas/Contact/ContactObject.yaml
> +      An EU value-added tax identification number.
```suggestion
      EU value-added tax identification number.
```

2022-11-16 09:55 UTC, ashkarpetin approved these changes

2022-11-16 12:55 UTC, adamaltman approved these changes

2022-11-16 13:16 UTC, noon-dawg approved these changes

2022-11-17 08:00 UTC, subenson commented
I propose to change `vat` to `vatNumber`. A contact does not have tax, it has a tax identification number.

2022-12-21 16:54 UTC, closed without merging