Add TaxJar tracking endpoints
Rebilly/api-definitions pull request #1171
Opened 2022-12-01 14:11 UTC by swilczynski

## Summary

## Links

## Checklist

- [ ] Writing style
- [ ] API design standards

2022-12-01 14:24 UTC, dariashka submitted a review, later dismissed

2022-12-01 14:27 UTC, mikerebilly commented on openapi/components/schemas/Tracking/TaxJarTracking.yaml
> +  customerId:
Not sure how important customer id is for analyzing tax logs. We already have the invoice which is the primary entity for this domain. Not sure how others feel though.

2022-12-01 14:34 UTC, noon-dawg reviewed
Excellent use of the writing style!! 

3 very minor comments

2022-12-01 14:34 UTC, noon-dawg commented on openapi/components/schemas/Tracking/TaxJarTracking.yaml
> +    description: Credentials used to send or retrieve data. Can be specified by the merchant or default.
```suggestion
    description: |-
        Credentials used to send or retrieve data. 
        This field can be specified by the merchant or by a default value.
```

2022-12-05 10:09 UTC, swilczynski commented on openapi/components/schemas/Tracking/TaxJarTracking.yaml
> +  customerId:
Log entries for CreditMemo items will not have the invoice attached, maybe it's worth leaving customer id

2022-12-05 12:17 UTC, adamaltman commented on openapi/components/schemas/Tracking/TaxJarTracking.yaml
> +  customerId:
Customer ID can be important.

2022-12-05 12:18 UTC, adamaltman commented on openapi/openapi.yaml
> +    $ref: './paths/tracking@taxjar@{id}.yaml'
I think these should change. Any tax integration log should be retrieved via a unified API.
```suggestion
  /tracking/taxjar:
    $ref: ./paths/tracking@taxes.yaml
  '/tracking/taxjar/{id}':
    $ref: './paths/tracking@taxes@{id}.yaml'
```

2022-12-05 12:18 UTC, adamaltman commented on openapi/paths/tracking@taxjar.yaml
> +  summary: Retrieve TaxJar logs collection
```suggestion
  summary: Retrieve TaxJar logs
```

2022-12-05 12:19 UTC, adamaltman commented on openapi/paths/tracking@taxjar.yaml
> +  summary: Retrieve TaxJar logs collection
But even this should change further to "Retrieve tax logs"

2022-12-07 09:04 UTC, swilczynski commented on openapi/paths/tracking@taxjar.yaml
> +  summary: Retrieve TaxJar logs collection
@adamaltman would `Retrieve tax service logs` look better perhaps?

2022-12-07 09:14 UTC, swilczynski commented
@Rebilly/php please re-review

2022-12-07 09:18 UTC, ashkarpetin commented on openapi/components/schemas/Tracking/TaxTracking.yaml
> +  Results can only be filtered by `id` or `entityId` (the core related-entity ID).
I don't think that it is a correct?

2022-12-07 09:18 UTC, ashkarpetin commented on openapi/components/schemas/Tracking/TaxTracking.yaml
> +  The sort order cannot adjusted.
Same as https://github.com/Rebilly/api-definitions/pull/1171/files#r1041951179?

2022-12-07 12:32 UTC, swilczynski commented on openapi/components/schemas/Tracking/TaxTracking.yaml
> +  Results can only be filtered by `id` or `entityId` (the core related-entity ID).
Fixed

2022-12-07 12:33 UTC, ashkarpetin submitted a review, later dismissed

2022-12-07 13:24 UTC, ashkarpetin commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    description: Name of the tax service used for the transaction.
```suggestion
    description: Name of the tax service used for the transaction.
    enum:
      - taxjar
```

2022-12-14 04:07 UTC, adamaltman commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +      - $ref: ../../ResourceId.yaml
```suggestion
    $ref: ../../ResourceId.yaml
```
You need to use `allOf` if you were to change the description or something like that.

2022-12-14 04:08 UTC, adamaltman commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +  payload:
I wonder if this should be called `requestBody`?

2022-12-14 04:09 UTC, adamaltman commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    description: ID of the invoice sent to tax service.
It could also be a credit memo. Should there be a `creditMemoId` property too?

2022-12-27 16:43 UTC, swilczynski commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    description: ID of the invoice sent to tax service.
I renamed it to more generic `entityId`

2022-12-27 17:12 UTC, ashkarpetin commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    description: ID of the main entity related to the event type.
Description looks incorrect

2022-12-27 17:14 UTC, ashkarpetin commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    description: ID of the customer associated with the transaction.
Which transaction? TaxJar transaction?

2022-12-29 10:00 UTC, swilczynski commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    description: ID of the customer associated with the transaction.
Changed to `ID of the resource associated with the tax service request.`

2022-12-29 10:01 UTC, swilczynski commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    description: ID of the main entity related to the event type.
Changed to `ID of the resource associated with the tax service request.`

2022-12-29 10:12 UTC, ashkarpetin approved these changes, later dismissed

2023-01-03 12:06 UTC, swilczynski commented
@Rebilly/php please re-review

2023-01-03 12:40 UTC, adamaltman requested changes
Ref issue.

2023-01-03 12:40 UTC, adamaltman commented on openapi/components/schemas/Tracking/TaxTracking/TaxJarTracking.yaml
> +    type: array
This line is incorrect. There should be no siblings for a $ref in OAS 3.0.

2023-01-03 13:37 UTC, Boydbueno approved these changes, later dismissed

2023-01-04 14:37 UTC, adamaltman approved these changes, later dismissed

2023-01-14 00:42 UTC, ninjasimon submitted a review, later dismissed

2023-01-16 10:09 UTC, noon-dawg commented on openapi/paths/tracking@taxes.yaml
> +  x-sdk-operation-name: getAllTaxLogs
nitpick: I think we may be missing a description here
```suggestion
  x-sdk-operation-name: getAllTaxLogs
  description: Retrieves tracking tax logs.
```

2023-01-16 10:10 UTC, noon-dawg commented on openapi/paths/tracking@taxes@{id}.yaml
> +  x-sdk-operation-name: getTaxLog
nitpick: we may be missing a description here also 
```suggestion
  x-sdk-operation-name: getTaxLog
  descriptions: Retrieves a tracking tax log with a specified ID.
```

2023-01-22 15:22 UTC, adamaltman commented on openapi/paths/tracking@taxes@{id}.yaml
> +  x-sdk-operation-name: getTaxLog
Should be `description`, not `descriptions` though.

2023-01-23 10:51 UTC, noon-dawg commented on openapi/paths/tracking@taxes@{id}.yaml
> +  x-sdk-operation-name: getTaxLog
Thanks for spotting this 😅 Updated my suggestion to `description`

2023-02-21 12:33 UTC, swilczynski commented
@Rebilly/docs please re-review

2023-02-21 12:34 UTC, swilczynski commented
@Rebilly/php please re-review

2023-03-02 12:04 UTC, noon-dawg approved these changes, later dismissed

2023-03-02 12:28 UTC, noon-dawg approved these changes, later dismissed

2023-03-03 11:20 UTC, swilczynski commented on openapi/components/schemas/Tracking/TaxTracking.yaml
> +  time:
```suggestion
  duration:
```

2023-03-06 14:20 UTC, swilczynski commented
@Rebilly/php please re-review

2023-03-07 10:48 UTC, noon-dawg approved these changes

2023-03-07 10:55 UTC, swilczynski commented
@Rebilly/php please re-review

2023-03-07 11:58 UTC, mikerebilly approved these changes

2023-03-07 13:45 UTC, merged