Add tag/untag API
Rebilly/api-definitions pull request #1185
Opened 2022-12-10 11:44 UTC by XaosSintez

## Checklist

- [ ] Writing style
- [ ] API design standards

2022-12-12 11:44 UTC, noon-dawg reviewed
All minor writing style suggestions

2022-12-12 11:44 UTC, noon-dawg commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    description: Unique rule identifier string.
nitpick: it's better to use 'ID' (based on our writing style)
```suggestion
    description: ID of the rule.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    description: Rule's name.
issue: where possible, avoid [possessive apostrophes](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#possessive-apostrophes)
```suggestion
    description: Name of the rule.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    description: Rebilly event type.
```suggestion
    description: Type of Rebilly event.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    description: List of tag ID customer should be tagged with.
nitpick: suggestion for readability and to remove passive 'should'
```suggestion
    description: List of tag IDs with which the customer must be tagged.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    description: List of tag ID customer should be untagged from.
nitpick: suggestion for readability and to remove passive 'should'
```suggestion
    description: List of tag IDs from which the customer must be untagged.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/paths/tags-configurations.yaml
> +  description: Retrieve a list of tags configuration.
issue: [based on our style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#operations)
```suggestion
  description: Retrieves a list of tags configuration.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/paths/tags-configurations.yaml
> +      description: List of tags configuration retrieved.
nitpick: I think this should be plural
```suggestion
      description: List of tags configurations retrieved.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/paths/tags-configurations.yaml
> +  description: Create tags configuration.
issue: [based on our style](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#operations)
```suggestion
  description: Creates a tags configuration.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/paths/tags-configurations@{id}.yaml
> +  description: Retrieve a tags configuration with specified identifier string.
nitpick: based on our writing style
```suggestion
  description: Retrieve a tags configuration with a specified ID.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/paths/tags-configurations@{id}.yaml
> +  description: Create a tags configuration with specified identifier string.
nitpick: based on our writing style
```suggestion
  description: Creates a tags configuration with a specified ID.
```

2022-12-12 11:44 UTC, noon-dawg commented on openapi/paths/tags-configurations@{id}.yaml
> +  description: Delete tags configuration with specified identifier string.
```suggestion
  description: Delete a tags configuration with a specified ID.
```

2022-12-12 13:01 UTC, dariashka submitted a review, later dismissed

2022-12-12 13:05 UTC, noon-dawg commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +description: Tag / Untag rule.
suggestion: I think we should avoid using `/` slash in descriptions

```suggestion
description: Tag or untag rules.
```
or 

```suggestion
description: Tag or untag a rule.
```

2022-12-13 08:07 UTC, noon-dawg commented
Looks good to me!

2022-12-14 03:53 UTC, adamaltman requested changes

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  addingTags:
```suggestion
  addTags:
```

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    description: List of tag IDs with which the customer must be tagged.
```suggestion
    description: List of tags to add to the customer.
```

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  removingTags:
```suggestion
  removeTags:
```

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    description: List of tag IDs from which the customer must be untagged.
```suggestion
    description: List of tags to remove for the customer.
```

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    $ref: ../OnOff.yaml
You can't have a sibling property to `$ref` in OpenAPI 3.0.

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +        - $ref: ../Links/SelfLink.yaml
Probably better to define it like Dima mentions in the Slack brainstorming channel.

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  eventType:
This one seems like it should be a `$ref`.  Does webhook have this same list? Otherwise, this list is likely to get outdated.

2022-12-14 03:53 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +      Filter that determines whether to send the webhook.
```suggestion
      Filter that determines whether to tag or untag.
```

2022-12-14 03:53 UTC, adamaltman commented on openapi/paths/tags-configurations.yaml
> +  summary: Retrieve tags configuration list
```suggestion
  summary: Retrieve tags configuration list
```
Should it be called tags configurations or tags rules?

2022-12-14 03:53 UTC, adamaltman commented on openapi/paths/tags-configurations.yaml
> +  summary: Retrieve tags configuration list
Same for the path, should it be tags-rules?

2022-12-14 07:14 UTC, XaosSintez commented on openapi/paths/tags-configurations.yaml
> +  summary: Retrieve tags configuration list
Renamed to rule

2022-12-14 07:27 UTC, XaosSintez commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +    $ref: ../OnOff.yaml
Updated, thank you

2022-12-14 07:27 UTC, XaosSintez commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +        - $ref: ../Links/SelfLink.yaml
Updated, thank you

2022-12-21 16:51 UTC, VladimirBerdnik commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +description: Tag or untag a rule.
```suggestion
description: Tag or untag rule.
```
or
```suggestion
description: Modify tags rule.
```

2022-12-21 16:51 UTC, VladimirBerdnik commented on openapi/paths/tags-configurations.yaml
> +  operationId: PostTagRules
```suggestion
  operationId: PostTagsRules
```

2022-12-23 19:56 UTC, adamaltman commented on openapi/paths/tags-configurations.yaml
> +get:
The path hasn't changed yet to `tags-rules.yaml`?

2022-12-23 19:58 UTC, adamaltman commented on openapi/paths/tags-configurations.yaml
> +  summary: Retrieve tags configuration list
I don't see the rename

2022-12-23 19:58 UTC, adamaltman commented on openapi/paths/tags-configurations.yaml
> +  summary: Retrieve tags configuration list
I also meant to rename the path from `tags-configurations` to `tags-rules`.

2022-12-23 19:59 UTC, adamaltman commented on openapi/openapi.yaml
> +  '/tags-configurations':
```suggestion
  '/tags-rules':
```
For example this is what I thought should be renamed..

2022-12-26 07:44 UTC, XaosSintez commented on openapi/paths/tags-configurations.yaml
> +get:
Yes, you are right. Renamed it as well.

2022-12-26 07:45 UTC, XaosSintez commented on openapi/openapi.yaml
> +  '/tags-configurations':
Done, thank you.

2023-01-11 16:04 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  eventType:
Yes, we need to do that. One list please.

2023-01-11 16:05 UTC, adamaltman commented on openapi/paths/tags-rules@{id}.yaml
> +  description: Retrieve a tags rule with a specified ID.
```suggestion
  description: Retrieves a tags rule with a specified ID.
```

2023-01-11 16:05 UTC, adamaltman commented on openapi/paths/tags-rules@{id}.yaml
> +  description: Delete a tags rule with a specified ID.
```suggestion
  description: Deletes a tags rule with a specified ID.
```

2023-01-19 07:25 UTC, XaosSintez commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  eventType:
Renamed `GlobalWebhookEventType` and used it here as well.

2023-01-19 15:34 UTC, XaosSintez commented
@Rebilly/php please review

2023-01-19 15:34 UTC, XaosSintez commented
@Rebilly/js Please review

2023-01-20 07:51 UTC, XaosSintez commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  eventType:
I have a question though. We have some events available to send webhook on where Customer is not related at all. For example, `gateway-account-downtime-started`.
Probably it doesn't make sense to add such events? May be separated list of events still makes sense?

2023-01-20 16:42 UTC, adamaltman submitted a review, later dismissed

2023-01-20 22:12 UTC, vykhrystiuk approved these changes, later dismissed

2023-01-22 15:21 UTC, adamaltman commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  eventType:
Possibly. Maybe a single list makes sense though. Maybe an additional `not` list?

2023-01-23 16:16 UTC, XaosSintez commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  eventType:
@adamaltman I've added "not", but it doesn't seem to work. Validation passes, but these event types are still presented in preview:
![image](https://user-images.githubusercontent.com/1369946/214090951-fc06af49-7d97-4ad2-ae4b-130fba45c25b.png)

I think it doesn't really work for our existing usages of "not: enum:"

2023-01-24 15:53 UTC, XaosSintez commented on openapi/components/schemas/TagUntag/TagUntagRule.yaml
> +  eventType:
Although, most likely the only client here will be Recomm. And it should have correct state - filter by "not" if needed

2023-02-03 18:30 UTC, dariashka approved these changes, later dismissed

2023-02-06 16:49 UTC, XaosSintez commented
@Rebilly/php Please review

2023-02-06 16:49 UTC, XaosSintez commented
@Rebilly/js Please review

2023-02-07 17:53 UTC, XaosSintez commented
@Rebilly/php Please review

2023-02-07 17:53 UTC, XaosSintez commented
@Rebilly/js  Please review

2023-02-09 09:41 UTC, giokaxo approved these changes

2023-02-09 10:05 UTC, VladimirBerdnik approved these changes

2023-02-09 10:09 UTC, merged