Add cashier custom properties
Rebilly/api-definitions pull request #1202
Opened 2022-12-21 10:24 UTC by jvc9109

## Summary
Cashier custom properties definitions proposal.

## Links

## Checklist

- [x] Writing style
- [x] API design standards

2023-01-16 15:52 UTC, noon-dawg commented on openapi/components/schemas/Cashier/CashierCustomPropertySet.yaml
> +      Defines properties the user can complete when they use the hosted cashier app..
nitpick: I think we should avoid referring to cashiers as apps

We have a number of apps within Rebilly, it may confuse users

```suggestion
      Defines properties the user can complete when they use the hosted cashier form.
```

2023-01-16 15:54 UTC, noon-dawg commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      Defines properties the user can complete when they use the hosted cashier app..
nitpick: avoid using `app` unless referring to the Rebilly app
```suggestion
      Defines properties the user can complete when they use the hosted cashier form.
```

2023-01-16 15:55 UTC, noon-dawg commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      Properties that are available for the user to complete when they use the hosted cashier app.
```suggestion
      Properties that are available for the user to complete when they use the hosted cashier form.
```

2023-01-16 15:57 UTC, noon-dawg commented on openapi/paths/cashier-custom-property-sets.yaml
> +    Create a cashier custom property set.
nitpick:
```suggestion
    Creates a cashier custom property set.
```

2023-01-16 15:58 UTC, noon-dawg commented on openapi/components/requestBodies/storefront/PostCashierDeposit.yaml
> +            Properties completed by user in the deposit form.
nitpick: avoid using a block scalar for single line descriptions
```suggestion
          description: Properties completed by user in the deposit form.
```

2023-01-16 16:04 UTC, noon-dawg commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +  description: Retrieves a cashier custom property set with a specified ID.
suggestion: I think it reads better to move 'custom' before 'cashier'
```suggestion
  description: Retrieves a custom cashier property set with a specified ID.
```

2023-01-16 16:06 UTC, noon-dawg commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +    description: Cashier custom property set resource.
suggestion:
```suggestion
    description: Custom cashier property set resource.
```

2023-01-16 16:06 UTC, noon-dawg commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +      description: Cashier custom property updated.
```suggestion
      description: Custom cashier custom property updated.
```

2023-01-16 16:09 UTC, noon-dawg commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +      description: Cashier custom property set created.
```suggestion
      description: Custom cashier property set created.
```

2023-01-16 16:10 UTC, noon-dawg commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +  description: Deletes a cashier custom property set with specified ID.
suggestion:
```suggestion
  description: Deletes a custom cashier property set with specified ID.
```

2023-01-16 16:11 UTC, noon-dawg commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +      description: Cashier custom property set deleted.
```suggestion
      description: Custom cashier property set deleted.
```

2023-01-16 16:12 UTC, noon-dawg commented on openapi/paths/cashier-custom-property-sets.yaml
> +    description: Cashier custom property set resource.
```suggestion
    description: Custom cashier property set resource.
```

2023-01-16 16:12 UTC, noon-dawg commented on openapi/paths/cashier-custom-property-sets.yaml
> +      description: Cashier custom property set created.
```suggestion
      description: Custom cashier property set created.
```

2023-01-16 16:12 UTC, noon-dawg commented on openapi/paths/cashier-custom-property-sets.yaml
> +  summary: Retrieve cashier custom properties sets
```suggestion
  summary: Retrieve custom cashier properties sets
```

2023-01-16 16:13 UTC, noon-dawg commented on openapi/paths/cashier-custom-property-sets.yaml
> +      description: List of cashier custom property set retrieved.
```suggestion
      description: List of custom cashier property sets retrieved.
```

2023-01-16 16:14 UTC, noon-dawg commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      Use this object to describe fields that are rendered and completed during deposit process, in the cashier deposit form.
nitpick: typo
```suggestion
      Use this object to describe fields that are rendered and completed during the deposit process, in the cashier deposit form.
```

2023-01-16 16:15 UTC, noon-dawg commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +      description: Cashier custom property set retrieved.
suggestion
```suggestion
      description: Custom cashier property set retrieved.
```

2023-01-20 04:16 UTC, ikram-patah requested changes
Looks good so far, just a couple of typos i've found

2023-01-20 04:16 UTC, ikram-patah commented on openapi/paths/cashier-custom-proeprty-sets@{id}.yaml
> +parameters:
There's a typo on the filename (`custom-property` instead of `custom-proeprty`)

2023-01-20 04:16 UTC, ikram-patah commented on openapi/openapi.yaml
> +  /caashier-custom-property-sets/{id}:
```suggestion
  /cashier-custom-property-sets/{id}:
```
issue: typo

2023-01-20 06:59 UTC, noon-dawg commented on openapi/components/requestBodies/storefront/PostCashierDeposit.yaml
> +          description: Properties completed by user in the deposit form.
nitpick: typo
```suggestion
          description: Properties completed by the user in the deposit form.
```

2023-01-20 14:48 UTC, jvc9109 commented on openapi/components/schemas/Cashier/CashierCustomPropertySet.yaml
> +      For more information on how to set up the fields look at [documentation](https://www.rebilly.com/docs/settings/cashier-strategies/).
this link will change once docs are ready

2023-01-22 15:18 UTC, adamaltman submitted a review, later dismissed

2023-01-27 03:05 UTC, ikram-patah commented on openapi/paths/cashier-custom-property-sets.yaml
> +  summary: Create a cashier custom property set
```suggestion
  summary: Create a custom cashier property set
```

2023-01-27 03:05 UTC, ikram-patah commented on openapi/components/schemas/Cashier/CashierCustomPropertySet.yaml
> +type: object
Suggestion: Should we also consider having a human-friendly identifier like a `name` for the set?

2023-01-30 05:11 UTC, ikram-patah approved these changes, later dismissed

2023-01-30 06:56 UTC, noon-dawg commented on openapi/components/schemas/Cashier/CashierCustomPropertySet.yaml
> +      For more information on how to set up the fields look at [documentation](https://www.rebilly.com/docs/settings/cashier-strategies/).
nitpick: [serial comma](https://product.rebilly.dev/writing-style-guide/grammar-and-mechanics/commas/#serial-commas) and link format
```suggestion
      Accepted properties types are: `string`, `number`, `integer`, `array`, and `enum`.
      For more information, see [Cashier strategies](https://www.rebilly.com/docs/settings/cashier-strategies/).
```

2023-01-30 07:03 UTC, noon-dawg commented on openapi/components/schemas/Cashier/CashierRequest.yaml
> +      description: ID of a custom property set to be applied for this request `propertiesSchema`.
nitpick: suggestion to avoid [passive voice](https://product.rebilly.dev/writing-style-guide/grammar-and-mechanics/tone-and-voice/voice/#passive-voice)
```suggestion
      description: ID of a custom property set to apply to the request `propertiesSchema`.
```

2023-02-15 20:18 UTC, lexerom approved these changes

2023-02-16 09:14 UTC, ikram-patah approved these changes

2023-02-16 11:56 UTC, merged