Add cashier logo permalink to website _links
Rebilly/api-definitions pull request #1240
Opened 2023-01-19 05:58 UTC by lexerom

## Summary
Add cashier form logo permalink for websites.

## Checklist

- [x] Writing style
- [x] API design standards

2023-01-19 11:34 UTC, ashkarpetin approved these changes

2023-01-19 12:52 UTC, jvc9109 approved these changes

2023-01-22 15:15 UTC, adamaltman requested changes
No more Common___.yaml files please.

I'm writing an article about it.

2023-01-22 15:28 UTC, adamaltman commented on openapi/components/schemas/Storefront/StorefrontWebsite.yaml
> +                - cashierLogoPermalink
This is a bad name. Should be `logo` to keep it simple and clear.

2023-01-22 15:29 UTC, adamaltman commented on openapi/components/schemas/Websites/Website.yaml
> -            - organization
And the reason to not add a `logo` here?

2023-01-22 17:38 UTC, lexerom commented on openapi/components/schemas/Storefront/StorefrontWebsite.yaml
> +                - cashierLogoPermalink
It only logo only for cashier form. Should it still be logo or cashierLogo?

2023-01-22 17:40 UTC, lexerom commented on openapi/components/schemas/Websites/Website.yaml
> -            - organization
I thought it would be used only in storefront cashier form, but I suppose we may use it with general api, so yes, will add it.

2023-01-22 17:58 UTC, adamaltman commented on openapi/components/schemas/Storefront/StorefrontWebsite.yaml
> +                - cashierLogoPermalink
How do you know it is only for the cashier form? Why isn't it the logo of the website? Who designed this?

2023-01-22 18:08 UTC, lexerom commented on openapi/components/schemas/Storefront/StorefrontWebsite.yaml
> +                - cashierLogoPermalink
It is in our rfc and we have api definitions for it - https://github.com/Rebilly/api-definitions/pull/1213/files#diff-592161eb74dfbbca5dce285209f2d47a853b184d3658e4c261e06360589ba165R8

2023-01-23 07:34 UTC, lexerom commented
API definitions will be updated here - https://github.com/Rebilly/api-definitions/pull/1213.

2023-01-23 07:34 UTC, lexerom commented
API definitions will be updated here - https://github.com/Rebilly/api-definitions/pull/1213.

2023-01-23 07:34 UTC, closed without merging