Adjust post payout request
Rebilly/api-definitions pull request #1250
Opened 2023-01-23 20:46 UTC by VladimirBerdnik

## Summary
Fix payout request schema

## Checklist

- [x] Writing style
- [x] API design standards

2023-01-23 20:48 UTC, 2e3s submitted a review, later dismissed

2023-01-23 20:51 UTC, 2e3s approved these changes, later dismissed

2023-01-23 21:21 UTC, mattsanf approved these changes

2023-01-23 21:22 UTC, ashkarpetin approved these changes

2023-01-24 00:00 UTC, ninjasimon approved these changes

2023-01-24 01:57 UTC, adamaltman requested changes

2023-01-24 01:57 UTC, adamaltman commented on openapi/components/schemas/PayoutRequest.yaml
> +    description: ID of the customer who is requesting a payout.
I'm confused where is this schema used?

2023-01-24 02:00 UTC, adamaltman commented on openapi/components/schemas/PayoutRequest.yaml
> +    description: ID of the customer who is requesting a payout.
I found it. It is not used in the storefront.

2023-01-24 02:00 UTC, adamaltman approved these changes

2023-01-24 06:06 UTC, merged