Add GatewayAccount setting to allow $0 authorization
Rebilly/api-definitions pull request #1286
Opened 2023-02-13 17:54 UTC by colinbird

## Summary

## Links

## Checklist

- [ ] Writing style
- [ ] API design standards

2023-02-13 18:05 UTC, colinbird commented on openapi/components/schemas/GatewayAccount.yaml
> +      Allow a zero dollar authorization. This is not supported by all gateways, the default value for an authroization is $1.00.
```suggestion
      Allow a zero dollar authorization. This is not supported by all gateways, the default value for an authorization is $1.00.
```

2023-02-13 18:08 UTC, colinbird commented on openapi/components/schemas/GatewayAccount.yaml
> +      Allow a zero dollar authorization. This is not supported by all gateways, the default value for an authorization is $1.00.
```suggestion
      Allow a zero amount for authorization. This is not supported by all gateways, the default value for an authorization is 1.00 in the transaction's currency.
```

2023-02-13 21:43 UTC, vykhrystiuk commented on openapi/components/schemas/GatewayAccount.yaml
> +      Allow a zero amount for authorization as part of a setup transaction. This is not supported by all gateways, the default value for an authorization is 1.00 in the transaction currency.
```suggestion
      Allow a zero amount for authorization as part of a setup transaction.
      This is not supported by all gateways, the default value for an authorization is 1.00 in the transaction currency.
```

2023-02-14 01:35 UTC, adamaltman requested changes
This seems wrong. It seems like they should send a setup transaction where the gateway is configured to do `authorize` for `$0 USD` for example. This should cause a zero dollar verification.

2023-02-14 01:47 UTC, colinbird commented
Can you explain a bit more what is wrong?  

The currency of the authorize comes from the (parent) setup transaction.

Do you mean that this gateway configuration should not be only for setup transactions but for all authorize transactions?

2023-02-14 12:32 UTC, adamaltman commented
There should not be any user configuration here.

2023-02-15 01:20 UTC, closed without merging