Add quotes
Rebilly/api-definitions pull request #1307
Opened 2023-03-02 15:47 UTC by lexerom

## Summary
Add quotes which can be converted to orders.

## Links
[Old API definitions PR and disucssion](https://github.com/Rebilly/api-definitions/pull/1093)

## Checklist

- [x] Writing style
- [x] API design standards

2023-03-13 08:02 UTC, noon-dawg commented on openapi/components/schemas/Quotes/Quote.yaml
> +      This field can be `null` in `draft` state.
suggestion: suggestion for readability 
```suggestion
      In a `draft` state, this field may be `null`.
```

2023-03-13 08:03 UTC, noon-dawg commented on openapi/components/schemas/Storefront/StorefrontQuote.yaml
> +      This field can be `null` in `draft` state.
suggestion: suggestion for readability 
```suggestion
      In a `draft` state, this field may be `null`.
```

2023-03-13 08:05 UTC, noon-dawg commented on openapi/paths/quotes@{id}@cancel.yaml
> +  description: Cancels a draft, or issued, quote with a specified ID.
suggestion: suggestion for readability (I believe I may have added these comments in an earlier comment, sorry!)
```suggestion
  description: Cancels a draft or issued quote with a specified ID.
```

2023-03-13 08:09 UTC, noon-dawg submitted a review, later dismissed

2023-03-14 10:31 UTC, ikram-patah commented on openapi/components/schemas/Quotes/QuoteInvoicePreview.yaml
> +    format: double
Question:

Since `tax` property is removed in [de962eb](https://github.com/Rebilly/api-definitions/pull/1307/commits/de962ebc3f089fbbfadc72e96f4564b873cec218), do we need to remove `taxAmount` as well? Or are these derived from the quote items?

2023-03-14 12:18 UTC, lexerom commented on openapi/components/schemas/Quotes/QuoteInvoicePreview.yaml
> +    format: double
Yeah, it is supposed to be total calculated tax amount to show in invoice preview. It is based on quote invoice items taxes.

2023-03-15 01:29 UTC, vykhrystiuk commented on openapi/components/schemas/Quotes/Quote.yaml
> +    description: Specifies the type of quote. A quote can be a subscription or a one-time purchase.
Based on the description, it's the type of quote. Should it be just `type`?

2023-03-20 14:07 UTC, jvc9109 commented on openapi/paths/quotes@{id}@issue.yaml
> +      $ref: ../components/responses/Conflict.yaml
```suggestion
    '409':
      $ref: ../components/responses/Conflict.yaml
    '422':
      $ref: ../components/responses/ValidationError.yaml
```

2023-03-23 16:17 UTC, jvc9109 submitted a review, later dismissed

2023-03-23 16:55 UTC, noon-dawg submitted a review, later dismissed

2023-03-24 12:35 UTC, ikram-patah submitted a review, later dismissed

2023-03-28 14:35 UTC, jvc9109 submitted a review, later dismissed

2023-03-28 14:44 UTC, noon-dawg commented on openapi/paths/quotes@{id}.yaml
> +    Update operation can only be used for quotes with a `status` of `draft`.
nitpick:
```suggestion
    The update operation can only be used for quotes with a `status` of `draft`.
```

2023-03-29 01:03 UTC, adamaltman requested changes, later dismissed

2023-03-29 01:03 UTC, adamaltman commented on plugins/products-bundler/mapping/Core.yaml
> +      - Quotes
This placement seems wrong in between Journal and Plans. I'd put it under Coupons.

2023-03-29 09:36 UTC, lexerom commented on openapi/components/schemas/Quotes/Quote.yaml
> +    enum:
Yeah, it will be `draft` status again. We need to add some recall event and a timeline for it. Also I think we may want recall from `canceled` status too.

2023-03-29 09:58 UTC, tamasvigh commented on openapi/components/schemas/Quotes/Quote.yaml
just a quick reminder to add `quoteNumber` property. [Slack thread](https://rebilly.slack.com/archives/C048ZU20J76/p1679312443672999).

2023-03-29 10:19 UTC, ikram-patah commented on openapi/components/schemas/Quotes/Quote.yaml
@tamasvigh just letting you know that the slack thread is only accessible to the project team 🙂

2023-03-29 14:51 UTC, ikram-patah commented on openapi/components/schemas/Quotes/Quote.yaml
Added `quoteNumber` to schema ([1d8b921](https://github.com/Rebilly/api-definitions/pull/1307/commits/1d8b9214ee858c811e93411f692382a80c3931d5))

2023-04-13 08:00 UTC, noon-dawg commented on openapi/paths/quotes@{id}@recall.yaml
> +  description: Recalls an issued quote with a specified ID. After recall the quote status is `draft`.
nitpick: I think we should use `retract` here

`Recall` is ambiguous because it is often used in relation to our memory. For example, "I can still vaguely recall being taken to the hospital".

```suggestion
  summary: Retract a quote
  operationId: PostQuoteRecall
  x-sdk-operation-name: recall
  description: Retract an issued quote with a specified ID. Retracted quotes are assigned the `draft` status.
```

2023-04-13 08:01 UTC, noon-dawg commented on openapi/paths/quotes@{id}@recall.yaml
> +      description: Quote recalled.
nitpick: Related to above comment
```suggestion
      description: Quote retracted.
```

2023-04-13 08:10 UTC, noon-dawg reviewed
This is looking good!
I added very minor comments

2023-04-13 08:10 UTC, noon-dawg commented on openapi/components/schemas/Quotes/Quote.yaml
> +    description: Status of quote.
```suggestion
    description: Status of the quote.
```

2023-04-13 08:10 UTC, noon-dawg commented on openapi/paths/quotes@{id}@timeline@{messageId}.yaml
> +  description: Retrieves a quote message with a specified ID.
nitpick: we should use 'quote timeline message' for all instances
```suggestion
  description: Retrieves a quote timeline message with a specified ID.
```

2023-04-13 08:10 UTC, noon-dawg commented on openapi/paths/quotes@{id}@timeline@{messageId}.yaml
> +      description: Quote message retrieved.
nitpick: we should use 'quote timeline message' for all instances
```suggestion
      description: Quote timeline message retrieved.
```

2023-04-17 13:15 UTC, jvc9109 approved these changes, later dismissed

2023-04-17 13:29 UTC, tamasvigh approved these changes, later dismissed

2023-04-17 13:43 UTC, noon-dawg approved these changes, later dismissed

2023-04-17 16:43 UTC, adamaltman commented on openapi/components/schemas/Quotes/Quote.yaml
> +    minItems: 1
What happens if you have a quote and delete all the items? Is that a possibility?

2023-04-17 16:44 UTC, adamaltman commented on openapi/components/schemas/Quotes/Quote.yaml
> +      List of coupons to redeem on the customer and restrict to this order.
"restrict" or "apply" to this order?

2023-04-17 16:46 UTC, adamaltman commented on openapi/components/schemas/Quotes/QuoteSignature.yaml
> +  organizationPrintedName:
Oh, it should not say "Merchant signature" or "Printed merchant name". The term merchant is a term we use, but unlikely to be a word that our customers would use to describe themselves. 

Also, it should have the title of the person.

Signature

Name

Title

Should also have the Date

2023-04-17 17:34 UTC, lexerom commented on openapi/components/schemas/Quotes/Quote.yaml
> +    minItems: 1
It will not allow to delete all the items.

2023-04-17 18:11 UTC, lexerom commented on openapi/components/schemas/Quotes/Quote.yaml
> +      List of coupons to redeem on the customer and restrict to this order.
Yes, it should be apply. Also, removed most of `couponIds` description as it is not applicable here.

2023-04-19 08:03 UTC, tamasvigh approved these changes

2023-04-19 12:24 UTC, jvc9109 approved these changes

2023-04-19 13:28 UTC, merged