Add customer company enrichment
Rebilly/api-definitions pull request #1312
Opened 2023-03-07 08:28 UTC by justnero

## Summary
Adds a customer company enrichment

## Checklist

- [x] Writing style
- [x] API design standards

2023-03-09 08:12 UTC, ashkarpetin approved these changes, later dismissed

2023-03-09 10:36 UTC, noon-dawg requested changes
We should add descriptions for all properties.

I've made at attempt at adding them here, I'm not sure if they are correct 😅

2023-03-09 10:36 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +  Company information associated with the customer primary email address domain.
nitpick: ( we can use [possessive apostrophes](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#possessive-apostrophes) for people)
```suggestion
  Company information that is associated with the customer's primary email address domain.
```

2023-03-09 10:36 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    type: string
```suggestion
  name:
    type: string
    description: Name of the company.
```

2023-03-09 10:36 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    nullable: true
```suggestion
    type: string
    description: Industry the company is associated with.
    nullable: true
```

2023-03-09 10:36 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    format: integer
```suggestion
    type: number
    description: Number of employees in the company.
    format: integer
```

2023-03-09 10:36 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    nullable: true
```suggestion
    type: string
    description: Country where the company is based.
    nullable: true
```

2023-03-09 10:36 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    format: url
suggestion: I'm not sure if this is correct
```suggestion
    type: string
    description: URL of the company website.
    format: url
```

2023-03-09 10:36 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    type: string
Issue: We need a description for this field. (I'm not sure what domain represents)

2023-03-13 13:02 UTC, justnero commented on openapi/components/schemas/Company.yaml
> +
```suggestion

```

2023-03-13 13:32 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    description: Year the company was founded.
suggestion: fixes the lint issue
```suggestion
    type: number
    description: Founding year of the company.
```

2023-03-13 13:38 UTC, noon-dawg commented on openapi/components/schemas/Company.yaml
> +    type: string
Issue: We need a description for this field. (I'm not sure if my suggestion is correct)
```suggestion
    type: string
    description: Website domain of the company.
```

2023-03-13 13:45 UTC, noon-dawg submitted a review, later dismissed
The descriptions look good to me!

2023-03-13 14:54 UTC, noon-dawg submitted a review, later dismissed

2023-03-13 15:04 UTC, ashkarpetin submitted a review, later dismissed

2023-03-13 18:57 UTC, justnero commented on openapi/components/schemas/Company.yaml
> +    nullable: true
Nice catch, thank you!
```suggestion
```

2023-03-13 19:00 UTC, noon-dawg approved these changes

2023-03-13 20:29 UTC, vykhrystiuk approved these changes

2023-03-14 10:55 UTC, ashkarpetin approved these changes

2023-03-14 11:24 UTC, merged