Edit description
Rebilly/api-definitions pull request #1366
Opened 2023-04-21 11:01 UTC by nanobash

## Summary

## Links

## Checklist

- [ ] Writing style
- [ ] API design standards

2023-04-21 13:53 UTC, noon-dawg approved these changes, later dismissed

2023-04-21 19:52 UTC, nanobash commented
@Rebilly/php please review

2023-04-21 20:31 UTC, ninjasimon commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
I think that this folder structure (folders with only a single file inside) was [specifically recommended against](https://github.com/Rebilly/api-definitions/pull/1102#pullrequestreview-1194997177), which is why the `AvalaraCredential` schema is in its current location.

2023-04-22 08:18 UTC, ashkarpetin requested changes
See https://github.com/Rebilly/api-definitions/pull/1366/files#r1174134151

2023-04-22 08:44 UTC, ashkarpetin commented on openapi/components/requestBodies/PostServiceCredential.yaml
> +        - $ref: ../schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
Better to do the opposite, and remove all nesting from `Credentials`

2023-04-24 14:38 UTC, nanobash commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
Thanks for noting, I did not know, I'll update it.

2023-04-24 14:38 UTC, nanobash commented on openapi/components/schemas/Credentials/AvalaraCredentials/AvalaraCredential.yaml
Thanks for noting, I did not know, I'll update it.

2023-04-25 09:33 UTC, nanobash commented
@Rebilly/php please review

2023-04-25 09:41 UTC, ashkarpetin approved these changes

2023-04-25 09:49 UTC, justnero approved these changes

2023-04-25 09:51 UTC, merged