Add digital wallet payment method #230
Rebilly/api-definitions pull request #137
Opened 2020-07-07 07:17 UTC by VladimirBerdnik

2020-07-07 15:08 UTC, colinbird commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +  billingAddress:
Is this required?

2020-07-07 15:08 UTC, colinbird commented on openapi/components/schemas/PaymentTokens/PaymentInstruments/GooglePay.yaml
> +        description: THe digital wallet type
```suggestion
        description: The digital wallet type
```

2020-07-07 15:09 UTC, colinbird commented on openapi/components/schemas/PaymentTokens/PaymentInstruments/ApplePay.yaml
> +      tokenData:
I came up with this name without much thought.  Perhaps there is a better name.  `payload` ?

2020-07-07 15:34 UTC, VladimirBerdnik commented on openapi/components/schemas/PaymentTokens/PaymentInstruments/ApplePay.yaml
> +      tokenData:
yes, looks so

2020-07-07 15:35 UTC, VladimirBerdnik commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +  billingAddress:
I think so as we create a new payment card, an Apple Pay digital wallet contains address data but it may be missed in the payload

2020-07-07 15:37 UTC, colinbird commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +  billingAddress:
I think we use the billing address that comes in the digital wallet payload (tokenData), if it exists
I don't think we would have something like a Google Pay button AND an address form in FramePay

2020-07-07 17:15 UTC, VladimirBerdnik commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +  billingAddress:
I've removed it, thank you for notes

2020-07-07 17:38 UTC, 2e3s commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +      $ref: ../Links/SelfLink.yaml
The duplication of data between tokens is worrisome

2020-07-08 10:49 UTC, VladimirBerdnik commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +      $ref: ../Links/SelfLink.yaml
@2e3s , I've extracted common part to a separate file here: https://github.com/Rebilly/api-definitions/pull/137/commits/ac7f00b706074f0c03e89ff137b62c58f7b7e0ad

2020-07-08 10:58 UTC, ashkarpetin commented on openapi/components/schemas/PaymentTokens/BankAccountToken.yaml
> +  - $ref: ./AbstractPaymentToken.yaml
I suggest to not introduce new name, and use `Common` folder / CommonToken.yaml

2020-07-08 11:24 UTC, VladimirBerdnik commented on openapi/components/schemas/PaymentTokens/BankAccountToken.yaml
> +  - $ref: ./AbstractPaymentToken.yaml
@ashkarpetin , yes, sounds reasonable, thank you! Will change right now

2020-07-08 12:26 UTC, ashkarpetin submitted a review, later dismissed

2020-07-08 18:13 UTC, colinbird commented on openapi/components/schemas/PaymentTokens/TokenDigitalWalletInstrument.yaml
> +    description: >-
```suggestion
    description:
```

2020-07-08 18:13 UTC, colinbird commented on openapi/components/schemas/PaymentTokens/TokenDigitalWalletInstrument.yaml
> +    description: >-
typo?

2020-07-08 18:36 UTC, colinbird submitted a review, later dismissed

2020-07-08 18:39 UTC, ashkarpetin submitted a review, later dismissed

2020-07-08 20:16 UTC, ptrofimov submitted a review, later dismissed

2020-07-10 12:22 UTC, adamaltman commented on openapi/components/schemas/PaymentTokens/TokenDigitalWalletInstrument.yaml
> +    description: Payment Card expiry month
```suggestion
    description: Payment Card expiration month
```

2020-07-10 12:22 UTC, adamaltman commented on openapi/components/schemas/PaymentTokens/TokenDigitalWalletInstrument.yaml
> +    description: Payment Card expiry year
```suggestion
    description: Payment Card expiration year
```

2020-07-10 12:23 UTC, adamaltman commented on openapi/components/schemas/PaymentTokens/TokenDigitalWalletInstrument.yaml
> +    description: The discriminator for a payment
```suggestion
    description: The descriptor for a payment
```

2020-07-10 12:27 UTC, adamaltman requested changes

2020-07-10 12:27 UTC, adamaltman commented on openapi/components/schemas/PaymentTokens/TokenDigitalWalletInstrument.yaml
> +type: object
This file should be combined into DigitalWalletToken.yaml.

2020-07-11 13:14 UTC, adamaltman approved these changes

2020-07-11 18:35 UTC, ashkarpetin approved these changes

2020-07-11 20:20 UTC, slavcodev commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +  billingAddress:
This is missing in the docs for some reason
![image](https://user-images.githubusercontent.com/757721/87233094-c7202380-c3c4-11ea-8e56-99bd8a45d9f9.png)

2020-07-11 21:56 UTC, adamaltman commented on openapi/components/schemas/PaymentTokens/DigitalWalletToken.yaml
> +  billingAddress:
It's `readOnly: true`

2020-07-17 14:20 UTC, merged