fix `BankAccountCreatePlain` discriminator
Rebilly/api-definitions pull request #1441
Opened 2023-06-08 08:50 UTC by jvc9109

## Summary

## Links

## Checklist

- [ ] Writing style
- [ ] API design standards

2023-06-08 16:14 UTC, ashkarpetin commented on openapi/components/schemas/BankAccounts/AccountNumberTypes/BBANType.yaml
> -allOf:
Hi this is unrelated to threedsecure

2023-06-08 16:18 UTC, jvc9109 commented on openapi/components/schemas/BankAccounts/AccountNumberTypes/BBANType.yaml
> -allOf:
Ops, you are right

2023-06-09 10:21 UTC, ashkarpetin approved these changes, later dismissed

2023-06-09 12:51 UTC, noon-dawg requested changes
Minor nitpicks and suggestions. I think these may have been in the docs already, again I'm taking the opportunity 🙏

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/Clearhaus.yaml
> +            description: Acquiring institution identification code.
suggestion: suggestion for readability

(Series of nouns can be difficult to read)

```suggestion
            description: Identification code of the acquiring institution.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/DataCash.yaml
> +        description: DataCash 3DS servers.
question: should this be singular or plural 
```suggestion
        description: DataCash 3DS server.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/DataCash.yaml
> +            description: Merchant plug-in name.
suggestion: suggestion for readability (series of nouns)
```suggestion
            description: Name of the merchant plug-in.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/Ilixium.yaml
> +            description: Merchant plug-in name.
suggestion: suggestion for readability (series of nouns)
```suggestion
            description: Name of the merchant plug-in.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/Ilixium.yaml
> +        description: Ilixium 3DS servers.
question: should this be singular or plural
```suggestion
        description: Ilixium 3DS server.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/EMerchantPay3dsServers/eMerchantPay3dsServer.yaml
> +    description: Merchant plug-in name.
suggestion: suggestion for readability (series of nouns)
```suggestion
    description: Name of the merchant plug-in.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/EMerchantPay3dsServers/eMerchantPay3dsServers.yaml
>  description: eMerchantPay 3DS servers.
question: should this be singular or plural? 
```suggestion
description: eMerchantPay 3DS server.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/ThreeDSecureIO3dsServer.yaml
> +    description: Merchant name.
suggestion: suggestion for readability
```suggestion
    description: Name of the merchant.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/ThreeDSecureIO3dsServer.yaml
> +    description: JCB acquirer BIN.
suggestion: suggestion for readability (series of nouns)
```suggestion
    description: BIN of the Visa acquirer.
    minLength: 6
    maxLength: 11
  merchantAcquirerBinMastercard:
    type: string
    description: BIN of the Mastercard acquirer.
    minLength: 6
    maxLength: 11
  merchantAcquirerBinAmex:
    type: string
    description: BIN of the American Express acquirer.
    minLength: 6
    maxLength: 11
  merchantAcquirerBinDiscover:
    type: string
    description: BIN of the Discover/Diners acquirer.
    minLength: 6
    maxLength: 11
  merchantAcquirerBinJcb:
    type: string
    description: BIN of the JCB acquirer.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/ThreeDSecureIO3dsServer.yaml
> +    description: Merchant country ISO Alpha-2 code format.
nitpick: typo
```suggestion
    description: Merchant country in ISO Alpha-2 code format.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/ThreeDSecureIO3dsServer.yaml
> +    description: Merchant URL.
suggestion: suggestion to provide more detail
```suggestion
    description: URL of the merchant's website.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/ThreeDSecureIO3dsServer.yaml
> +    description: Use 3DS for merchant initiated transactions.
nitpick: I think this description is missing the `specifies...` part
```suggestion
    description: Specifies whether to use 3DS for merchant initiated transactions.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/Clearhaus.yaml
> +            description: Merchant account ID or Card Acceptor ID provided by the acquiring bank.
nitpick: capitalization 
```suggestion
            description: Merchant account ID or card acceptor ID provided by the acquiring bank.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/ThreeDSecureServers/ThreeDSecureIO3dsServer.yaml
> +    description: JCB acquirer merchant ID (MID).
suggestion: suggestion for readability (series of nouns)
```suggestion
    description: Merchant ID (MID) of the Visa acquirer.
    maxLength: 35
  acquirerMerchantIdMastercard:
    type: string
    description: Merchant ID (MID) of the Mastercard acquirer.
    maxLength: 35
  acquirerMerchantIdAmex:
    type: string
    description: Merchant ID (MID) of the American Express acquirer.
    maxLength: 35
  acquirerMerchantIdDiscover:
    type: string
    description: Merchant ID (MID) of the Discover/Diners acquirer .
    maxLength: 35
  acquirerMerchantIdJcb:
    type: string
    description: Merchant ID (MID) of the JCB acquirer.
```

2023-06-09 12:51 UTC, noon-dawg commented on openapi/components/schemas/GatewayAccountConfig/Clearhaus.yaml
> +            description: API key for 3D Secure server.
nitpick: typo
```suggestion
            description: API key of the 3D Secure server.
```

2023-06-09 13:11 UTC, noon-dawg approved these changes

2023-06-15 08:19 UTC, jvc9109 commented
@Rebilly/js @Rebilly/php  please review

2023-06-15 08:45 UTC, ashkarpetin approved these changes

2023-06-15 08:54 UTC, merged