Add QuickBooks Online external service settings
Rebilly/api-definitions pull request #1469
Opened 2023-07-03 05:52 UTC by justnero

## Summary

A bit redefined the initially proposed schema to make it simpler overall.

## Checklist

- [ ] Writing style
- [ ] API design standards

2023-07-03 09:33 UTC, noon-dawg reviewed
Looks good!

I added some minor nitpicks

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +        description: Specifies how to sync customers.
nitpick: I think it would be good to give more detail
```suggestion
        description: Specifies how to synchronize customer data between your Rebilly and QuickBooks Online account.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +        description: Specifies how to sync invoices.
```suggestion
        description: Specifies how to synchronize invoices.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +        description: Specifies how to sync journal entries.
```suggestion
        description: Specifies how to synchronize journal entries.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create and update customers automatically.
nitpick: Good to give more detail here

(Also, we should avoid [Latin](https://product.rebilly.dev/writing-style-guide/cheat-sheet/#do-not-use) and abbreviations)  

```suggestion
          manually: Customer data is only synchronized when it is manually executed.
          when-used: Customer data is synchronized when related entities, such as transactions or invoices are changes or updated.
          always: Customer data is synchronized automatically as data is created or updated.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create, update and void invoices automatically.
nitpick: Good to give more detail

```suggestion
          manually: Customer data is only synchronized when it is manually executed.
          when-used: Customer data is synchronized when related entities, such as transactions or invoices are changes or updated.
          always: Customer data is synchronized automatically as data is created or updated.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create transactions automatically.
nitpick: Good to give more detail

```suggestion
          manually: Customer data is only synchronized when it is manually executed.
          always: Customer data is synchronized automatically as data is created or updated.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create refund receipts automatically .
nitpick: Good to give more detail

```suggestion
          manually: Customer data is only synchronized when it is manually executed.
          always: Customer data is synchronized automatically as data is created or updated.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create and update journal entries automatically.
nitpick: Good to give more detail

```suggestion
          manually: Customer data is only synchronized when it is manually executed.
          always: Customer data is synchronized automatically as data is created or updated.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +        description: Specifies how to sync invoices.
```suggestion
        description: Specifies how to synchronize invoices.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +        description: Specifies how to sync transactions.
```suggestion
        description: Specifies how to synchronize transactions.
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +        example: jrn_acc_01H32J1KGXSRDH0K8Q7YYA552T
nitpick: Where possible, we should start descriptions like these with 'ID of the...'

Three nouns in a row can make descriptions difficult to read.

```suggestion
        description: ID of the journal account where all products are created.
        example: jrn_acc_01H32J1C97KWGRCKF1E1JY0QG8
      taxesAccountId:
        type: string
        nullable: true
        default: null
        description: ID of the journal account where all taxes are created.
        example: jrn_acc_01H32J1KGXSRDH0K8Q7YYA552T
      department:
        type: string
        nullable: true
        default: null
        description: ID of the QuickBooks Online department that invoices are related to.
        example: jrn_acc_01H32J1KGXSRDH0K8Q7YYA552T
```

2023-07-03 09:33 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +        description: QuickBooks Online department ID payments and refund receipts belong to.
nitpick: Three nouns
```suggestion
        description: ID of the journal account where all payments and refund receipts are deposited.
        example: jrn_acc_01H32J1C97KWGRCKF1E1JY0QG8
      department:
        type: string
        nullable: true
        default: null
        description: ID of the QuickBooks Online department that payments and refund receipts are related to.
```

2023-07-03 13:04 UTC, justnero commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create and update customers automatically.
Fixed a typo here
```suggestion
          manually: Customer data is only synchronized when it is manually executed.
          when-used: Customer data is synchronized when related entities, such as transactions or invoices are created or updated.
          always: Customer data is synchronized automatically as data is created or updated.
```

2023-07-03 13:08 UTC, noon-dawg commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create and update customers automatically.
Thanks for spotting this!

2023-07-03 13:14 UTC, justnero commented on openapi/components/schemas/QuickBooksOnlineExternalServiceSettings.yaml
> +          always: Create, update and void invoices automatically.
This is not accurate related to invoices. It's more like `when-issued`. Adjusted to be that.

```suggestion
          manually: Invoice data is only synchronized when it is manually executed.
          when-issued: Invoice data is synchronized when issued.
          always: Invoice data is synchronized automatically as data it is issued or updated.
```

2023-07-03 16:42 UTC, ashkarpetin commented
PR checklist?

2023-07-03 16:58 UTC, justnero commented
@ashkarpetin checked, was waiting on Chris comments and forgot to check after them.

2023-07-03 17:02 UTC, ashkarpetin commented on openapi/components/schemas/ExternalServiceSettings.yaml
> +    $ref: ./QuickBooksOnlineExternalServiceSettings.yaml
What is the reason to use separate schema for this? It can be described inline.

2023-07-03 17:05 UTC, justnero commented on openapi/components/schemas/ExternalServiceSettings.yaml
> +    $ref: ./QuickBooksOnlineExternalServiceSettings.yaml
It has a nested layer, which makes it harder to read if inline.

2023-07-03 17:18 UTC, ashkarpetin commented on openapi/components/schemas/ExternalServiceSettings.yaml
> +    $ref: ./QuickBooksOnlineExternalServiceSettings.yaml
We agreed to avoid excessive schemas reuse afaik.

2023-07-03 17:29 UTC, justnero commented on openapi/components/schemas/ExternalServiceSettings.yaml
> +    $ref: ./QuickBooksOnlineExternalServiceSettings.yaml
It's not a reuse. Though, it doesn't really make too much of a difference for me.

2023-07-03 17:32 UTC, justnero commented on openapi/components/schemas/ExternalServiceSettings.yaml
> +    $ref: ./QuickBooksOnlineExternalServiceSettings.yaml
Combined

2023-07-03 17:45 UTC, noon-dawg approved these changes

2023-07-03 17:49 UTC, noon-dawg requested changes
The invoice object has some properties that do not have descriptions (I'll try and add them as suggestions)
![Screenshot 2023-07-03 at 19 47 21](https://github.com/Rebilly/api-definitions/assets/85164331/c873844d-2162-45d4-9a16-ace2babeb746)

2023-07-03 17:56 UTC, noon-dawg commented on openapi/components/schemas/ExternalServiceSettings.yaml
> +            type: string
suggestion: suggestions for missing property descriptions 
(I'm not 100% on some of these)
```suggestion
          itemName:
            type: string
            description: Name of the invoice item.
          itemDescription:
            type: string
            description: Description of the invoice item.
          itemSku:
            type: string
            description: Stock Keeping Unit (SKU) item.
          itemLineDescription:
            type: string
            description: Description of the invoice line item.
          taxName:
            type: string
            description: Name of the tax that is applied to the invoice.
          taxDescription:
            type: string
            description: Description of the tax that is applied to the invoice.
          taxSku:
            type: string
            description: Tax that is applied to the Stock Keeping Unit (SKU) item.
          taxLineDescription:
            type: string
            description: Description of the tax line item.
```

2023-07-03 19:21 UTC, justnero commented on openapi/components/schemas/ExternalServiceSettings.yaml
> +            type: string
More like:

```suggestion
          itemName:
            type: string
            description: Name of the invoice item.
          itemDescription:
            type: string
            description: Description of the invoice item.
          itemSku:
            type: string
            description: Stock Keeping Unit (SKU) of the invoice item.
          itemLineDescription:
            type: string
            description: Description of the invoice line item.
          taxName:
            type: string
            description: Name of the tax that is applied to the invoice.
          taxDescription:
            type: string
            description: Description of the tax that is applied to the invoice.
          taxSku:
            type: string
            description: Stock Keeping Unit (SKU) of the tax that is applied to the invoice.
          taxLineDescription:
            type: string
            description: Description of the tax line.
```

2023-07-03 19:27 UTC, noon-dawg approved these changes

2023-07-03 19:49 UTC, ashkarpetin approved these changes

2023-07-04 12:37 UTC, jvc9109 approved these changes

2023-07-10 12:41 UTC, merged