fix: Add missing Storefront transaction properties
Rebilly/api-definitions pull request #1595
Opened 2023-09-14 13:26 UTC by ashkarpetin

## Summary

Add missing Storefront transaction properties
Renamed subscriptionIds to orderIds 

## Links

## Checklist

- [x] Writing style
- [x] API design standards

2023-09-14 13:28 UTC, dara123 approved these changes, later dismissed

2023-09-14 13:33 UTC, mehicalen commented on openapi/components/schemas/StorefrontTransaction.yaml
> +      Detailed Dynamic currency conversion (DCC).
```suggestion
      Detailed dynamic currency conversion (DCC).
```

2023-09-14 13:36 UTC, ashkarpetin commented on openapi/components/schemas/StorefrontTransaction.yaml
> +      Detailed Dynamic currency conversion (DCC).
I copied from Transaction schema

2023-09-14 13:39 UTC, adamaltman requested changes
Not safe

2023-09-14 13:39 UTC, adamaltman commented on openapi/components/schemas/StorefrontTransaction.yaml
> +  dcc:
This is not safe for storefront.

2023-09-14 13:50 UTC, ashkarpetin commented on openapi/components/schemas/StorefrontTransaction.yaml
> +  dcc:
I removed dcc and hasDcc

2023-09-14 13:53 UTC, mehicalen commented on openapi/components/schemas/StorefrontTransaction.yaml
> +      Detailed Dynamic currency conversion (DCC).
Apologies @ashkarpetin , had a chat with @noon-dawg and I think having `Detailed Dynamic Currency Conversion (DCC)` is best.

2023-09-14 13:56 UTC, adamaltman submitted a review, later dismissed

2023-09-14 13:56 UTC, mehicalen submitted a review, later dismissed

2023-09-14 14:01 UTC, noon-dawg submitted a review, later dismissed

2023-09-14 16:14 UTC, ashkarpetin commented on openapi/components/schemas/StorefrontTransaction.yaml
> +      Detailed Dynamic currency conversion (DCC).
I've checked [docs](https://www.rebilly.com/docs/settings/dynamic-currency-conversion/). We use `Dynamic currency conversion`  there.

2023-09-14 16:18 UTC, mehicalen submitted a review, later dismissed

2023-09-14 16:29 UTC, noon-dawg commented on openapi/components/schemas/StorefrontTransaction.yaml
> +      Detailed Dynamic currency conversion (DCC).
You've found an inconsistency there. The DDC topic is old, and needs to be updated. I have some guidance on the use of acronyms in the [writing style guide](https://product.rebilly.dev/writing-style-guide/grammar-and-mechanics/acronyms/), I'll add add this to the API [writing style guidelines](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md).

In Markdown files, use `Dynamic Currency Conversion (DCC)` for the first instance of the acronym on a page and `DCC` thereafter. Since these are API docs, the reader may only browse a few properties, so may be best to use `Detailed Dynamic Currency Conversion (DCC)`. It's good to be consistent on our usage acronyms and related descriptions because the reader they think they are different

2023-09-14 16:44 UTC, mikerebilly submitted a review, later dismissed

2023-09-14 16:54 UTC, ashkarpetin commented on openapi/components/schemas/StorefrontTransaction.yaml
> +      Detailed Dynamic currency conversion (DCC).
Okay, I've rolled back transaction description changes. They are our of scope of the PR.

2023-09-14 22:44 UTC, mehicalen approved these changes

2023-09-15 11:38 UTC, noon-dawg approved these changes

2023-09-15 11:42 UTC, merged