Add quote taxes
Rebilly/api-definitions pull request #1635
Opened 2023-10-11 05:38 UTC by lexerom

## Summary

Add taxes to Quote, rearrange tax files.

## Checklist

- [x] Writing style
- [x] API design standards

2023-10-11 09:30 UTC, noon-dawg submitted a review, later dismissed
Looks good on the docs side

2023-10-11 13:30 UTC, tamasvigh submitted a review, later dismissed

2023-10-13 12:44 UTC, adamaltman commented on openapi/components/schemas/Taxes/TaxTypes/rebilly-taxjar.yaml
> +    description: Total amount of all taxes.
```suggestion
    description: Total amount of taxes.
```

2023-10-13 12:45 UTC, adamaltman requested changes

2023-10-13 12:45 UTC, adamaltman commented on openapi/components/schemas/UpcomingInvoice.yaml
> +      - $ref: ./Taxes/Taxes.yaml
I would use the description from the Taxes.yaml object everywhere throughout and not try to override the description with `allOf`.

2023-10-14 07:34 UTC, lexerom commented on openapi/components/schemas/Taxes/TaxTypes/rebilly-avalara.yaml
>        allOf:
Fixed.

2023-10-16 08:58 UTC, noon-dawg approved these changes, later dismissed

2023-10-16 17:09 UTC, adamaltman requested changes
You need two schemas.

2023-10-16 17:09 UTC, adamaltman commented on openapi/components/schemas/Taxes/CreditMemoTaxItem.yaml
> +        readOnly: false
`allOf` does not override. This is not valid.

2023-10-16 19:25 UTC, adamaltman approved these changes

2023-10-17 06:40 UTC, tamasvigh approved these changes

2023-10-17 07:10 UTC, merged