feat(kyc): clarify liveness session finish operation
Rebilly/api-definitions pull request #1711
Opened 2023-11-30 11:48 UTC by danio1024

## Summary
Clarify the inner workings of KYC liveness session finish endpoint.

## Links

## Checklist

- [x] Writing style
- [x] API design standards

2023-11-30 11:52 UTC, noon-dawg commented on openapi/paths/storefront/kyc-liveness-sessions@{id}@finish.yaml
> +    Session will be finalized only once the KYC liveness session in the third-party service is in a final state.
suggestion: for readability
```suggestion
    The session is finalized when the KYC liveness session in the third-party service is in a final state.
```

2023-11-30 11:54 UTC, noon-dawg commented on openapi/paths/storefront/kyc-liveness-sessions@{id}@finish.yaml
> +    Attempt to finalize a pending KYC liveness session.
nitpick: [Start all operation descriptions with an active verb](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#operations)
```suggestion
    Attempts to finalize a pending KYC liveness session.
```

2023-11-30 12:12 UTC, ashkarpetin commented on openapi/paths/storefront/kyc-liveness-sessions@{id}@finish.yaml
> +    The session can only be finalized when the KYC liveness session, in the third-party service, is in a final state.
```suggestion
    The session can only be finalized when the KYC liveness session in the third-party service, is in a final state.
```
Not sure seems unnecessay comma here

2023-11-30 12:12 UTC, noon-dawg approved these changes, later dismissed
Looks good on the docs side

2023-11-30 12:15 UTC, noon-dawg commented on openapi/paths/storefront/kyc-liveness-sessions@{id}@finish.yaml
> +    The session can only be finalized when the KYC liveness session, in the third-party service, is in a final state.
I thought it might be good to break up the sentence a little. It seems quite long. I don't have strong feelings on it though

2023-11-30 12:19 UTC, mikerebilly commented on openapi/paths/storefront/kyc-liveness-sessions@{id}@finish.yaml
> +    The session can only be finalized when the KYC liveness session, in the third-party service, is in a final state.
I agree with @noon-dawg to be honest. Otherwise it's a little too much of a run-on sentence.

2023-11-30 12:23 UTC, mikerebilly submitted a review, later dismissed
It looks good IMHO

2023-11-30 12:29 UTC, ashkarpetin submitted a review, later dismissed

2023-12-01 05:15 UTC, adamaltman commented on openapi/paths/storefront/kyc-liveness-sessions@{id}@finish.yaml
> +    The session can only be finalized when the KYC liveness session, in the third-party service, is in a final state.
```suggestion
```

I think we should remove it. It sounds too much like the transaction can be marked as completed when the gateway completed processing.

2023-12-01 05:22 UTC, adamaltman requested changes

2023-12-04 19:13 UTC, ashkarpetin approved these changes

2023-12-05 09:25 UTC, noon-dawg approved these changes

2024-07-12 18:05 UTC, closed without merging