Orders API
Rebilly/api-definitions pull request #1734
Opened 2023-12-25 08:38 UTC by nanobash

## Summary

Rename:

- `Orders` => `Subscriptions`
- `Orders timeline` => `Subscriptions timeline`

## Links

## Checklist

- [ ] Writing style
- [ ] API design standards

2023-12-28 09:14 UTC, Weetbix commented on openapi/components/schemas/Order.yaml
> +          description: Type of the order.
```suggestion
          description: Type of the order item.
```

2024-01-02 16:02 UTC, creocoder commented on openapi/components/schemas/Order.yaml
> +          subscription-order: ./OrderSubscription.yaml
```suggestion
          subscription: ./OrderSubscription.yaml
```

2024-01-02 16:02 UTC, creocoder commented on openapi/components/schemas/Order.yaml
> +          one-time-order: ./Purchase.yaml
```suggestion
          purchase: ./Purchase.yaml
```

2024-01-02 16:08 UTC, creocoder commented
Please use https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

2024-01-02 16:11 UTC, vykhrystiuk commented on openapi/components/schemas/OrderSubscription.yaml
> +      - subscription-order
```suggestion
```

Since we have Purchase, we do not need `orderType` for Subscriptions

2024-01-02 16:15 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
Should we add `paymentInstrumentId`?

2024-01-02 16:32 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +  initialInvoiceId:
We should also add `upcomingInvoiceId`

2024-01-04 14:13 UTC, nanobash commented on openapi/components/schemas/Order.yaml
I believe they are already added.

2024-01-04 15:56 UTC, vykhrystiuk commented on openapi/components/schemas/OrderSubscription.yaml
> +      - subscription-order
@nanobash `Order.subscriptions` may contain only subscriptions, we already know the type.

2024-01-04 15:59 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
@nanobash we should remove all excessive fields from `OrderSubscription.yaml` and `Purchase.yaml` that are related to billing and add them to `Order.yaml`

2024-01-04 16:02 UTC, creocoder commented on openapi/components/schemas/Invoice.yaml
> +      - 'null'
```suggestion
```

2024-01-04 16:57 UTC, creocoder commented on openapi/components/schemas/Order.yaml
> +        propertyName: orderType
```suggestion
        propertyName: type
```

2024-01-04 17:45 UTC, vykhrystiuk commented on openapi/components/schemas/OrderSubscription.yaml
> +      - subscription-order
NM you're right, we need discriminator there

2024-01-04 18:51 UTC, nanobash commented on openapi/components/schemas/Order.yaml
As discussed with @creocoder, removed `Purchase.yaml` at all for now. But extracted billing related props to `Order.yaml` as suggested, thanks

2024-01-08 17:35 UTC, vykhrystiuk commented on openapi/components/parameters/orderExpand.yaml
> +    - `upcomingInvoice`
We should also add `paymentInstrument`, `website`

2024-01-08 17:37 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +    properties:
We should add `paymentInstrument`, `website`

2024-01-08 19:51 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +        - $ref: ./Subscription.yaml
Does it mean that it can be Subscription only or can it be OneTimeSale as well?

2024-01-09 10:03 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +        - $ref: ./Subscription.yaml
It means that currently, `Order` supports only `Subscription`, here how it looks like on UI:

<img width="1483" alt="image" src="https://github.com/Rebilly/api-definitions/assets/6716383/ff748872-5965-42d5-848c-d3d9c8624b3f">

2024-01-09 14:47 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +        - $ref: ./Subscription.yaml
I think it should support `Subscription` or `OneTimeSale`. Both should exclude billing-related fields (I can see there are still `initialInvoiceId`, `recentInvoiceId`).

2024-01-09 21:33 UTC, vykhrystiuk commented on openapi/components/schemas/BaseSubscription.yaml
> +      - type: 'null'
This is billing related property, we should move it to the Order level

2024-01-10 10:27 UTC, nanobash commented on openapi/components/schemas/BaseSubscription.yaml
> +      - type: 'null'
Moved to order level, thanks

2024-01-10 11:32 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +        - $ref: ./Subscription.yaml
Moved `initialInvoiceId` and `recentInvoiceId` to `Order` level and added `one-time-sale` type alongside `subscription` to `Order`.

2024-01-16 15:12 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +description: Order details.
We should specify the required fields

2024-01-16 15:13 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
We should also add `revision`

2024-01-16 20:02 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +description: Order details.
Added, thanks

2024-01-22 08:09 UTC, creocoder commented on openapi/components/schemas/Order.yaml
> +      this property enables the customer to subscribe to different plans.
This is legacy property. We need replace it with `invoiceIssueTimeShift` and `invoiceDueTimeShift`.

2024-01-22 09:58 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +      this property enables the customer to subscribe to different plans.
Added invoiceIssueTimeShift and invoiceDueTimeShift properties, thanks

2024-01-22 10:40 UTC, creocoder commented on openapi/components/schemas/Order.yaml
> +      this property enables the customer to subscribe to different plans.
Great, thank you! 👍

2024-01-22 10:42 UTC, creocoder commented on openapi/components/schemas/Order.yaml
> +    description: Invoice issue time shift of the order.
Invoice issue time shift expressed in the ISO 8601 format.

2024-01-23 11:24 UTC, noon-dawg commented on openapi/components/parameters/orderExpand.yaml
> +  For more information, see [Expand to include embedded objects](../../overview/#section/Expand-to-include-embedded-objects).
nitpick: I think we need to use an absolute link here
```suggestion
  For more information, see [Expand to include embedded objects](https://www.rebilly.com/catalog/all/#section/Expand-to-include-embedded-objects).
```

2024-01-23 11:26 UTC, noon-dawg commented on openapi/components/schemas/LegacyOneTimeSale.yaml
> +    description: ID of the initial invoice (`null` for one-time orders).
suggestion: to avoid parenthesis 
```suggestion
    description: |-
      ID of the initial invoice.
      This value is `null` for one-time orders.
```

2024-01-23 11:31 UTC, noon-dawg commented on openapi/components/schemas/LegacyOneTimeSale.yaml
> +      The invoice might not be `paid` yet.
suggestion: for readability
I'm not sure what the second sentence means in relation to the first. I've made a suggestion based on my understanding, which may not be correct
```suggestion
      This value is `null` if no invoice is `paid` yet.
```

2024-01-23 11:33 UTC, noon-dawg commented on openapi/components/schemas/LegacyOneTimeSale.yaml
> +      a [pending order TTL](https://www.rebilly.com/catalog/all/Organizations/PatchOrganization/#!t=request&path=settings/billing/pendingOrderTtl) setting is used to calculate the value.
suggestion: think we should use 'the' instead of 'a'

```suggestion
      the [pending order TTL](https://www.rebilly.com/catalog/all/Organizations/PatchOrganization/#!t=request&path=settings/billing/pendingOrderTtl) setting is used to calculate the value.
```

2024-01-23 11:35 UTC, noon-dawg commented on openapi/components/schemas/LegacyOneTimeSale.yaml
> +        Applied coupons that are not supplied in list are canceled.
nitpick: possible typo
```suggestion
        Applied coupons that are not supplied in the list are canceled.
```

2024-01-23 11:35 UTC, noon-dawg commented on openapi/components/schemas/LegacyOneTimeSale.yaml
> +    description: Purchase order number displayed on the issued invoices.
suggestion: for readability 
```suggestion
    description: Purchase order number that is displayed on the issued invoices.
```

2024-01-23 11:36 UTC, noon-dawg commented on openapi/components/schemas/LegacyOneTimeSale.yaml
> +    description: Notes for the customer displayed on the order invoice.
suggestion: for readability
```suggestion
    description: Notes for the customer that are displayed on the order invoice.
```

2024-01-23 11:39 UTC, noon-dawg commented on openapi/components/schemas/LegacySubscription.yaml
> +    description: Current billing period number.
nitpick: [noun stack](https://github.com/Rebilly/api-definitions/blob/main/WRITING-STYLE.md#noun-strings-or-noun-stacks)
```suggestion
    description: Number of the current billing period.
```

2024-01-23 11:41 UTC, noon-dawg commented on openapi/components/schemas/LegacySubscription.yaml
> +      The invoice might not be `paid` yet.
suggestion: for readability
I'm not sure what the second sentence means in relation to the first. I've made a suggestion based on my understanding, which may not be correct
```suggestion
      This value is `null` if no invoice is `paid` yet.
```

2024-01-23 11:43 UTC, noon-dawg commented on openapi/components/schemas/LegacySubscription.yaml
> +    description: Purchase order number displayed on the issued invoices.
suggestion: for readability
```suggestion
    description: Purchase order number that is displayed on the issued invoices.
```

2024-01-23 11:43 UTC, noon-dawg commented on openapi/components/schemas/LegacySubscription.yaml
> +    description: Notes for the customer displayed on the order invoice.
suggestion: for readability
```suggestion
    description: Notes for the customer that are. displayed on the order invoice.
```

2024-01-23 12:01 UTC, noon-dawg commented on openapi/components/schemas/LegacySubscription.yaml
> +      Shifts issue time and due time of invoices for this subscription.
suggestion: for readability
```suggestion
      Adjusts the issue date and time of renewal invoices for this subscription.
```

2024-01-23 12:05 UTC, noon-dawg commented on openapi/components/schemas/LegacySubscription.yaml
> +      a [pending order TTL](https://www.rebilly.com/catalog/all/Organizations/PatchOrganization/#!t=request&path=settings/billing/pendingOrderTtl) setting is used to calculate the value.
suggestion: for readability
```suggestion
      the [pending order TTL](https://www.rebilly.com/catalog/all/Organizations/PatchOrganization/#!t=request&path=settings/billing/pendingOrderTtl) setting is used to calculate the value.
```

2024-01-23 12:09 UTC, noon-dawg commented on openapi/components/schemas/Order.yaml
> +      Invoice issue time shift interval in ISO-8601 format.
suggestion: to add a definition for invoice time shift
```suggestion
      Invoice issue time shift interval in ISO-8601 format.
      
      Invoice issue time shift adjusts the issue date and time of renewal invoices for this subscription.
```

2024-01-23 12:15 UTC, noon-dawg commented on openapi/components/schemas/Order.yaml
> +      Interval supports only `+` sign.
suggestion: to add more detail

I was confused by the sentence contain the `+` symbol. I've made a suggestion based on my assumption, which may not be correct. Please doublecheck this

```suggestion
      Invoice due time shift interval in ISO-8601 format.
      
      Invoice due time shift adjusts when the payment is due for subscription.
      If autopay is configured, payment is collected automatically on this date.

      This value must be prefixed with the `+` symbol.
```

2024-01-23 12:16 UTC, noon-dawg commented on openapi/components/schemas/Order.yaml
> +    description: Purchase order number displayed on the issued invoices.
suggestion: for readability 
```suggestion
    description: Purchase order number that is displayed on the issued invoices.
```

2024-01-23 12:16 UTC, noon-dawg commented on openapi/components/schemas/Order.yaml
> +    description: Notes for the customer displayed on the order invoice.
suggestion: for readability
```suggestion
    description: Notes for the customer that are displayed on the order invoice.
```

2024-01-23 14:01 UTC, noon-dawg commented on openapi/components/schemas/Order.yaml
> +      Interval supports `-/+` signs.
```suggestion
      The interval value supports both `-` and `+` symbols.
```

2024-01-23 14:47 UTC, noon-dawg submitted a review, later dismissed
Looks good on the docs side

2024-01-30 20:52 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +    type: string
Can it be null?

2024-01-31 07:18 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +    type: string
Good catch, yes, at least [current implementation of status is nullable](https://github.com/Rebilly/rebilly/pull/2974/files#diff-dee34f84ecc8dfd232273f8f38ac1255e1ec8aed8d2d5e3b2f616e33c00f10d0R736), updated, thanks

2024-01-31 08:27 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +    type: string
Or perhaps we should do `return $this->getRecentInvoice() ? $this->getRecentInvoice()->getStatus() : Invoice::STATUS_UNPAID;` just like [here](https://github.com/Rebilly/rebilly/blob/main/backend/core/src/Resource/Order/Entity/OrderItem.php#L660)?

2024-01-31 09:55 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +    type: string
I think it makes more sense to be unpaid by default if there is no recentInvoice, [updated implementation](https://github.com/Rebilly/rebilly/pull/3166/commits/c1b7d2ea078433e3684cd85cabc368bc1a46811a)

2024-02-14 13:19 UTC, adamaltman commented on openapi/components/parameters/orderExpand.yaml
> +  For more information, see [Expand to include embedded objects](https://www.rebilly.com/catalog/all/#section/Expand-to-include-embedded-objects).
Do we need to support expand at all here? It's a new API.

2024-02-14 13:23 UTC, adamaltman commented on openapi/components/schemas/Order.yaml
> +    type: string
```suggestion
    type:
      - string
      - 'null'
```
In creating an order it shows this can be `null`. So this should be defined like that, right?

2024-02-14 13:30 UTC, adamaltman commented on openapi/components/schemas/Order.yaml
> +        - $ref: ./OneTimeSale.yaml
The values here seem wrong.

![image](https://github.com/Rebilly/api-definitions/assets/1161871/0745aa4c-ed71-43be-a959-97076e07a935)

It should be ID of the item, right?

2024-02-14 13:31 UTC, adamaltman commented on openapi/components/schemas/Subscription.yaml
>    id:
This should be ID of the item, right? Not ID of the order.

2024-02-14 13:31 UTC, adamaltman commented on openapi/components/schemas/Subscription.yaml
>        $ref: ./OrderItem.yaml
This is already an item, so how can it have more items?

2024-02-14 17:07 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +        - $ref: ./OneTimeSale.yaml
Yes, it should be OrderItem (Subscription or OneTimeSale) ID.

2024-02-14 17:14 UTC, vykhrystiuk commented on openapi/components/schemas/Subscription.yaml
>      example: ord_01GYJPRKHBD6ZYHH897QCJMBS4
We should consider changing the ID prefix for subscription and one-time sale items. cc: @nanobash

2024-02-14 17:32 UTC, creocoder commented on openapi/components/schemas/Subscription.yaml
>        $ref: ./OrderItem.yaml
Order items: subscriptions and one time sales. The current implementation of subscriptions and one time sales also includes items in it.

At the moment we cannot change this because first we need to convert all clients to the new concept.

What we can do. In the new implementation of orders, we can abandon such concepts as subscription and one time sale items. Within the API, in this way we can transfer the properties of a specific subscription item to the level of the subscription itself and eliminate it property. What do you think about it?

2024-02-14 17:34 UTC, creocoder commented on openapi/components/schemas/Subscription.yaml
>        $ref: ./OrderItem.yaml
An alternative to this is multi-product plans. In this case, this property will be useful.

2024-02-14 17:38 UTC, creocoder commented on openapi/components/schemas/Subscription.yaml
>        $ref: ./OrderItem.yaml
Let me show the current implementation on the diagram (for the transition period):

```
- Order N1
-- Subscription N1
--- Subscription Item N1 ---| we may want drop this legacy concept in future
--- Subscription Item N2 ---| or go multi-product plan way
-- One Time Sale N1
--- One Time Sale Item N1 ---| we may want drop this legacy concept in future
--- One Time Sale Item N2 ---| or go multi-product plan way
```

This implementation on model layer during transition period. On public api level we may eliminate this property right now or accept the concept of multi-product plans. We need decision on this topic.

2024-02-15 09:16 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +    type: string
Yes, it's `nullable`, updated, thank you

2024-02-15 10:54 UTC, nanobash commented on openapi/components/schemas/Subscription.yaml
>      example: ord_01GYJPRKHBD6ZYHH897QCJMBS4
I provided prefix suggestions on a corresponding PR

2024-02-15 11:11 UTC, creocoder commented on openapi/components/schemas/Subscription.yaml
>      example: ord_01GYJPRKHBD6ZYHH897QCJMBS4
We can change prefixes only on stage when we decouple one time sales from subscriptions.

2024-02-15 13:21 UTC, nanobash commented on openapi/components/schemas/Subscription.yaml
>        $ref: ./OrderItem.yaml
Removed `{Subscription|OneTimeSale}.items`

2024-02-15 18:50 UTC, nanobash commented on openapi/components/parameters/orderExpand.yaml
> +  For more information, see [Expand to include embedded objects](https://www.rebilly.com/catalog/all/#section/Expand-to-include-embedded-objects).
Currently, I don't think we need to support it, so can remove it, thanks

2024-02-22 18:54 UTC, vykhrystiuk commented on openapi/components/schemas/Order.yaml
> +  richBillingPortalId:
Should it be renamed?

2024-02-22 19:58 UTC, nanobash commented on openapi/components/schemas/Order.yaml
> +  richBillingPortalId:
Good catch, renamed, thanks

2024-02-26 13:52 UTC, creocoder approved these changes, later dismissed

2024-02-26 14:26 UTC, i-yasko submitted a review, later dismissed

2024-02-26 15:32 UTC, vykhrystiuk approved these changes, later dismissed

2024-02-27 12:22 UTC, ashkarpetin requested changes
This will affect php-sdk generation. Model classes will be generated with `Legacy*` prefix, should be discussed internally.

https://github.com/Rebilly/rebilly-php/blob/851b2d06f2b77543e6931f68218af08c89046174/src/Model/Subscription.php#L20
https://github.com/Rebilly/rebilly-php/blob/851b2d06f2b77543e6931f68218af08c89046174/src/Model/SubscriptionOrOneTimeSale.php#L18

2024-02-28 14:47 UTC, creocoder approved these changes

2024-02-28 14:48 UTC, vykhrystiuk approved these changes

2024-02-28 14:52 UTC, ashkarpetin approved these changes

2024-03-01 11:11 UTC, giokaxo approved these changes

2024-03-08 05:44 UTC, merged