Add StorefrontPostSubscriptionReactivation
Rebilly/api-definitions pull request #1830
Opened 2024-03-15 22:00 UTC by lucasxciv

## Summary

Add `StorefrontPostSubscriptionReactivation`.

## Checklist

- [x] Writing style
- [x] API design standards

2024-03-15 22:18 UTC, adamaltman requested changes

2024-03-15 22:18 UTC, adamaltman commented on openapi/openapi.yaml
> +  '/storefront/subscriptions/{id}/reactivation':
```suggestion
  '/storefront/subscriptions/{id}/reactivations':
```

2024-03-15 22:18 UTC, adamaltman commented on openapi/openapi.yaml
> +    $ref: paths/storefront/subscriptions@{id}@reactivation.yaml
```suggestion
    $ref: paths/storefront/subscriptions@{id}@reactivations.yaml
```

2024-03-15 22:18 UTC, adamaltman commented on openapi/paths/storefront/subscriptions@{id}@reactivation.yaml
It must accept a request body -- what if someone wants to reactivate with a different plan or quantity?

2024-03-15 22:20 UTC, adamaltman commented on openapi/paths/storefront/subscriptions@{id}@reactivation.yaml
> +            $ref: ../../components/schemas/StorefrontQuoteReactivateOrder.yaml
I haven't checked what this schema is yet. To me, it implies that this is incorrectly structured paths -- reactivation shouldn't be a nested subresource.

https://redocly.com/blog/no-subresources/

2024-03-16 15:02 UTC, adamaltman commented on openapi/openapi.yaml
> +  '/storefront/subscriptions/{id}/reactivations':
This is a subresource. Does the reactivation have any ID? Kind of -- it's a quote ID.
```suggestion
  '/storefront/quotes/{id}/':
```

Or `/storefront/reactivations/{id}/`

2024-03-16 15:03 UTC, adamaltman commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +    type: array
```suggestion
  items:
    orderId:
      type: string
      description: ID of the order associated with the reactivation quote.
    type: array
```

2024-03-18 20:07 UTC, adamaltman commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +  subscriptionId:
Are they reactivating a subscription or an order?

2024-03-19 21:59 UTC, lucasxciv commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +  subscriptionId:
It should be subscription (discussed internally).

2024-03-21 14:08 UTC, adamaltman approved these changes

2024-03-26 14:18 UTC, noon-dawg approved these changes

2024-03-26 14:50 UTC, justnero approved these changes

2024-03-26 15:06 UTC, i-yasko approved these changes

2024-03-26 18:36 UTC, creocoder requested changes
It doesn't look correct that the subscription level endpoint requires `orderId`.

2024-03-26 19:42 UTC, creocoder commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +    example: ord_01HRF27SATGE4Z6PBJE6PD8328
```suggestion
  subscriptionId:
    type: string
    description: ID of the subscription associated with the reactivation quote.
    example: ord_01HRF27SATGE4Z6PBJE6PD8328
```

2024-03-27 01:02 UTC, adamaltman commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +    example: ord_01HRF27SATGE4Z6PBJE6PD8328
It's an order level endpoint. The point is to reactivate the order. The word order and subscription have been used interchangeably for a few years which causes a problem with understanding this. The ID expected here is actually an order ID. Unless I'm misunderstanding something. I think the confusion is that prior to your project, 1 subscription ~ 1 order. You couldn't have 1 order with >1 subscription (but you could have >1 item including >1 subscription items).

So this is a real question as to what is getting reactivated? If it is reactivating the subscription only -- then this is the wrong endpoint and functionality. It doesn't meet the business use case. The business use case is related to order reactivation.

2024-03-27 12:37 UTC, creocoder commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +    example: ord_01HRF27SATGE4Z6PBJE6PD8328
> The point is to reactivate the order
If we talk about new orders, this is not an entirely correct statement. An order may include multiple subscriptions. We may want to reactivate one of them, several or all of them.

> So this is a real question as to what is getting reactivated?
The action context for reactivations is subscriptions, not order.

> The business use case is related to order reactivation.
This can be achieved by reactivating all order subscriptions.

2024-03-27 12:42 UTC, creocoder commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +    example: ord_01HRF27SATGE4Z6PBJE6PD8328
Let me explain the difference between `orderId` and `subscriptionId` in that particular case. With `orderId` we we are losing the ability to partially reactivate subscriptions. For example, if an order contains three subscriptions, and we want to reactivate only one of them. By using `subscriptionId` (one value or array) we get the opportunity to reactivate one, several or all order subscriptions.

2024-03-27 12:49 UTC, creocoder commented on openapi/components/requestBodies/storefront/PostSubscriptionReactivation.yaml
> +    example: ord_01HRF27SATGE4Z6PBJE6PD8328
In general, if within the framework of this resource it is advisable to always completely reactivate all order subscriptions, then I think everything is good with `orderId` in that case.

2024-03-27 12:50 UTC, creocoder approved these changes

2024-03-27 13:53 UTC, merged