Update ord prefixes to sub
Rebilly/api-definitions pull request #1864
Opened 2024-04-09 10:54 UTC by nanobash

## Summary

- [x] Update `ord_cnl_` to `sub_cnl_`
- [x] Update `ord_itm_` to `sub_itm_`
- [x] Update `ord_pau_` to `sub_pau_`
- [x] Update `ord_rct_` to `sub_rct_`
- [x] Update `ord_usg_` to `sub_usg_`

## Links

## Checklist

- [ ] Writing style
- [ ] API design standards

2024-04-09 16:11 UTC, jvc9109 submitted a review, later dismissed

2024-04-09 16:14 UTC, justnero approved these changes, later dismissed

2024-04-09 16:32 UTC, adamaltman requested changes
Seems confusing to me.

2024-04-09 16:32 UTC, adamaltman commented on openapi/components/schemas/StorefrontQuoteCreateOrder.yaml
> +    example: sub_01HRF27SATGE4Z6PBJE6PD8328
This should be creating an order, not a subscription. I think the old prefix was correct.

2024-04-09 16:32 UTC, adamaltman commented on openapi/components/schemas/StorefrontQuoteChangeOrder.yaml
> +    example: sub_01HRF27SATGE4Z6PBJE6PD8328
This should be creating an order, not a subscription. I think the old prefix was correct.

2024-04-09 16:32 UTC, adamaltman commented on openapi/components/requestBodies/storefront/PatchOrder.yaml
> +                example: sub_itm_0YV7DENSVGDBW9S71XZNNYYQ0X
This should be related to an order, not a subscription. I think the old prefix was correct.

2024-04-09 16:32 UTC, adamaltman commented on openapi/components/schemas/QuoteChangeOrder.yaml
> +    example: sub_01HRF27SATGE4Z6PBJE6PD8328
This should be related to an order, not a subscription. I think the old prefix was correct.

2024-04-09 16:32 UTC, adamaltman commented on openapi/components/schemas/QuoteTrialConversionOrder.yaml
> +    example: sub_01HRF27SATGE4Z6PBJE6PD8328
This should be related to an order, not a subscription. I think the old prefix was correct.

2024-04-09 16:32 UTC, adamaltman commented on openapi/components/schemas/StorefrontQuoteReactivateOrder.yaml
> +    example: sub_01HRF27SATGE4Z6PBJE6PD8328
This should be related to an order, not a subscription. I think the old prefix was correct.

2024-04-09 16:32 UTC, adamaltman commented on openapi/components/schemas/StorefrontQuoteTrialConversionOrder.yaml
> +    example: sub_01HRF27SATGE4Z6PBJE6PD8328
This should be related to an order, not a subscription. I think the old prefix was correct.

2024-04-09 20:20 UTC, nanobash commented on openapi/components/requestBodies/storefront/PatchOrder.yaml
> +                example: sub_itm_0YV7DENSVGDBW9S71XZNNYYQ0X
The initial prefix `ord_itm` indicates that it is actually a subscription item (plan), that we agreed on to change to `sub_itm`.

cc: @XaosSintez

2024-04-11 13:51 UTC, nanobash commented
@Rebilly/php please review

2024-04-15 11:47 UTC, nanobash commented on openapi/components/requestBodies/storefront/PatchOrder.yaml
> +                example: sub_itm_0YV7DENSVGDBW9S71XZNNYYQ0X
Please re-review @adamaltman

2024-04-15 11:48 UTC, nanobash commented
@Rebilly/php please review

2024-04-16 01:32 UTC, adamaltman commented on openapi/components/requestBodies/storefront/PatchOrder.yaml
> +                example: sub_itm_0YV7DENSVGDBW9S71XZNNYYQ0X
Shouldn't you change the description to say ID of subscription item?

2024-04-16 01:33 UTC, adamaltman commented on openapi/components/schemas/SubscriptionOrOneTimeSaleItem.yaml
> +    example: sub_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX
This can be a subscription or one time sale item.

2024-04-16 07:34 UTC, nanobash commented on openapi/components/requestBodies/storefront/PatchOrder.yaml
> +                example: sub_itm_0YV7DENSVGDBW9S71XZNNYYQ0X
Yes, updated, thanks

2024-04-16 07:51 UTC, nanobash commented on openapi/components/schemas/SubscriptionOrOneTimeSaleItem.yaml
> +    example: sub_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX
True, however currently we don't (did not) have specific prefixes for `subscription` or `one-time-sale` items. Furthermore `subscription/one-time-sale` items going to be restructured and there won't be need for such prefix.

cc: @creocoder

2024-04-17 11:40 UTC, creocoder commented on openapi/components/schemas/SubscriptionOrOneTimeSaleItem.yaml
> +    example: sub_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX
Taking into account that in the future we plan to remove the items of subscriptions and one time sales we can left this identifier as it is for now.

2024-04-18 15:44 UTC, adamaltman commented on openapi/components/schemas/SubscriptionOrOneTimeSaleItem.yaml
> +    example: sub_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX
Do you mean like this @creocoder `ord_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX`?

2024-04-18 15:44 UTC, adamaltman commented on openapi/components/requestBodies/storefront/PatchOrder.yaml
> +                example: sub_itm_0YV7DENSVGDBW9S71XZNNYYQ0X
Line 34 doesn't seem to have changed?

2024-04-18 15:52 UTC, creocoder commented on openapi/components/schemas/SubscriptionOrOneTimeSaleItem.yaml
> +    example: sub_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX
Yes

2024-04-18 15:55 UTC, nanobash commented on openapi/components/requestBodies/storefront/PatchOrder.yaml
> +                example: sub_itm_0YV7DENSVGDBW9S71XZNNYYQ0X
It is changed in this commit: https://github.com/Rebilly/api-definitions/pull/1864/commits/1bedf3338c76d12d845f4b88c491c23950abff0c

2024-04-22 11:13 UTC, nanobash commented on openapi/components/schemas/SubscriptionOrOneTimeSaleItem.yaml
> +    example: sub_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX
Based on internal discussion, updated subscription items to `sub_` prefix, and removed example from ambiguous `SubscriptionOrOneTimeSaleItem.yaml`, where the prefix can belong to subscription item or one-time-sale item.

2024-04-25 15:35 UTC, nanobash commented
@Rebilly/php please review

2024-04-30 12:51 UTC, nanobash commented on openapi/components/schemas/SubscriptionOrOneTimeSaleItem.yaml
> +    example: sub_itm_0YVJ6172Q2CXW9VP7KJMKHCMMX
Please re-review @adamaltman, thank you

2024-05-02 18:36 UTC, adamaltman approved these changes

2024-05-02 19:03 UTC, nanobash commented
@Rebilly/php please review

2024-05-02 20:44 UTC, justnero approved these changes

2024-05-03 07:27 UTC, merged