Add pushInstrumentsUp for adjust-ready-to-pay Rules Engine action
Rebilly/api-definitions pull request #233
Opened 2020-10-08 17:56 UTC by justnero

2020-10-08 18:52 UTC, adamaltman commented on openapi/components/schemas/Rules/Actions/adjust-ready-to-pay.yaml
> +          If set as `true`, the payment methods that a customer has a saved payment instrument for will be displayed at
I think it should be "active" payment instruments.
```suggestion
          If set as `true`, the payment methods that a customer has active payment instruments for will be displayed at
```

2020-10-08 19:23 UTC, 2e3s submitted a review, later dismissed

2020-10-08 19:24 UTC, 2e3s commented
But sometimes merchants need to refine a priority for payment methods more than that.

2020-10-08 19:29 UTC, justnero commented
This will preserve the ordering between the pushed methods. If more fine tuning is required merchant could use manual adjustments using separate rules with conditions

2020-10-10 02:15 UTC, adamaltman commented on openapi/components/schemas/Rules/Actions/adjust-ready-to-pay.yaml
> +          If set as `true`, the payment methods that a customer has active payment instruments for will be displayed at
```suggestion
          If set as `true`, the payment methods associated to the customer's active payment instruments will be displayed at
```

2020-10-10 07:11 UTC, svensono commented on openapi/components/schemas/Rules/Actions/adjust-ready-to-pay.yaml
> +      pushInstrumentsUp:
Maybe it's because I'm not very familiair with it yet, but the key pushInstrumentsUp seems a bit vague. What do you think about something like prioritizeActivePaymentInstrument?

2020-10-10 09:20 UTC, justnero commented on openapi/components/schemas/Rules/Actions/adjust-ready-to-pay.yaml
> +      pushInstrumentsUp:
I don't like the word `prioritize` in this context. Generally we push the weights up preserving their order while prioritize would mean we are reordering active payment instrument methods no matter what weight it was.

2020-10-10 12:20 UTC, adamaltman commented on openapi/components/schemas/Rules/Actions/adjust-ready-to-pay.yaml
> +      pushInstrumentsUp:
Then perhaps the feature is still off? I think `prioritize` is more like what I described in the meeting the other day.

2020-10-10 12:59 UTC, adamaltman commented on openapi/components/schemas/Rules/Actions/adjust-ready-to-pay.yaml
> +      pushInstrumentsUp:
The concept of weights is actually incorrect and inconsistent with how we use weights throughout our app. Weights are used for weighted random selections. We want ordered sequences, not weights.

2020-10-10 13:01 UTC, adamaltman requested changes
I actually think the smarter approach would be to redo the action entirely. The conceptual logic is wrong, and will just come to bite us in the end.

Thinking of it in terms of the simplicity cycle, by leaving all of that weights, allow/deny stuff in there we have:

a) more complexity
b) less goodness

2020-10-10 16:27 UTC, adamaltman commented
This is looking better. What is the (default) behavior if no rule action is set/matched?

2020-10-10 16:28 UTC, justnero commented
In such case no methods are presented in the ready to pay response.

2020-10-10 16:30 UTC, justnero commented
If no actions matched we would expose all methods available assuming Gateway Account filters. To invert this behavior you can place an all-matching rule at the end of the list with an empty `paymentMethods` array.

2020-10-10 16:34 UTC, adamaltman commented
This sounds good to me. This information should be written somewhere in the documentation (not just in comments here).

2020-10-10 16:52 UTC, adamaltman submitted a review, later dismissed

2020-10-10 18:36 UTC, adamaltman approved these changes

2020-10-10 18:37 UTC, adamaltman commented
Please adjust the PR title.

2020-10-12 17:57 UTC, ashkarpetin approved these changes

2020-10-13 04:31 UTC, iamdevice approved these changes

2020-10-15 13:15 UTC, merged