Add Transaction Query API
Rebilly/api-definitions pull request #288
Opened 2020-11-26 20:32 UTC by slavcodev

2020-11-27 11:58 UTC, VladimirBerdnik commented on openapi/paths/transactions@{id}@query.yaml
> +      description: Transaction query was done successfully and parsed.
```suggestion
      description: Transaction query was done successfully and the transaction was reconciled.
```
Do you think such description may be appropriate?

2020-11-27 11:59 UTC, VladimirBerdnik commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      If 'true' the response will be parsed and may update the transaction.
```suggestion
      If 'true' the response will be parsed and may update or reconcile the transaction.
```

2020-12-13 16:32 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      if discrepancies will be found.
The completed transaction should be reconciled regardless -- being reconciled is different from being marked as having a discrepancy.

2020-12-13 16:33 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +  processResponse:
Is there really any case where we do not want to process the response? 

I think we would not process the response in particular cases anyway:

- can't be understood/parsed properly

2020-12-13 16:34 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      - $ref: ../ResourceId.yaml
Can you refresh my memory? Is this `readOnly`?

2020-12-13 16:36 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +  gatewayResponse:
Is this after the query?

2020-12-13 16:37 UTC, adamaltman requested changes
I think we should not have a query API. Instead, I think we should have a reconcile API.

2020-12-13 17:51 UTC, slavcodev commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      if discrepancies will be found.
This requires change or backend or change our language I think. Right now we create an record of "reconciliation" when the reconciliation is created by merchant or by Rebilly if we change status of completed transaction. AFAIK.

If we plan to create new instance of "reconciliation" for every "query" it requires another project, I think.
In this RFC to implement Query API (mainly for for mama API, but can be added on Recomm too) with no great change in backend behavior.

2020-12-13 17:53 UTC, slavcodev commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      if discrepancies will be found.
What do you suggest? Should we postpone this RFC and investigate what to do with reconciliation on query or maybe anything else?

2020-12-13 17:55 UTC, slavcodev commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +  processResponse:
I guess, my text and naming is not clear but I don't know how to improve it. Let me explain, by "processResponse" I mean finalize transaction wiht this query. So the answer for 
> Is there really any case where we do not want to process the response?

is the example when we want to query for preview, like we do now in mama: we query, but finalize only on send request "Update transaction".

2020-12-13 17:55 UTC, slavcodev commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      - $ref: ../ResourceId.yaml
No.

2020-12-13 17:58 UTC, slavcodev commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +  gatewayResponse:
Yes, this is the query response parsed and shows how it affects the transaction if `processResponse` is true.

2020-12-13 18:03 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      - $ref: ../ResourceId.yaml
I find this confusing then. Who will supply this id? And why?

2020-12-13 18:04 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +  processResponse:
It seems it would be better to have a separate operation for Update transaction now. Why support a flag property if we don't need it?

2020-12-13 18:09 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionQuery.yaml
> +      if discrepancies will be found.
I suggest:

1. Renaming: query is unclear and `query-gateway` may be more clear -- we do not want someone to implement this API to query the transaction status.

2. Removing the flag property which updates the transaction.

3. Making the log id `readOnly`.

4. Adding a new update transaction operation which may accept a log id as an input property. As mentioned, there are other reasons people may need to update the transaction result. I think we should allow them to do it as long as it creates an immutable record (marks it as having had a discrepancy and log to the timeline who, what and when).

2020-12-13 18:09 UTC, slavcodev commented
Closing this, it's incorrect.

2020-12-13 18:09 UTC, closed without merging