Add Drafts Rules API
Rebilly/api-definitions pull request #364
Opened 2021-03-08 01:26 UTC by 2e3s

2021-03-08 01:30 UTC, 2e3s commented on openapi/components/schemas/Rules/Bind.yaml
> +      when the rule is created, updated or removed.
This is the main difference from #356 even though it existed there as well. It allows to do all the timeline work in the backend, and the frontend can do its diff work based on this as well. Hence all other APIs from #356 are simply unnecessary.

2021-03-08 01:35 UTC, adamaltman requested changes
Minor change... missing "of" in a few copy/pasted descriptions.

2021-03-08 01:35 UTC, adamaltman commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +    description: All binds are executed regardless other binds, there can't be a final bind.
Regardless "of" other binds (missing of).

2021-03-08 09:04 UTC, slavcodev commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
I think we discussed to not save draft versions. What is purpose of the draft version?

2021-03-08 09:06 UTC, slavcodev commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  - rules
What about name?

2021-03-08 15:17 UTC, 2e3s commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  - rules
If the user doesn't want to specify it then they don't specify IMO

2021-03-08 15:31 UTC, slavcodev commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  - rules
How they will distinguish drafts w/o names?

2021-03-08 16:05 UTC, 2e3s commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
To know that the live ruleset has advanced from the draft ruleset. Since it can be computed from Rules History API (by comparing the live version updatedTime and the draft's created time), it's only a materialized link to the ruleset version which was actual when the draft was created.

2021-03-08 16:27 UTC, 2e3s commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
It could be named something like "lastActiveVersion"

2021-03-08 16:33 UTC, slavcodev commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
Can you please elaaborate, not sure I unerstood your answer. Can you explain on this scenario

1) My active rules set has version 2
2) I clone a draft "A" (is it version 2?)
3) I clone another draft "B" (is it version 2?)
4) I publish "A" as active (it will be version 3?)
5) I publish "B" as active (what version will be it now?)

2021-03-08 16:43 UTC, slavcodev commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
Another story

1) My active rules set has version 2
2) I clone a draft (as far I understand draft will have version 2 too, as active set from which it was cloned)
3) I changed the draft - will it keep `version = 2`? 

How it will be useful? To compare this draft with version 2 from history? Does it make sense? Should not we always ocmpare with active rules set, whatever version it is?

2021-03-08 20:28 UTC, adamaltman submitted a review, later dismissed
I reject this change. I think the version should be clarified a bit, maybe renamed to `clonedVersion`

2021-03-08 20:28 UTC, adamaltman commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
I disagree with @slavcodev as I mentioned. Please re-read the RFC. I think this property could be named better as `clonedVersion` or similar.

2021-03-08 20:29 UTC, adamaltman commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
> Should not we always compare with active rules set, whatever version it is?

Yes, but from which version was it cloned?

2021-03-08 20:45 UTC, 2e3s commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
A draft can be cloned from 
- an older rule set,
- an active rule set
- another draft 
- or a new draft can be created from the scratch

The API is agnostic to that.
I have thought about having a writeable "version" to accomodate all of that. Hence this property will be used only by the frontend with no underlying logic behind.

2021-03-09 08:00 UTC, slavcodev commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  - version
```suggestion
  - clonedVersion
```
?

2021-03-09 09:03 UTC, slavcodev commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
> I think this property could be named better as clonedVersion or similar.

I propose `baseVersion`. Since cloned seems not appropriate, the draft could be posted with different some or all rules, taken another set as base. It does not seem a real "clone".

2021-03-09 18:30 UTC, 2e3s commented on openapi/components/schemas/Rules/RuleSetDraft.yaml
> +  version:
I agree, I wanted to suggest something different from "clone" but I didn't come up with a better term

2021-03-11 20:02 UTC, 2e3s commented
devs please review

2021-03-11 22:58 UTC, 2e3s commented
devs please review

2021-03-11 22:59 UTC, ashkarpetin approved these changes

2021-03-16 15:32 UTC, 2e3s commented
devs please review

2021-03-17 23:17 UTC, 2e3s commented
devs please review

2021-03-18 16:02 UTC, 2e3s commented
devs please review

2021-03-30 14:51 UTC, ghost approved these changes
Looks good. The `RuleSetDraft` has some duplicates from `RuleSet`, e.g. `rules` and `binds` though. We should consider to refactor the definitions in order to DRY.

2021-03-30 15:54 UTC, 2e3s commented
Bind and rules are on a the few same fields and they are already separate in `Bind,yaml`. I've thought that DRY would be overcomplication here.

2021-03-30 15:54 UTC, merged

2021-03-30 16:05 UTC, slavarebilly commented
It's overcomplication to repeat your self and keep documentation consistent for the things that represent the same. IMO.