Add tolerance percentage to Piastrix
Rebilly/api-definitions pull request #368
Opened 2021-03-12 19:04 UTC by dara123

2021-03-12 19:13 UTC, ashkarpetin commented on openapi/components/schemas/GatewayAccountConfig/Piastrix.yaml
> +            maximum: 5
I wonder why it is different compared to Paymero https://github.com/Rebilly/api-definitions/pull/332/

2021-03-12 19:16 UTC, dara123 commented on openapi/components/schemas/GatewayAccountConfig/Piastrix.yaml
> +            maximum: 5
we fixed Paymero. should be max 5

2021-03-12 19:16 UTC, dara123 commented on openapi/components/schemas/GatewayAccountConfig/Piastrix.yaml
> +            maximum: 5
https://github.com/Rebilly/api-definitions/blob/master/openapi/components/schemas/GatewayAccountConfig/Paymero.yaml#L28

2021-03-12 19:22 UTC, ashkarpetin approved these changes

2021-03-12 19:33 UTC, slavcodev reviewed
Please re-use definition https://github.com/Rebilly/api-definitions/blob/6db1f07d41faea89059edd5e1b5825856b8fdb3a/openapi/components/schemas/GatewayAccountConfig/UPayCard.yaml#L33

2021-03-12 19:45 UTC, dara123 commented
I don't think that work yet. I still see bug issue for this open

2021-03-14 13:03 UTC, adamaltman approved these changes

2021-03-14 13:05 UTC, adamaltman requested changes

2021-03-14 13:05 UTC, adamaltman commented on openapi/components/schemas/GatewayAccountConfig/Piastrix.yaml
> +            example: 5
```suggestion
           $ref: ../Gateways/AmountAdjustmentTolerance.yaml
```

2021-03-14 16:18 UTC, dara123 commented on openapi/components/schemas/GatewayAccountConfig/Piastrix.yaml
> +            example: 5
Using ref doesn't work on Gateway account setting now. I open ticket for Recomm to fix this. I will change to ref after they fix that.

2021-03-14 19:06 UTC, ashkarpetin approved these changes

2021-03-14 19:21 UTC, adamaltman approved these changes

2021-03-14 20:03 UTC, merged