Separate List's values from the resource
Rebilly/api-definitions pull request #444
Opened 2021-04-29 20:09 UTC by 2e3s

Lists collection can be very slow as the values can be very big for each list.

2021-04-29 22:25 UTC, ashkarpetin commented on openapi/components/schemas/List.yaml
> +    writeOnly: true
This is a breaking change for API consumers

2021-04-29 22:27 UTC, ashkarpetin commented on openapi/paths/lists@{id}@{version}@values.yaml
> +  x-sdk-operation-name: getByVersion
Seems copy-pasted from `lists@{id}@{version}.yaml`

2021-04-29 22:30 UTC, slavcoclone commented on openapi/paths/lists@{id}@{version}@values.yaml
> +  x-sdk-operation-name: getByVersion
@agualis could we add the check in linter to check uniqueness?

2021-04-29 22:39 UTC, adamaltman commented on openapi/paths/lists@{id}@{version}@values.yaml
> +  x-sdk-operation-name: getByVersion
Yes, look at this for a hint of how to do it:

https://github.com/Redocly/openapi-cli/blob/master/packages/core/src/rules/common/operation-operationId-unique.ts

2021-04-29 22:40 UTC, adamaltman commented on openapi/components/schemas/List.yaml
> +    writeOnly: true
I think this will break at least one client (that we didn't write ourselves).

2021-04-29 22:50 UTC, ashkarpetin commented on openapi/users.yaml
> +    $ref: './paths/lists@{id}@{version}@values.yaml'
It will require 2 requests to retrieve latest version of a list:

1.  `/lists` or `/lists/{id}`
2.  `/lists/{id}/{version}/values`

Retrieving latest version of a list is the most usable API.

2021-04-30 20:00 UTC, 2e3s commented on openapi/components/schemas/List.yaml
> +    writeOnly: true
There should be a BC layer to output this field for older consumers.

2021-05-01 15:34 UTC, adamaltman requested changes
Maybe this needs a discussion on slack or a GitHub issue I can better understand.

2021-05-05 18:41 UTC, 2e3s commented
This is too low priority to continue as nobody is affected right now. The barely used API can live with the flaw.

2021-05-05 18:41 UTC, closed without merging