Gateway account digital wallet
Rebilly/api-definitions pull request #51
Opened 2020-04-29 05:18 UTC by colinbird

2020-04-29 20:29 UTC, dara123 commented on openapi/components/schemas/PaymentCards/DigitalWalletName.yaml
> +  - Google Pay
should we use 1 word?

2020-04-29 22:39 UTC, adamaltman commented on openapi/components/schemas/PaymentCards/DigitalWallets/GooglePay.yaml
> +              description: The Merchant Origin in Google Pay.  The fully qualified domain
```suggestion
        description: Google Pay digital wallet settings.
        type: array
        items:
          type: object
          required:
            - merchantName
            - merchantOrigin
          properties:
            merchantName:
              description: The merchant name in Google Pay.
              type: string
              example: "Test Merchant"
            merchantOrigin:
              description: The Merchant Origin in Google Pay.  The fully qualified domain.

```

2020-05-12 14:54 UTC, colinbird commented on openapi/components/schemas/PaymentCards/DigitalWallets/ApplePay.yaml
> +description: ApplePay Digital Wallet
```suggestion
description: Apple Pay Digital Wallet

```

2020-05-12 17:22 UTC, adamaltman commented on openapi/components/schemas/PaymentCards/DigitalWallets/ApplePay.yaml
> +description: Apple Pay Digital Wallet
```suggestion
description: Apple Pay digital wallet

```

2020-05-12 17:22 UTC, adamaltman commented on openapi/components/schemas/PaymentCards/DigitalWallets/GooglePay.yaml
> +              description: The Merchant Origin in Google Pay.  The fully qualified domain.
```suggestion
              description: The merchant origin in Google Pay.  The fully qualified domain.

```

2020-05-12 17:25 UTC, adamaltman commented on openapi/components/schemas/PaymentCards/DigitalWallets/GooglePay.yaml
> +              description: The Merchant Origin in Google Pay.  The fully qualified domain.
The example you give below doesn't have the protocol?

2020-05-14 04:50 UTC, iamdevice commented on openapi/components/schemas/PaymentCards/DigitalWallets/GooglePay.yaml
> +              description: The Merchant Origin in Google Pay.  The fully qualified domain.
Yes, as I see in Google Pay documentation. They require FQDN without the protocol.

2020-05-15 12:11 UTC, iamdevice commented
php please review

2020-05-15 12:13 UTC, ashkarpetin commented on openapi/components/schemas/PaymentCards/DigitalWallets/ApplePay.yaml
> +
```suggestion
```

2020-05-15 12:14 UTC, ashkarpetin commented on openapi/components/schemas/PaymentCards/DigitalWallets/GooglePay.yaml
> +
```suggestion
```

2020-05-15 12:18 UTC, ashkarpetin submitted a review, later dismissed

2020-05-19 08:58 UTC, subenson submitted a review, later dismissed

2020-05-19 09:00 UTC, slavcodev commented on openapi/components/schemas/GatewayAccount.yaml
> +    maxItems: 1
Did you mean `minItems` ?

2020-05-19 09:04 UTC, slavcodev commented on openapi/components/schemas/PaymentCards/DigitalWallets/GooglePay.yaml
> +            description: The merchant origin in Google Pay.  The fully qualified domain name.
```suggestion
            description: The merchant origin in Google Pay. The fully qualified domain name.

```

2020-05-19 09:42 UTC, iamdevice commented on openapi/components/schemas/GatewayAccount.yaml
> +    maxItems: 1
No, `maxItems` is correct. GatewayAccount can create without any digital wallet.

2020-05-19 10:08 UTC, slavcodev commented on openapi/components/schemas/GatewayAccount.yaml
> +    maxItems: 1
But `maxItems: 1` means only 0 or 1 supported digital wallet. In this case, it makes no sense to have `digitalWallets` as array, it could be just `digitalWallet`.

2020-05-19 10:38 UTC, iamdevice commented on openapi/components/schemas/GatewayAccount.yaml
> +    maxItems: 1
Yes. Now we support only one digital wallet per gateway account. We will add multiple digital wallets support in the next iterations.

2020-05-19 10:40 UTC, slavcodev submitted a review, later dismissed

2020-05-19 15:45 UTC, colinbird commented on openapi/components/schemas/PaymentCards/DigitalWallets/GooglePay.yaml
> +
```suggestion

```

2020-05-20 10:48 UTC, adamaltman requested changes
This API doesn't seem to make sense.

2020-05-20 10:48 UTC, adamaltman commented on openapi/components/schemas/GatewayAccount.yaml
> +    type: array
I don't think it makes sense for this to be an array. It makes sense when there are multiple items... in this case, you're really just supplying an object.

2020-05-20 10:48 UTC, adamaltman commented on openapi/components/schemas/GatewayAccount.yaml
> +    maxItems: 1
This doesn't make any sense to me.

2020-05-20 11:15 UTC, iamdevice commented on openapi/components/schemas/GatewayAccount.yaml
> +    type: array
I think we shouldn't change API when we add multiple digital wallets support per gateway account. We just remove the limit and it won't require any other API changes. One gateway could work with Apple Pay and Google Pay together.

2020-05-20 11:46 UTC, adamaltman commented on openapi/components/schemas/GatewayAccount.yaml
> +    type: array
Look how complex this pull request and API description is versus:

https://github.com/Rebilly/api-definitions/pull/51

2020-05-20 13:34 UTC, closed without merging