Add Storefront API
Rebilly/api-definitions pull request #57
Opened 2020-05-04 16:47 UTC by justnero

2020-05-04 17:05 UTC, adamaltman requested changes

2020-05-04 17:05 UTC, adamaltman commented on openapi/components/schemas/Storefront/Method.yaml
> +type: string
This is just incorrect. We do not want to duplicate schemas.

2020-05-05 11:31 UTC, justnero commented on openapi/components/schemas/Storefront/Method.yaml
> +type: string
@adamaltman I've removed all duplicates from Storefront schemas

2020-05-05 13:31 UTC, adamaltman commented on openapi/components/requestBodies/storefront/PostPaymentInstrument.yaml
> +          description: Payment Instrument Token ID.
Descriptions should be written using sentence casing, like I did in this comment.

2020-05-05 13:32 UTC, adamaltman commented on openapi/components/schemas/Storefront/CustomerJWT.yaml
> +    description: Session expired time. Defaults to one hour
When you use sentences and punctuation, then you must use punctuation.
```suggestion
    description: Session expired time. Defaults to one hour.
```

2020-05-05 13:33 UTC, adamaltman commented on openapi/components/schemas/Storefront/Invoice.yaml
> +    description: The Invoice's shipping amount
Invoice is not a proper name. The problem exists everywhere in this PR.
```suggestion
    description: The invoice's shipping amount
```

2020-05-05 14:01 UTC, adamaltman requested changes
More questions

2020-05-05 14:01 UTC, adamaltman commented on openapi/components/schemas/Storefront/Method.yaml
> +type: string
I still see a lot of things that look like duplicates.

2020-05-05 14:29 UTC, justnero commented on openapi/components/schemas/Storefront/Invoice.yaml
> +type: object
It hides `retryInstruction`, `revision` and `dueReminder` settings as well as `customerId` because it Storefront is customer specific.

2020-05-05 14:33 UTC, justnero commented on openapi/components/schemas/Storefront/PaymentInstructions/PaymentInstrument.yaml
> +type: object
This one is just a payment instrument reference ID, separate schema used for clean `oneOf`

2020-05-05 14:34 UTC, justnero commented on openapi/components/schemas/Storefront/PaymentInstructions/PaymentMethod.yaml
> +type: object
These methods should be passed as a valid `paymentInstrumentId` using schema `components/schemas/Storefront/PaymentInstructions/PaymentInstrument`

2020-05-05 14:39 UTC, justnero commented on openapi/components/schemas/Storefront/PaymentInstruments/BankAccount.yaml
> +type: object
Hides `customerId`

2020-05-05 14:39 UTC, justnero commented on openapi/components/schemas/Storefront/PaymentInstruments/PayPalAccount.yaml
> +title: 'PayPal Account'
Hides `customerId`

2020-05-05 14:40 UTC, justnero commented on openapi/components/schemas/Storefront/PaymentInstruments/PaymentCard.yaml
> +type: object
Hides `customerId`, `stickyGatewayAccountId` and `expirationReminder` settings

2020-05-05 14:41 UTC, justnero commented on openapi/components/schemas/Storefront/Plan.yaml
> +type: object
Hides `invoiceTimeShift` and `subscriptionCount`

2020-05-05 14:42 UTC, justnero commented on openapi/components/schemas/Storefront/Product.yaml
> +type: object
Hides `taxCategoryId` and `accountingCode`

2020-05-05 14:45 UTC, justnero commented on openapi/components/schemas/Storefront/Transaction.yaml
> +type: object
Hides `gatewayAccountId`, `gatewayTransactionId`, `gateway`, `gatewayName`, `acquirerName`, `customerId`, `velocity`, `revision`, `referenceData`, `riskScore`, `riskMetadata`, `notificationUrl`, `retryInstruction`

2020-05-05 14:46 UTC, justnero commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  dcc:
It was inside original schema, If this is private for merchant and should not be shown to customer we can remove it.

2020-05-05 14:46 UTC, justnero commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  hasBumpOffer:
It was inside original schema, If this is private for merchant and should not be shown to customer we can remove it.

2020-05-05 17:40 UTC, adamaltman commented on openapi/components/schemas/Storefront/PaymentInstruments/BankAccount.yaml
> +type: object
Is there some reason for it to be hidden?

2020-05-05 17:41 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +type: object
It seems like a lot more stuff should be removed. But I don't understand the need to remove customerId. After all, it will make it much more clear for anyone looking at API logs too.

2020-05-05 17:44 UTC, justnero commented on openapi/components/schemas/Storefront/Transaction.yaml
> +type: object
We don't operate with `customerId` in terms of Storefront API. I think there is no reason to show any ID that can't be checked or used by customer.

2020-05-05 17:44 UTC, adamaltman commented on openapi/components/schemas/Storefront/PaymentInstructions/PaymentMethod.yaml
> +type: object
This seems incorrect though. I thought the idea was that someone could pass a payment instruction that says use a `payment-card` but the customer doesn't have any payment card on file yet...

2020-05-05 17:45 UTC, adamaltman commented on openapi/components/schemas/Storefront/Invoice.yaml
> +type: object
I think it makes strong sense to include `customerId`.

2020-05-05 17:47 UTC, justnero commented on openapi/components/schemas/Storefront/PaymentInstructions/PaymentMethod.yaml
> +type: object
You are mixing APIs, that part is in https://github.com/Rebilly/api-definitions/pull/32

2020-05-05 17:58 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +    description: The transactions's purchase amount
```suggestion
    description: The amount actually purchased which may have differed from the originally requested amount in case of an adjustment.
```

2020-05-05 17:59 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +    description: The transactions's amount received in the payment request
```suggestion
    description: The amount in the payment request. If adjusted, the purchase amount and billing amount may vary from it.
```

2020-05-05 18:01 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +    description: The transactions's parent ID
```suggestion
    description: The parent's transaction ID
```

2020-05-05 18:02 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  orderIds:
This is going to lead to a confusing conflict. This is linked to the `subscriptionIds`?

2020-05-05 18:03 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  retriesResult:
I believe this should be removed.

2020-05-05 18:03 UTC, justnero commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  orderIds:
Yes, I can change that to `subscriptionIds` to be on the same page as our core API, but wanted to deprecate that name right from the start

2020-05-05 18:03 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  retriedTransactionId:
I believe this should be removed.

2020-05-05 18:04 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +    readOnly: true
This should be removed.

2020-05-05 18:04 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +    description: The transactions's request ID.  This ID must be unique within a 24 hour period.
```suggestion
    description: The transaction's request ID.  This ID must be unique within a 24 hour period.
```

2020-05-05 18:04 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  scheduledTime:
This should be removed.

2020-05-05 18:05 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  bumpOffer:
Remove this section.

2020-05-05 18:05 UTC, adamaltman commented on openapi/components/schemas/Storefront/Transaction.yaml
> +  dcc:
Remove this section.

2020-05-05 18:26 UTC, adamaltman commented on openapi/components/schemas/Storefront/PaymentInstruments/PayPalAccount.yaml
> +title: 'PayPal Account'
Same thing. I don't think there is a reason to hide customerId.

2020-05-05 18:26 UTC, adamaltman commented on openapi/components/schemas/Storefront/PaymentInstruments/PaymentCard.yaml
> +type: object
I don't think there is a reason to hide `customerId` (readOnly).

2020-05-05 18:27 UTC, adamaltman commented on openapi/components/schemas/Storefront/Plan.yaml
> +type: object
I don't see a reason to do that.

2020-05-05 18:41 UTC, justnero commented on openapi/components/schemas/Storefront/Plan.yaml
> +type: object
Can we show `subscriptionCount` to a single customer? Won't it disclose internal business state of a merchant?

2020-05-05 18:48 UTC, adamaltman commented on openapi/components/schemas/Storefront/Plan.yaml
> +type: object
Sorry, I thought this was customer->subscriptionCount.

2020-05-06 19:30 UTC, justnero commented
php please review

2020-05-07 14:04 UTC, justnero commented
php please review

2020-05-08 20:15 UTC, adamaltman approved these changes

2020-05-08 20:58 UTC, ashkarpetin approved these changes

2020-05-09 11:42 UTC, merged