Add 3DS setting for AsiaPaymentGateway
Rebilly/api-definitions pull request #608
Opened 2021-09-27 22:21 UTC by ninjasimon

Adds a setting to enable 3DS authentication for AsiaPaymentGateway.

2021-09-27 22:23 UTC, ashkarpetin commented on openapi/components/schemas/GatewayAccountConfig/AsiaPaymentGateway.yaml
> +          use3DS:
Why you are not using `threeDSecureServer` setting?

https://github.com/Rebilly/api-definitions/blob/ecafddadf911993e55725a9d829ee2def2bd494e/openapi/components/schemas/GatewayAccountConfig/Piastrix.yaml#L32-L33

2021-09-27 22:25 UTC, ashkarpetin requested changes
~I believe it's not correct, we have a special object that instructs gateway to use 3ds or not~

It's a flag that instructs adapter to send request to a different endpoint.

2021-09-27 23:16 UTC, ashkarpetin approved these changes

2021-09-28 06:58 UTC, vykhrystiuk approved these changes

2021-09-28 07:08 UTC, XaosSintez approved these changes

2021-09-29 19:46 UTC, merged