Add supported setup instructions to gateway metadata
Rebilly/api-definitions pull request #611
Opened 2021-09-30 14:32 UTC by Boydbueno

2021-09-30 23:11 UTC, 2e3s approved these changes, later dismissed

2021-09-30 23:16 UTC, 2e3s commented on openapi/components/schemas/Metadata/PaymentGatewayMetadata.yaml
> +  supportedSetupInstructions:
I think this overlaps with `setupInstructions` though,

2021-10-04 12:57 UTC, Boydbueno commented on openapi/components/schemas/Metadata/PaymentGatewayMetadata.yaml
> +  supportedSetupInstructions:
Renamed it to `supportedPaymentMethodSetupInstructions`

2021-10-07 01:46 UTC, adamaltman requested changes, later dismissed
Please use https://github.com/Rebilly/api-definitions/pull/590

Also, notice how the definition is used in it with `x-enumDescriptions`.

2021-10-14 21:43 UTC, 2e3s commented on openapi/components/schemas/Metadata/PaymentGatewayMetadata.yaml
> +          If the gateway account is configured for strong customer authentication, it will be used.
This looks excessive, as `sca` is just a different choice from these.
```suggestion
        authorize-and-void: |
          Creates an `authorize` transaction in the amount/currency of the request, followed by a `void` (if the `authorize` was approved).
```

2021-10-15 19:52 UTC, 2e3s commented on openapi/components/schemas/Metadata/PaymentGatewayMetadata.yaml
> +          Creates an `authorize` transaction in the amount/currency of the request, followed by a `void` (if the `authorize` was approved).
It would behave like any authorize transaction. But why have this line if this is applied to `setupInstruction=sca`? Or what other instruction also affects it?

2021-10-15 20:09 UTC, adamaltman commented on openapi/components/schemas/Metadata/PaymentGatewayMetadata.yaml
> +          Creates an `authorize` transaction in the amount/currency of the request, followed by a `void` (if the `authorize` was approved).
Because this line is needed for clarity.

2021-10-16 02:03 UTC, 2e3s approved these changes

2021-10-25 17:48 UTC, ashkarpetin approved these changes

2021-10-25 19:51 UTC, merged