Shipping rates API
Rebilly/api-definitions pull request #644
Opened 2021-10-26 15:02 UTC by justnero

2021-12-14 08:13 UTC, creocoder commented on openapi/components/schemas/ShippingTypes/rebilly.yaml
> +      shippingRateId:
```suggestion
      rateId:
```

2022-01-10 14:49 UTC, Boydbueno commented on openapi/components/schemas/ShippingTypes/rebilly.yaml
> +          - $ref: ../../ResourceId.yaml
Thanks. Resolved it.

2022-01-25 15:16 UTC, Boydbueno submitted a review, later dismissed

2022-01-25 17:37 UTC, adamaltman requested changes

2022-01-25 17:37 UTC, adamaltman commented on openapi/components/schemas/ShippingTypes/rebilly.yaml
> +        description: The shipping rate ID. If unset – cheapest shipping rate among applicable would be chosen.
```suggestion
        description: The shipping rate ID. If unset the cheapest applicable shipping rate is chosen.
```

2022-01-25 17:37 UTC, adamaltman commented on openapi/components/schemas/Storefront/Purchase.yaml
> +    description: The shipping rate ID. If unset – cheapest shipping rate among applicable would be chosen.
```suggestion
    description: The shipping rate ID. If unset the cheapest applicable shipping rate is chosen.
```

2022-01-26 12:29 UTC, vykhrystiuk commented on openapi/components/schemas/Common/CommonOrderPreview.yaml
> +    description: The shipping rate ID. If unset – cheapest shipping rate among applicable would be chosen.
```suggestion
    description: The shipping rate ID. If unset the cheapest applicable shipping rate is chosen.
```

https://github.com/Rebilly/api-definitions/pull/644#discussion_r791964287

2022-01-28 12:08 UTC, adamaltman approved these changes

2022-01-28 12:36 UTC, Boydbueno commented
Please review

2022-01-28 12:45 UTC, ashkarpetin approved these changes

2022-01-28 13:18 UTC, merged