Add Backup Payment instruments
Rebilly/api-definitions pull request #718
Opened 2022-01-31 14:03 UTC by XaosSintez

2022-02-01 07:06 UTC, akozhevnikov-rebilly approved these changes, later dismissed

2022-02-02 11:18 UTC, justnero approved these changes, later dismissed

2022-02-02 14:22 UTC, ninjasimon approved these changes, later dismissed

2022-02-04 04:17 UTC, adamaltman requested changes
chore: minor edits

2022-02-04 04:17 UTC, adamaltman commented on openapi/components/schemas/Common/CommonAlternativeInstrument.yaml
> +    description: Allow to use this payment instrument as backup, it will be used on invoice payment retry.
```suggestion
    description: Allow using this payment instrument as a backup for invoice payment retries.
```

2022-02-04 04:17 UTC, adamaltman commented on openapi/components/schemas/Common/CommonBankAccount.yaml
> +    description: Allow to use this payment instrument as backup, it will be used on invoice payment retry.
```suggestion
    description: Allow using this payment instrument as a backup for invoice payment retries.
```

2022-02-04 04:17 UTC, adamaltman commented on openapi/components/schemas/Common/CommonPayPalAccount.yaml
> +    description: Allow to use this payment instrument as backup, it will be used on invoice payment retry.
```suggestion
    description: Allow using this payment instrument as a backup for invoice payment retries.
```

2022-02-04 04:17 UTC, adamaltman commented on openapi/components/schemas/Common/CommonPaymentCard.yaml
> +    description: Allow to use this payment instrument as backup, it will be used on invoice payment retry.
```suggestion
    description: Allow using this payment instrument as a backup for invoice payment retries.
```

2022-02-04 04:54 UTC, adamaltman approved these changes

2022-02-04 05:21 UTC, subenson approved these changes

2022-02-04 06:51 UTC, vykhrystiuk approved these changes

2022-02-08 06:28 UTC, merged