Add credit file kyc endpoint
Rebilly/api-definitions pull request #757
Opened 2022-02-21 16:50 UTC by dara123

2022-02-22 15:05 UTC, adamaltman requested changes

2022-02-22 15:05 UTC, adamaltman commented on openapi/components/schemas/CreditFileKyc.yaml
> +      - trans-union
```suggestion
      - equifax
      - trans-union
      - experian
```

2022-02-22 15:05 UTC, adamaltman commented on openapi/components/schemas/CreditFileKyc.yaml
> +properties:
missing the `createdTime`.

2022-02-22 15:05 UTC, adamaltman commented on openapi/paths/credit-file-kyc.yaml
> +  summary: Retrieve a list of credit file method kyc.
```suggestion
  summary: List credit file KYC reports
```

2022-02-22 15:05 UTC, adamaltman commented on openapi/paths/credit-file-kyc.yaml
> +    Retrieve a list of credit file kyc method.
```suggestion
    Retrieve a list of credit file KYC reports.
```

2022-02-22 15:05 UTC, adamaltman commented on openapi/paths/credit-file-kyc.yaml
> +      description: Credit file kyc was retrieved successfully.
```suggestion
      description: Credit file KYC report was retrieved successfully.
```

2022-02-22 15:05 UTC, adamaltman commented on openapi/paths/credit-file-kyc.yaml
> +  summary: Create credit file method kyc.
```suggestion
  summary: Run credit file KYC report
```

2022-02-22 15:05 UTC, adamaltman commented on openapi/paths/credit-file-kyc.yaml
> +    Trigger an API call to credit bureau and store the response.
```suggestion
    Trigger an API call to credit bureau to do a credit file KYC check and store the response.
```

2022-02-22 15:05 UTC, adamaltman commented on openapi/paths/credit-file-kyc.yaml
> +      description: Credit file kyc was created.
```suggestion
      description: Credit file KYC report was created.
```

2022-02-22 15:52 UTC, colinbird commented on openapi/components/schemas/CreditFileKyc.yaml
> +    description: Return true if city address is matched otherwise false.
```suggestion
    description: Return true if city is matched otherwise false.
```

2022-02-28 15:53 UTC, dara123 commented
We don't need this new endpoint. We need to update our `PostKycRequest` endpoint to add new subtype `credit-file-proof` and trigger credit file check and `embeded` in the response

2022-03-03 16:32 UTC, dara123 commented
https://github.com/Rebilly/api-definitions/pull/772

2022-03-03 16:32 UTC, closed without merging