Add EDD
Rebilly/api-definitions pull request #766
Opened 2022-02-27 19:14 UTC by XaosSintez

2022-03-01 02:44 UTC, adamaltman commented on openapi/components/schemas/Edd/EddScoreDetails.yaml
> +    description: The text where score is taked from.
```suggestion
    description: The url where score is taken from.
  details:
    type: string
    description: The text where score is taken from.
```

2022-03-01 02:44 UTC, adamaltman commented on openapi/paths/customers@{id}@edd-score.yaml
> +    - Payments
```suggestion
```

2022-03-01 02:45 UTC, adamaltman commented on openapi/paths/customers@{id}@edd-search-results.yaml
> +    - Payments
```suggestion
```

2022-03-01 02:45 UTC, adamaltman commented on openapi/paths/customers@{id}@edd-score.yaml
> +    - Payments
```suggestion
```

2022-03-24 16:12 UTC, agualis requested changes

2022-03-24 16:12 UTC, agualis commented on openapi/paths/customers@{id}@edd-timeline.yaml
> +  x-sdk-operation-name: createTimelineComment
We are already using this Id for `PostCustomerTimeline` operation.
Why not using `createEddTimelineComment`?

2022-03-28 07:54 UTC, agualis approved these changes

2022-03-28 08:04 UTC, justnero approved these changes

2022-03-28 10:13 UTC, akozhevnikov-rebilly approved these changes

2022-03-28 10:15 UTC, merged