KYC acceptance report improvements
Rebilly/api-definitions pull request #777
Opened 2022-03-07 11:32 UTC by akozhevnikov-rebilly

2022-03-07 12:12 UTC, adamaltman requested changes

2022-03-07 12:12 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                    acceptAutoRejected:
```suggestion
                    acceptedAutoRejected:
```

2022-03-07 12:12 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
>                      autoAcceptedPercentage:
This needs to be adjusted, and we need to have more percentages to communicate ratios:
```
accuracyRate:
  description: Percent of automatically accepted and rejected documents that remain in the same status after review.
acceptanceRate:
  description: Percent of accepted documents out of the total number of KYC documents.
```

2022-03-07 12:32 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                      description: Percent of automatically accepted and rejected documents that remain in the same status after review.
From the numbers above, accuracy rate would be:

= (total - acceptedAutoRejected - rejectedAutoAccepted)/total

With some sample numbers:

1000 total
200 accepted that were auto rejected
20 rejected that were auto accepted
600 total accepted

accuracy rate = (1000 - 200 - 20)/1000 = 780/1000 = 78%
acceptance rate = 600/1000 = 60%

2022-03-07 12:34 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                      description: Percent of automatically accepted and rejected documents that remain in the same status after review.
(This information may be good in the API description.)
```suggestion
                      description: |
                        Percent of automatically accepted and rejected documents that remain in the same status after review.
                        Calculated by the formula: `(total - accepted auto rejected - rejected auto accepted)/total`.
```

2022-03-07 12:34 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                      description: Percent of accepted documents out of the total number of KYC documents.
```suggestion
                      description: Percent of accepted documents out of the total number of KYC documents. Calculated by accepted total divided by the total.
```

2022-03-09 01:29 UTC, adamaltman approved these changes, later dismissed

2022-03-09 13:26 UTC, ashkarpetin approved these changes, later dismissed

2022-03-11 13:52 UTC, ashkarpetin submitted a review, later dismissed

2022-03-11 13:54 UTC, mikerebilly approved these changes, later dismissed

2022-03-11 13:56 UTC, vykhrystiuk submitted a review, later dismissed

2022-03-11 18:07 UTC, adamaltman approved these changes, later dismissed
Minor text changes to add prior to merge

2022-03-11 18:07 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been accepted by user.
```suggestion
                              description: Amount of documents that have been accepted by reviewer.
```

2022-03-11 18:07 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been rejected automatically and then accepted by user.
```suggestion
                              description: Amount of documents that have been rejected automatically and then accepted by reviewer.
```

2022-03-11 18:07 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been rejected automatically and then accepted by user.
```suggestion
                              description: Amount of documents that have been rejected automatically and then accepted by reviewer.
```
```suggestion
                              description: Amount of documents that have been rejected automatically and then accepted by user.
```

2022-03-11 18:07 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been rejected by user.
```suggestion
                              description: Amount of documents that have been rejected by reviewer.
```

2022-03-11 18:07 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been rejected by user.
```suggestion
                              description: Amount of documents that have been rejected by reviewer.
```
```suggestion
                              description: Amount of documents that have been rejected by user.
```

2022-03-11 18:07 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been accepted automatically and then rejected by user.
```suggestion
                              description: Amount of documents that have been accepted automatically and then rejected by reviewer.
```

2022-03-11 18:07 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been accepted automatically and then rejected by user.
```suggestion
                              description: Amount of documents that have been accepted automatically and then rejected by reviewer.
```

2022-03-11 18:32 UTC, ashkarpetin approved these changes

2022-03-11 18:44 UTC, vykhrystiuk approved these changes

2022-03-11 18:50 UTC, adamaltman approved these changes

2022-03-11 18:50 UTC, adamaltman commented on openapi/paths/reports@kyc-acceptance-summary.yaml
> +                              description: Amount of documents that have been accepted by user.
```suggestion
                              description: Amount of documents that have been accepted by reviewer.
```

2022-03-14 07:50 UTC, merged