Improve definitions with discriminator
Rebilly/api-definitions pull request #789
Opened 2022-03-10 18:12 UTC by VladimirBerdnik

2022-03-14 03:26 UTC, VladimirBerdnik commented
devs please review

2022-03-14 03:46 UTC, adamaltman requested changes

2022-03-14 03:46 UTC, adamaltman commented on openapi/components/schemas/GatewayAccount.yaml
> +oneOf:
I think this is incorrect. They are using allOf so they are valid. And it must be anyOf here, because many of them have the same schema.

2022-03-14 03:52 UTC, VladimirBerdnik commented on openapi/components/schemas/GatewayAccount.yaml
> +oneOf:
```suggestion
anyOf:
```

2022-03-14 04:16 UTC, VladimirBerdnik commented on openapi/components/schemas/GatewayAccount.yaml
> +oneOf:
Site previews started to crash after this change. I don't see the reason, it only says it is crashed

2022-04-17 12:44 UTC, adamaltman commented on openapi/components/schemas/Timelines/TimelineAction.yaml
> +  - $ref: ./Actions/schow-edd-search-logs.yaml
```suggestion
  - $ref: ./Actions/show-edd-search-logs.yaml
```

2022-07-01 05:03 UTC, VladimirBerdnik commented
Closing due to age

2022-07-01 05:03 UTC, closed without merging