Add more fields to Kyc credit file match data
Rebilly/api-definitions pull request #829
Opened 2022-04-11 18:46 UTC by dara123

2022-04-11 18:48 UTC, ashkarpetin commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Return true if it's dual source decision. Kyc document will rejected but can use it with another source.
> Kyc document will rejected but can use it with another source.


Can you please elaborate? I don't understand.

2022-04-11 18:52 UTC, dara123 commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Return true if it's dual source decision. Kyc document will rejected but can use it with another source.
so we accept/reject base on `isSingleSourceDecision`.
if isSingleSourceDecision is true we accept document all good.
if isSingleSourceDecision is false we reject document but isDualSourceDecision is true merchant can use it if they have another source of KYC like identity or address proof

2022-04-11 18:54 UTC, dara123 commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Return true if it's dual source decision. Kyc document will rejected but can use it with another source.
need to fix description

2022-04-11 19:42 UTC, adamaltman commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +  isDualSourceDecision:
```suggestion
  decision:
    description: Value based on if the credit file can be used as a single source proof of identity decision, requires at least one more source (dual-source), or other for anything else.
    type: string
    enum:
      - single-source
      - dual-source
      - other
    readOnly: true
```

2022-04-11 21:12 UTC, adamaltman commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Return true if it's single source decision. Kyc document will be accepted.
```suggestion
    description: Return `true` if it's single source decision, then the Kyc document is accepted.
```

2022-04-12 13:04 UTC, dara123 commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> -  isCivicNumberMatched:
I don't think we need these field anymore since we only need `isSingleSourceDecision` and `isDualSourceDecision` to calculate the score. we can more these fields to `referenceData`.

2022-04-12 13:34 UTC, adamaltman requested changes
This needs some more change:

> If you use the credit file method, you must record:[Footnote6](https://www.fintrac-canafe.gc.ca/guidance-directives/client-clientele/Guide11/11-eng#fn20216) 
> 
> the person's name;
> the date you consulted or searched the credit file;
> the name of the Canadian credit bureau or third party vendor as the source holding the credit file; and
> the person's credit file number.
> 

This must contain the person's name, and the date we consulted the file. While it should be the `createdTime`, I don't know if that is explicit enough and I don't know if anything could influence it differently where it is consulted after it is created for some reason I can't guess now.

2022-04-12 13:37 UTC, adamaltman commented
Also for dual process:

> If you use the dual-process method to verify a person's identity, you must record:[Footnote12](https://www.fintrac-canafe.gc.ca/guidance-directives/client-clientele/Guide11/11-eng#fn202112)
> 
> - the person's name;
> - the date you verified the information;
> - the name of the two different reliable sources that were used to verify the identity of the person;
> - the type of information referred to (for example, a utility statement, a bank statement, a marriage licence); and
> - the number associated with the information (for example, account number or if there is no account number, a number that is associated with the information, which could be a reference number or certificate number, etc.). If you use information aggregated by a Canadian credit bureau and receive information from two distinct sources (tradelines), you must record the account number or number associated to each tradeline, not the aggregator (credit bureau) number.
>

2022-04-12 13:54 UTC, ashkarpetin commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Date to cosult with credit file bureaur.
```suggestion
    description: Date to consult with credit file bureau.
```

2022-04-12 13:55 UTC, adamaltman requested changes, later dismissed
This is still missing the required fields for dual process

2022-04-12 13:55 UTC, adamaltman commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Date to cosult with credit file bureaur.
```suggestion
    description: Date consulted with credit file bureau.
```

2022-04-12 13:55 UTC, adamaltman commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    type: string
```suggestion
    type: string
    format: date-time
```

2022-04-12 15:26 UTC, dara123 commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +  dualSourceData:
This will be something like this
```
dualSourceData => [
	[
		'InstitutionName',
		'AccountNumber',
		'DateOpened',
	],
	[
		'InstitutionName',
		'AccountNumber',
		'DateOpened',
	],
]
```

2022-04-13 13:45 UTC, ashkarpetin commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Contain 2 objects from different source like statements, letters, certificates, forms or other information sources.
```suggestion
    description: Contains 2 objects from different sources like statements, letters, certificates, forms or other information sources.
```

2022-04-14 14:56 UTC, VladimirBerdnik commented on openapi/components/schemas/KycDocument/CreditFileMatches.yaml
> +    description: Date to cosult with credit file bureau.
```suggestion
    description: Date to consult with credit file bureau.
```

2022-04-15 12:08 UTC, dara123 commented
@Rebilly/php please review

2022-04-15 17:29 UTC, dara123 commented
@Rebilly/php please review

2022-04-18 21:32 UTC, adamaltman approved these changes

2022-04-19 09:56 UTC, ashkarpetin approved these changes

2022-04-19 12:42 UTC, merged