Mark invoiceTimeShift parameter as deprecated
Rebilly/api-definitions pull request #838
Opened 2022-04-20 09:51 UTC by nanobash

2022-04-20 14:09 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        description: >
These descriptions I copies from `IssueTimeShiftInstruction` and from `DueTimeShiftInstruction`, as the idea is the same, but maybe we should modify also the description or add something?

2022-04-21 07:00 UTC, VladimirBerdnik commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '-P00Y00M00DT00H00M00S'
```suggestion
        default: '-P00Y00M00DT00H00M00S'
        example: '-P7D'
```

2022-04-21 07:01 UTC, VladimirBerdnik commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          This is used in conjunction with the **billing anchor** to calculate due time
```suggestion
          This is used in conjunction with the issue time to calculate due time
```

2022-04-21 07:02 UTC, VladimirBerdnik commented on openapi/components/schemas/Plans/Plan.yaml
> +          This is used in conjunction with the **billing anchor** to calculate due time
```suggestion
          This is used in conjunction with the issue time to calculate due time
```

2022-04-21 07:02 UTC, VladimirBerdnik commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '+P00Y00M00DT00H00M00S'
```suggestion
        default: '+P00Y00M00DT00H00M00S'
        example: '-P7D'
```

2022-04-21 07:03 UTC, VladimirBerdnik commented on openapi/components/schemas/Plans/Plan.yaml
> +        default: '-P00Y00M00DT00H00M00S'
```suggestion
        default: '-P00Y00M00DT00H00M00S'
        example: '-P7D'
```

2022-04-21 07:05 UTC, VladimirBerdnik commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        description: >
The format of the value is not described, I think we must mention is like here: https://github.com/Rebilly/api-definitions/blob/881206bb988d51ce8528f6a4708cf614a60a2ec8/openapi/components/schemas/Subscription/SubscriptionPause.yaml#:~:text=in%20ISO%2D8601%20durations%20format

2022-04-21 10:24 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        description: >
Good point, updated, thanks

2022-04-21 10:24 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '-P00Y00M00DT00H00M00S'
Nice one, updated, thanks

2022-04-21 10:24 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          This is used in conjunction with the **billing anchor** to calculate due time
Thanks, updated

2022-04-21 10:25 UTC, nanobash commented on openapi/components/schemas/Plans/Plan.yaml
> +          This is used in conjunction with the **billing anchor** to calculate due time
Updated, thanks

2022-04-21 10:25 UTC, nanobash commented on openapi/components/schemas/Plans/Plan.yaml
> +        default: '-P00Y00M00DT00H00M00S'
Updated, thanks

2022-04-21 11:25 UTC, VladimirBerdnik commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
```suggestion
          Time period between the invoice issue time shift and the renewal time in **ISO-8601** format.
```

2022-04-21 11:25 UTC, VladimirBerdnik commented on openapi/components/schemas/Plans/Plan.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
```suggestion
Time period between the invoice issue time shift and the renewal time in **ISO-8601** format.
```

2022-04-21 11:28 UTC, VladimirBerdnik commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
```suggestion
          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
          Period must be positive.
```
The term `chronology` seems not relevant to this value anymore

2022-04-21 11:29 UTC, VladimirBerdnik commented on openapi/components/schemas/Plans/Plan.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
```suggestion
          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
          Period must be positive.
```
The term `chronology` seems not relevant to this value anymore

2022-04-21 11:35 UTC, adamaltman commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
Needs a better explanation still. I have an idea...

2022-04-21 12:58 UTC, adamaltman requested changes

2022-04-21 12:58 UTC, adamaltman commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
```suggestion
        description: |-
          Time period between the renewal invoice issue time and subscription's renewal time in **ISO-8601** format.
```

2022-04-21 12:58 UTC, adamaltman commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
```suggestion
        description: |-
          This is the relative time period (in **ISO-8601** format) after the renewal invoice issue time to calculate due time of the invoice. The period must be zero or positive because it can only be due at or after the issue time.
```

2022-04-21 12:58 UTC, adamaltman commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        nullable: true
I have the same issue here with the nullable.

2022-04-21 12:58 UTC, adamaltman commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '+P00Y00M00DT00H00M00S'
I thought our default is 1 hour later?

2022-04-21 12:58 UTC, adamaltman commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '+P00Y00M00DT00H00M00S'
And I question if this is actually default value -- is it returned in the API? Or is it a default behavior of a null value?

2022-04-21 12:58 UTC, adamaltman commented on openapi/components/schemas/Plans/Plan.yaml
> +        deprecated: true
This may be good spirited, but it kind of harms the docs. Move this property to the very bottom of this object. Having deprecated properties at the top does a disservice to everyone involved.

2022-04-21 12:58 UTC, adamaltman commented on openapi/components/schemas/Plans/Plan.yaml
> +      invoiceIssueTimeShift:
I have the same issue here as I do with the ones above.

2022-04-21 14:45 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
Updated, thank you

2022-04-21 14:45 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
Updated, thank you

2022-04-21 15:14 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
Thanks for suggestions, updated

2022-04-21 15:15 UTC, nanobash commented on openapi/components/schemas/Plans/Plan.yaml
> +          Time period between the invoice issue time shift and the invoice due time shift in **ISO-8601** format.
Updated as Adam requested, thank you

2022-04-21 15:37 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        nullable: true
Technically on database layer columns `invoiceIssueTimeShift` and `invoiceDueTimeShift` are nullable (they were needed for altering table and adding the columns and basically for transition from old implementation), that's why I put param as nullable too, however on application layer once Plan or Subscription is created default values are applied which is `+P00Y00M00DT00H00M00S`. So I think you are right and we can remove nullable from here

2022-04-21 15:55 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '+P00Y00M00DT00H00M00S'
The default one is `+P00Y00M00DT00H00M00S`. If in DB value is null, API also returns null, but without manual interaction value in DB can't be null for Plan or Subscription, as in case of absence during creation default values are applied

2022-04-21 16:02 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        nullable: true
Removed, thank you

2022-04-21 16:02 UTC, nanobash commented on openapi/components/schemas/Plans/Plan.yaml
> +      invoiceIssueTimeShift:
Applied the same changes like with the ones above, thank you

2022-04-27 11:08 UTC, nanobash commented
@Rebilly/php please review

2022-04-27 11:12 UTC, creocoder commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '+P00Y00M00DT00H00M00S'
I think default for due time should be `+PT1H` hour as @adamaltman mentioned.

2022-04-27 11:24 UTC, nanobash commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '+P00Y00M00DT00H00M00S'
I see, updated, thank you

2022-04-27 11:34 UTC, creocoder commented on openapi/components/schemas/Common/CommonSubscriptionOrder.yaml
> +        default: '+P00Y00M00DT00H00M00S'
Thank you 👍

2022-08-02 01:11 UTC, adamaltman approved these changes
What is the status of this?

2022-08-02 05:22 UTC, akozhevnikov-rebilly approved these changes

2023-04-21 15:57 UTC, nanobash commented
[Backend implementation is closed](https://github.com/Rebilly/backend/pull/15541).

2023-04-21 15:57 UTC, closed without merging