Add MRR report
Rebilly/api-definitions pull request #859
Opened 2022-05-13 13:25 UTC by justnero

2022-05-13 14:12 UTC, jvc9109 commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                MRR of new customers who didn't have revenue before they placed an order.
```suggestion
                MRR of new customers who didn't have recurring revenue before they placed an order.
```

2022-05-13 14:26 UTC, adamaltman commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                MRR of new customers who didn't have revenue before they placed an order.
This seems strange. Isn't a "new customer" someone who didn't have revenue?
```suggestion
                MRR of new customers.
```

2022-05-13 14:29 UTC, adamaltman requested changes

2022-05-13 14:29 UTC, adamaltman commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +            reactivated:
```suggestion
            reactivation:
```

2022-05-13 14:29 UTC, adamaltman commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +            contracted:
```suggestion
            contraction:
```

2022-05-13 14:29 UTC, adamaltman commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +            expanded:
```suggestion
            expansion:
```

2022-05-13 14:29 UTC, adamaltman commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                Sally upgraded to a plan that's $100/month. She was at $40/month, so the expansions MRR is $60.
```suggestion
                Sally upgraded to a plan that's $100/month. She was at $40/month, so the expansion MRR is $60.
```

2022-05-13 15:19 UTC, noon-dawg commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +          description: The total MRR amount.
nitpick: It's good to describe the acronym in its first instance. 

```suggestion
          description: Total Maintenance Margin Requirement (MMR) amount.
```

2022-05-13 15:24 UTC, noon-dawg commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +            The difference between current period MRR and previous period MRR would be equal to `new + reactivated + expanded - contracted - churned`.
nitpick: Avoid passives

`would, could, should, ...`

```suggestion
            MRR categories are described below.
            The difference between current period MRR and previous period MRR is equal to `new + reactivated + expanded - contracted - churned`.
```

2022-05-13 15:26 UTC, noon-dawg commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                For example, Sally is a new customer who signed up and is at $40/month plan is $40 in new MRR.
```suggestion
                For example, Sally is a new customer who signed up to a $40 per month plan. This is $40 in new MRR.
```

2022-05-13 15:30 UTC, noon-dawg commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                She purchases the $25/month plan. This is reactivation MRR, and is at $25.
```suggestion
                Sally was previously a customer but stopped being a customer for a period.
                She signs up again and purchases a $25 per month plan. This is reactivation MRR of $25.
```

2022-05-13 15:36 UTC, noon-dawg commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                When the subscription churns, she went from $80/month to $0/month, and that is $80 of churned MRR.
```suggestion
                A customer decides to cancel.
                The subscription churns, the customer goes from $80 per month to $0 per month. This is $80 of churned MRR.
```

2022-05-13 15:41 UTC, noon-dawg commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                For example, Sally was at $100 in MRR, and changed to $80 in MRR. The contraction MRR is $20.
```suggestion
                Existing customers who changed items which resulted in a smaller MRR. Contraction MRR is the difference.
                For example, a customer at $100 in MRR changes to $80 in MRR. This contraction MRR is $20.
```

2022-05-13 15:44 UTC, noon-dawg commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +                Sally upgraded to a plan that's $100/month. She was at $40/month, so the expansions MRR is $60.
```suggestion
                Existing customers who changed items which resulted in a bigger MRR.
                Example: A customer upgrades from a plan that is $40 per month to a plan that is $100 per month. This is an expansion MRR of $60.
```

2022-05-13 17:00 UTC, justnero commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +          description: The total MRR amount.
Agreed, but it's MRR, not MMR, so
```suggestion
          description: Total Monthly Recurring Revenue (MRR) amount.
```

2022-05-13 17:05 UTC, justnero commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +            churned:
Should this also be renamed? @adamaltman @noon-dawg 
```suggestion
            churn:
```

2022-05-13 18:52 UTC, adamaltman commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +            churned:
No, this is correct as churned.

2022-05-13 18:53 UTC, adamaltman submitted a review, later dismissed
This could be made better with some examples.

2022-05-13 18:53 UTC, adamaltman commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +          pattern: '^\d{4}-\d{2}$'
Even a simple example here would be helpful
```suggestion
          pattern: '^\d{4}-\d{2}$'
          example: 2022-06
```

2022-05-13 19:23 UTC, justnero commented on openapi/components/schemas/ReportMonthlyRecurringRevenue.yaml
> +          pattern: '^\d{4}-\d{2}$'
Good point, added, please re-review.

2022-05-13 19:25 UTC, ninjasimon approved these changes

2022-05-14 12:56 UTC, adamaltman approved these changes

2022-05-14 14:59 UTC, ashkarpetin approved these changes

2022-05-16 07:54 UTC, noon-dawg approved these changes

2022-05-16 09:18 UTC, jvc9109 approved these changes

2022-05-16 10:23 UTC, merged