Add transaction limits parameter to transactions
Rebilly/api-definitions pull request #860
Opened 2022-05-15 13:49 UTC by nanobash

- Add transaction amount limits parameter to transactions

2022-05-15 14:50 UTC, adamaltman requested changes

2022-05-15 14:50 UTC, adamaltman commented on openapi/components/schemas/Transactions/Transaction.yaml
> +        allOf:
allOf isn't required here.

2022-05-15 14:50 UTC, adamaltman commented on openapi/components/schemas/Transactions/TransactionRequest.yaml
> +        allOf:
allOf isn't required here.

2022-05-15 15:14 UTC, nanobash commented on openapi/components/schemas/Transactions/Transaction.yaml
> +        allOf:
Removed, thank you

2022-05-15 15:14 UTC, nanobash commented on openapi/components/schemas/Transactions/TransactionRequest.yaml
> +        allOf:
Removed, thank you

2022-05-15 15:21 UTC, adamaltman approved these changes, later dismissed

2022-05-16 05:54 UTC, justnero submitted a review, later dismissed

2022-05-16 10:13 UTC, ashkarpetin submitted a review, later dismissed

2022-05-16 13:41 UTC, vykhrystiuk approved these changes, later dismissed

2022-05-17 07:41 UTC, noon-dawg commented on openapi/components/schemas/TransactionLimitAmount.yaml
> +    description: The time the limit resets which may be used for some user interfaces.
suggestion: At first read I was not sure which time was being reset.
I understood on the second or third read. My suggestion here is to help make this more explicit.

```suggestion
    description: The date and time in which the limit amount resets. This value may be used for some user interfaces.
```

2022-05-17 16:40 UTC, nanobash commented
@Rebilly/php please review

2022-05-17 16:40 UTC, ashkarpetin approved these changes

2022-05-17 16:43 UTC, noon-dawg approved these changes

2022-05-17 16:43 UTC, justnero approved these changes

2022-05-17 16:48 UTC, merged