Add jorunal report
Rebilly/api-definitions pull request #905
Opened 2022-06-27 08:23 UTC by justnero

2022-07-22 07:57 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +      description: Revenue booked month.
nitpick: suggestion to aid clarity
```suggestion
      description: Month in which revenue is booked.
```

2022-07-22 08:04 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +      description: The revenue amount booked for recognition.
nitpick: Where possible, we should avoid starting descriptions with "The"

It makes the docs tiresome to read

(I have some really basic writing style guidance for API docs [here](https://product.rebilly.dev/writing-style-guide/api-reference/))

```suggestion
      description: Revenue amount this is booked for recognition.
```

2022-07-22 08:06 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +      description: The revenue amount recognized.
nitpick: I find this easier to read
```suggestion
      description: Recognized revenue amount.
```

2022-07-22 08:48 UTC, noon-dawg reviewed
Small suggestions

2022-07-22 08:48 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +      description: The revenue amount remaining to be recognized.
nitpick: We should use the adjective before the noun

The placement of "remaining" (adjective) made it a little confusing

```suggestion
      description: Remaining revenue amount to be recognized.
```

2022-07-22 08:48 UTC, noon-dawg commented on openapi/components/schemas/ReportRevenueWaterfall.yaml
> +      description: The revenue amount recognized up to `recognizedTo` month.
question: does recognized revenue include the `recognizedTo` month?
```suggestion
      description: Recognized revenue amount up to, and including, the `recognizedTo` month.
```

```suggestion
      description: Recognized revenue amount up to, and excluding, the `recognizedTo` month.
```

2022-07-22 08:48 UTC, noon-dawg commented on openapi/paths/reports@journal.yaml
> +  summary: Retrieve a journal report
```suggestion
  summary: Retrieve a journal report.
```

2022-07-22 08:48 UTC, noon-dawg commented on openapi/paths/reports@journal.yaml
> +      description: Revenue booked from month. Omit to retrieve booked starting from the start.
nitpick: I was unsure of the meaning of the second sentence

```suggestion
      description: Month from which revenue is booked. Omit this value to retrieve booked revenue starting from the first booked amount.
```

2022-07-22 08:48 UTC, noon-dawg commented on openapi/paths/reports@journal.yaml
> +      description: Revenue booked to month. Omit to retrieve booked to the end.
nitpick: "Booked to" is a bit ambitious

```suggestion
      description: Month in which revenue is booked until. Omit this value to retrieve booked revenue up until the most recently booked amount.
```

2022-07-22 08:48 UTC, noon-dawg commented on openapi/paths/reports@journal.yaml
> +      description: Revenue recognition month.
nitpick: suggestion to aid clarity
```suggestion
      description: Month in which revenue was recognized.
```

2022-07-22 08:48 UTC, noon-dawg commented on openapi/paths/reports@journal.yaml
> +      description: Report was retrieved successfully.
nitpick: where possible, avoid past tense

```suggestion
      description: Report successfully retrieved.
```

2022-07-22 21:10 UTC, 2e3s commented on openapi/components/schemas/ReportJournal.yaml
> +      description: The revenue amount booked for recognition.
```suggestion
      description: Revenue amount which is booked for recognition.
```

2022-07-25 07:43 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +      description: The revenue amount booked for recognition.
Oops! :) Sorry

2022-07-25 13:53 UTC, noon-dawg commented
LGTM

2022-07-25 14:08 UTC, 2e3s submitted a review, later dismissed

2022-07-25 14:33 UTC, 2e3s commented
devs please review

2022-07-25 14:34 UTC, ashkarpetin approved these changes, later dismissed

2022-07-26 03:52 UTC, ninjasimon approved these changes, later dismissed

2022-07-27 03:43 UTC, adamaltman requested changes

2022-07-27 03:43 UTC, adamaltman commented on openapi/paths/reports@journal.yaml
> +  summary: Retrieve a journal report.
```suggestion
  summary: Retrieve a journal report
```
Operation summary should not have a full stop.

2022-07-27 07:43 UTC, n-fasano submitted a review, later dismissed

2022-07-27 12:40 UTC, adamaltman commented on openapi/paths/reports@journal.yaml
> +  description: Retrieve a journal report.
This description should be enhanced. What is a journal report? This doesn't answer that question and it should.

2022-07-27 12:42 UTC, adamaltman commented on openapi/components/schemas/ReportJournal.yaml
> +  type: object
This object doesn't show the `aggregationField` anywhere. I find this more difficult API design because it means I need to retain some state about the request.

2022-07-27 17:19 UTC, 2e3s commented on openapi/components/schemas/ReportJournal.yaml
> +  type: object
But there are also `currency`, `bookedFrom`, `bookedTo`, `recognizedAt`, why distinguish `aggregationField`?

2022-07-27 18:17 UTC, adamaltman commented on openapi/components/schemas/ReportJournal.yaml
> +  type: object
I'm not -- perhaps those should be included too. Maybe the design should be:

```yaml
type: object
properties:
  currency:
     type: string
  bookedFrom
     type: string
#  etc...
   data:
      type: array
#       etc...
```

2022-07-27 20:28 UTC, 2e3s commented on openapi/components/schemas/ReportJournal.yaml
> +  type: object
I've restructured it this way, I have some doubts though about the consistency of this approach. Most our APIs have some incoming request data, and none return it back. Not only reports, but e.g. filters or offset/limit in collections, the latter being provided in headers.
```
type: object
properties:
   data:
```
This one is more consistent with other reports though.

2022-07-31 16:33 UTC, adamaltman commented on openapi/components/schemas/ReportJournal.yaml
> +  type: object
Yes, I think with filters we don't return anything back, but with offset/limits those are returned in headers and the client can use those appropriately.

2022-07-31 16:38 UTC, adamaltman commented on openapi/components/schemas/ReportJournal.yaml
> +    example: 2022-01
```suggestion
  aggregationField:
    type: string
    description: The report data is grouped by the aggregation field.
    enum:
      - product.accountingCode
      - product.id
      - plan.id
  currency:
    $ref: CurrencyCode.yaml
  bookedFrom:
    type: string
    description: A year and month in `yyyy-mm` format.
    pattern: '^\d{4}-\d{2}$'
    example: 2022-01
  bookedTo:
    type: string
    description: A year and month in `yyyy-mm` format.
    pattern: '^\d{4}-\d{2}$'
    example: 2022-01
  recognizedAt:
    type: string
    description: A year and month in `yyyy-mm` format.
    pattern: '^\d{4}-\d{2}$'
    example: 2022-01
```

2022-07-31 16:38 UTC, adamaltman commented on openapi/components/schemas/ReportJournal.yaml
> +    example: 2022-01
I am recommending descriptions.

2022-08-01 02:54 UTC, 2e3s commented on openapi/components/schemas/ReportJournal.yaml
> +    example: 2022-01
My bad, I should've thought about it

2022-08-01 09:38 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +    description: A year and month in `yyyy-mm` format.
question: should we use the same descriptions as in `openapi/paths/reports@journal.yaml` here?

I feel that these descriptions describe the expected value but not what the value is used for. I think the example and pattern kind of describes this already

From `openapi/paths/reports@journal.yaml`:
```suggestion
    description: Month from which revenue is booked. Omit this value to retrieve booked revenue starting from the first booked amount.
```

2022-08-01 09:38 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +    description: A year and month in `yyyy-mm` format.
Suggestion based on `openapi/paths/reports@journal.yaml`

```suggestion
    description: Month in which revenue is booked until. Omit this value to retrieve booked revenue up until the most recently booked amount.
```

2022-08-01 09:38 UTC, noon-dawg commented on openapi/components/schemas/ReportJournal.yaml
> +    description: A year and month in `yyyy-mm` format.
Suggestion based on `openapi/paths/reports@journal.yaml`

```suggestion
    description:  Month in which revenue was recognized.
```

2022-08-01 17:32 UTC, 2e3s commented on openapi/components/schemas/ReportJournal.yaml
> +    description: A year and month in `yyyy-mm` format.
I don't think that the descriptions need to match exactly. One is a control field, the other is informational.

2022-08-02 01:07 UTC, adamaltman approved these changes

2022-08-02 06:50 UTC, noon-dawg commented
LGTM

2022-08-02 06:55 UTC, ashkarpetin approved these changes

2022-08-02 20:10 UTC, merged