Add revenue audit report
Rebilly/api-definitions pull request #915
Opened 2022-07-06 17:25 UTC by 2e3s

2022-07-06 20:15 UTC, justnero approved these changes

2022-07-06 20:16 UTC, justnero requested changes
Just noticed you didn't register new path in `openapi.yaml`

2022-07-06 20:27 UTC, justnero submitted a review, later dismissed

2022-07-07 05:44 UTC, justnero submitted a review, later dismissed

2022-07-07 09:41 UTC, noon-dawg commented on openapi/paths/reports@revenue-audit.yaml
> +  summary: Retrieve a revenue audit report
```suggestion
  summary: Retrieve a revenue audit report.
```

2022-07-07 09:42 UTC, noon-dawg commented on openapi/paths/reports@revenue-audit.yaml
> +      description: A revenue audit report was retrieved successfully.
nitpick: avoid past tense
```suggestion
      description: Revenue audit report successfully retrieved.
```

2022-07-07 09:54 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Customer's ID.
suggestion: It seems like we are repeating the variable name in the description

If we are describing object IDs, I think we should use this description
```suggestion
    description: Unique object identifier.
```
Or, if it's not a object:
```suggestion
    description: Unique customer identifier.
```

or

2022-07-07 09:55 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Invoice's ID.
suggestion: from earlier comment

```suggestion
    description: Unique object identifier.
```

or 

```suggestion
    description: Unique invoice identifier.
```

2022-07-07 10:16 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +      scheduled: The amount will be recognized in the end of month.
```suggestion
      scheduled: The amount will be recognized at the end of month.
```

2022-07-07 10:18 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: The amount which will be recognized unless it's changed by the recognition time.
```suggestion
    description: Estimated amount which will be recognized unless it is changed before recognition time.
```

2022-07-07 10:25 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: When the entry was recognized.
```suggestion
    description: Date and time at which the entry was recognized.
```

2022-07-07 10:33 UTC, noon-dawg commented on openapi/paths/reports@revenue-audit.yaml
> +        description: Your organization ID.
```suggestion
        description: Unique object identifier.
```

Or

```suggestion
        description: Unique organization identifier.
```

2022-07-07 10:34 UTC, noon-dawg commented on openapi/paths/reports@revenue-audit.yaml
> +    description: Live server
```suggestion
    description: Live server.
```

2022-07-11 04:10 UTC, 2e3s commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Customer's ID.
```suggestion
    description: Identifier of the customer which generated the revenue.
```

2022-07-11 04:11 UTC, 2e3s commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Invoice's ID.
```suggestion
    description: Identifier of the invoice with the item which generated the revenue.
```

2022-07-11 04:12 UTC, 2e3s commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Invoice item's ID.
```suggestion
    description: Identifier of the invoice item which generated the revenue.
```

2022-07-11 04:12 UTC, 2e3s commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Customer's ID.
It's not really unique, @noon-dawg

2022-07-11 09:01 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Identifier of the customer which generated the revenue.
Awesome! These are much more descriptive.

Now that we are describing them in detail, I think we could shorten them to use `ID` (sorry if I'm giving you mixed messages here )

```suggestion
    description: ID of the customer which generated the revenue.
```

2022-07-11 09:02 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Identifier of the invoice with the item which generated the revenue.
```suggestion
    description: ID of the invoice that contains the item which generated the revenue.
```

2022-07-11 09:02 UTC, noon-dawg commented on openapi/components/schemas/RevenueEntry.yaml
> +    description: Identifier of the invoice item which generated the revenue.
```suggestion
    description: ID of the invoice item which generated the revenue.
```

2022-07-13 08:55 UTC, noon-dawg approved these changes, later dismissed
Looks good!

2022-07-13 09:20 UTC, ashkarpetin submitted a review, later dismissed

2022-07-14 04:36 UTC, akozhevnikov-rebilly submitted a review, later dismissed

2022-07-27 03:37 UTC, adamaltman commented on openapi/components/schemas/RevenueEntry.yaml
> +      - $ref: ./ResourceId.yaml
What is the true point of the `allOf`?

2022-07-27 03:40 UTC, adamaltman requested changes, later dismissed

2022-07-27 03:40 UTC, adamaltman commented on openapi/paths/reports@revenue-audit.yaml
> +  summary: Retrieve a revenue audit report.
Summary should not have a full stop

2022-07-27 03:40 UTC, adamaltman commented on openapi/paths/reports@revenue-audit.yaml
> +  description: Retrieve a revenue audit report.
The description should have more meat (at least 30 characters). For example, I'm not clear how would the period be set?  Is there a default period?

2022-07-27 03:40 UTC, adamaltman commented on openapi/paths/reports@revenue-audit.yaml
> +  summary: Retrieve a revenue audit report
@noon-dawg operation summaries should not have a full stop.

2022-07-27 03:41 UTC, adamaltman commented on openapi/paths/reports@revenue-audit.yaml
> +    description: Live server
The server should not have a full stop.

2022-07-27 03:42 UTC, adamaltman commented on openapi/paths/reports@revenue-audit.yaml
> +    description: Live server.
```suggestion
    description: Live server
```

2022-07-27 21:00 UTC, 2e3s commented on openapi/components/schemas/RevenueEntry.yaml
> +      - $ref: ./ResourceId.yaml
That's everywhere when `$ref` is used with override. How else could it be used?

2022-07-29 20:40 UTC, 2e3s commented on openapi/paths/reports@revenue-audit.yaml
> +  description: Retrieve a revenue audit report.
I've added a few more details, period and other fields would be set like with other collections with `filter` parameter.

2022-08-03 03:05 UTC, 2e3s commented on openapi/components/schemas/RevenueEntry.yaml
> +      - $ref: ./ResourceId.yaml
https://swagger.io/docs/specification/using-ref/#sibling
> Any sibling elements of a $ref are ignored

So `allOf` is the only way we can merge without losing the fields.

2022-08-03 07:56 UTC, noon-dawg commented on openapi/paths/reports@revenue-audit.yaml
> +    It is a collection, so parameters as filter, limit and offset are available to work with it.
nitpick: I think it would be good to link to related content

I added a link which describes revenue waterfalls. We don't have one for journal reports yet (in this cycle I think)

```suggestion
  description: |
    Retrieve a revenue audit report which contains detailed journal entries. 
    A revenue audit report is a combination of a granular 
    [revenue waterfall](https://www.rebilly.com/docs/data-tables/revenue-recognition/#revenue-waterfall) 
    and a journal report, which describes revenue per account. 
    Use`Pagination-Limit` and `Pagination-Offset` parameters to filter the report.
```

2022-08-04 08:09 UTC, noon-dawg commented on openapi/paths/reports@revenue-audit.yaml
> +    Use [`filter`](https://api-reference.rebilly.com/#section/Using-filter-with-collections),
nitpick: comma is not needed
```suggestion
    Use [`filter`](https://api-reference.rebilly.com/#section/Using-filter-with-collections)
```

2022-08-05 07:12 UTC, noon-dawg approved these changes
LGTM

2022-08-05 19:47 UTC, ashkarpetin approved these changes

2022-08-05 20:52 UTC, merged