Add organizationId to Customer and Invoice resources
Rebilly/api-definitions pull request #943
Opened 2022-07-28 22:44 UTC by ninjasimon

Adds `organizationId` property to Customer and Invoice resources.

2022-07-29 01:47 UTC, XaosSintez approved these changes, later dismissed

2022-07-29 07:10 UTC, ashkarpetin approved these changes, later dismissed

2022-07-29 08:30 UTC, vykhrystiuk approved these changes, later dismissed

2022-07-29 22:42 UTC, adamaltman commented on openapi/components/schemas/Customer.yaml
> +      - $ref: ./ResourceId.yaml
I would actually prefer if we had a reusable OrganizationId.yaml.

2022-08-02 01:00 UTC, adamaltman submitted a review, later dismissed

2022-08-02 04:10 UTC, subenson approved these changes, later dismissed

2022-08-02 04:29 UTC, akozhevnikov-rebilly submitted a review, later dismissed

2022-08-02 05:10 UTC, XaosSintez approved these changes, later dismissed

2022-08-02 06:31 UTC, slavcodev commented on openapi/components/schemas/OrganizationId.yaml
> +description: The resource ID. Defaults to UUID v4.
This pretty much looks like copy-paste, might be improved, I think

2022-08-02 06:32 UTC, slavcodev commented on openapi/components/schemas/OrganizationId.yaml
> +type: string
Is this field always read-only?

2022-08-02 06:32 UTC, slavcodev commented on openapi/components/schemas/GatewayAccount.yaml
>      deprecated: true
Is this still considered deprecated?

2022-08-02 06:33 UTC, slavcodev commented on openapi/components/schemas/Websites/Website.yaml
>      deprecated: true
Is this still considered deprecated?

2022-08-02 18:35 UTC, ninjasimon commented on openapi/components/schemas/OrganizationId.yaml
> +description: The resource ID. Defaults to UUID v4.
Thanks, I forgot to update that.

2022-08-12 02:32 UTC, subenson commented on openapi/components/schemas/OrganizationId.yaml
> +type: string
Yes. It is.

2022-08-12 02:33 UTC, subenson commented on openapi/components/schemas/GatewayAccount.yaml
>      deprecated: true
Yes. No changes have been made to GatewayAccount that are related to the organizationId.

2022-08-12 02:34 UTC, subenson commented on openapi/components/schemas/Websites/Website.yaml
>      deprecated: true
Yes. No changes have been made to Website that are related to the organizationId.

2022-08-12 03:11 UTC, subenson commented
@Rebilly/php @Rebilly/js please review

2022-08-12 07:52 UTC, noon-dawg reviewed
Minor suggestion on the descriptions

Most of the suggestion are on lines that were not changed. I'm taking this opportunity to update the text while under your supervision :)

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/OrganizationId.yaml
> +description: Organization ID.
nitpick: Good to add more detail here
```suggestion
description: |-
     Your organization ID. The organization ID describes your
     organization in Rebilly. For information on how to obtain
     your organization ID, see
     [Obtain your organization ID and website ID](https://www.rebilly.com/docs/settings/organizations-and-websites/#obtain-your-organization-id-and-website-id).
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Subscription/OrderTypes/OneTimeOrder.yaml
>    # Always keep the SubscriptionMetadata the latest merged schema,
```suggestion
  # Always keep the SubscriptionMetadata from the latest merged schema,
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Subscription/OrderTypes/SubscriptionOrder.yaml
>    # Always keep the SubscriptionMetadata the latest merged schema,
```suggestion
  # Always keep the SubscriptionMetadata from the latest merged schema,
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Transactions/Transaction.yaml
>          description: The time that the transaction was settled by the banking instuition.
nitpick: suggestion to add more detail and remove to avoid starting with "the"
```suggestion
        description: Date and time at which the transaction was settled by the banking institution.
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Websites/Website.yaml
>      description: The links related to resource.
nitpick: Where possible, we should avoid starting descriptions with "the"

This can be tiresome to read

```suggestion
    description: Related resource links.
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Customer.yaml
>      description: The links related to resource.
nitpick: Where possible, we should avoid starting descriptions with "the"

This can be tiresome to read

```suggestion
    description: Related resource links.
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Invoices/Invoice.yaml
>          description: The links related to resource.
nitpick: Where possible, we should avoid starting descriptions with "the"

This can be tiresome to read

```suggestion
    description: Related resource links.
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Membership.yaml
>          description: Organization name.
nitpick: good to add more detail here
```suggestion
        description: |-
             An organization is an entity that represents you, or your
             company, as a merchant. You can have multiple organizations.
             For more information, see
             [My organizations and websites](https://www.rebilly.com/docs/settings/organizations-and-websites/).
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Membership.yaml
>          description: First and last name.
nitpick: I'm assuming this is the Rebilly user's first and last name
```suggestion
        description: Your first and last name.
```

2022-08-12 07:52 UTC, noon-dawg commented on openapi/components/schemas/Organizations/Organization.yaml
>      description: The organization name.
nitpick: good to add more detail here
```suggestion
        description: |-
             An organization is an entity that represents you, or your
             company, as a merchant. You can have multiple organizations.
             For more information, see
             [My organizations and websites](https://www.rebilly.com/docs/settings/organizations-and-websites/).
```

2022-08-14 20:48 UTC, adamaltman requested changes

2022-08-14 20:48 UTC, adamaltman commented on openapi/components/schemas/Customer.yaml
> +      - $ref: ./OrganizationId.yaml
This needs to change everywhere. `OrganizationId.yaml` is defined with`readOnly: true`.

2023-01-25 21:14 UTC, ashkarpetin commented
Absorbed by https://github.com/Rebilly/api-definitions/pull/1228

2023-01-25 21:14 UTC, closed without merging