Fix issues related sdk
Rebilly/api-definitions pull request #962
Opened 2022-08-10 12:38 UTC by jvc9109

- ensure `type: string` for `BankAccountInstrument`
- Fix the response type for `authentication-options` endpoints. (does not return an array).
- Refactor response type for `authentication-tokens` to improve sdk autogeneration.
- Refactor `PaymentInstrument` to create a discriminated model in sdk. Add `x-abastract-parent` to common schemas.

2022-08-11 09:57 UTC, justnero approved these changes

2022-08-11 09:58 UTC, justnero requested changes
Actually, the mapping is broken here
<img width="715" alt="image" src="https://user-images.githubusercontent.com/11618962/184109491-88e82624-cce5-4214-9875-ddbe4ab08b14.png">

2022-08-11 13:40 UTC, noon-dawg reviewed
Minor nitpicks

2022-08-11 13:40 UTC, noon-dawg commented on openapi/components/schemas/Common/CommonAuthenticationToken.yaml
> +    description: The token's generation mode. A SecretApiKey must be used to login in passwordless mode.
nitpick: I found 'mode' confusing here

I think 'type' is a good alternative when describing this field. In my thinking, we currently have two types of token, one which provides access with a password, and one which provides access without.

```suggestion
    description: |-
    Type of token authentication token to generate. The `password` token requires the 
    user to enter a password to log in. The `passwordless` token, requires a secret API 
    key to log in. To obtain an API key, see 
    [Manage API keys](https://www.rebilly.com/docs/dev-docs/api-keys/#manage-api-keys).
```

2022-08-11 13:40 UTC, noon-dawg commented on openapi/components/schemas/Common/CommonAuthenticationToken.yaml
> +    description: Should OTP be required to exchange this token.
nitpick: suggestion to provide more detail
```suggestion
    description: Specifies whether a One-Time Password (OTP) is required to exchange the authentication token.
```

2022-08-11 13:40 UTC, noon-dawg commented on openapi/components/schemas/Common/CommonKhelocardCard.yaml
>      description: The payment instrument ID.
nickpick: suggestion to avoid starting the description with "the"
```suggestion
    description: ID of the payment instrument.
```

2022-08-11 13:40 UTC, noon-dawg commented on openapi/components/schemas/Common/CommonBankAccount.yaml
>      description: The payment instrument ID.
nickpick: suggestion to avoid starting the description with "the"
```suggestion
    description: ID of the payment instrument.
```

2022-08-11 13:40 UTC, noon-dawg commented on openapi/components/schemas/Common/CommonAuthenticationToken.yaml
> +    description: The credential's ID.
issue: I'm not clear on what this field represents

(I took a guess here, I'm not sure if it's correct)

```suggestion
    description: ID of the user associated with the authentication token. 
```

2022-08-11 13:40 UTC, noon-dawg commented on openapi/components/schemas/Common/CommonAlternativeInstrument.yaml
>      description: The billing address.
nitpick: suggestion to reduce ambiguity
```suggestion
    description: Billing address of the user that is associated with the payment instrument.
```

2022-08-11 14:36 UTC, jvc9109 commented on openapi/components/schemas/CustomerAuthentication/AuthenticationTokenResponse.yaml
> +        description: The token's username.
My guess is that a credential (or token) has a username and a password. A customer can have multiple credentials (hence multiple usernames) https://api-reference.rebilly.com/tag/Customer-Authentication/operation/PostCredential

2022-08-11 14:44 UTC, noon-dawg commented on openapi/components/schemas/CustomerAuthentication/AuthenticationTokenResponse.yaml
> +        description: The token's username.
I think I understand now, I've updated my suggestion

2022-08-11 15:31 UTC, justnero commented on openapi/components/schemas/Common/CommonAuthenticationToken.yaml
> +    description: The token's generation mode. A SecretApiKey must be used to login in passwordless mode.
When we say `type` we generally mean the entity becomes or is of this type. In this case `mode` describes only the method of verifying authenticity and has nothing to do with the resulting entity. If `mode: passwordless` is passed for this operation, the authentication method must be a secret key for this exact request. With `mode: password` – the actual password must be supplied in the same request. The token you get from this operation will be the same independently of the `mode`.

2022-08-11 15:31 UTC, justnero commented on openapi/components/schemas/CustomerAuthentication/AuthenticationToken.yaml
> +x-abstract-parent: CommonAuthenticationToken
Trailing new line

2022-08-11 16:42 UTC, noon-dawg commented on openapi/components/schemas/Common/CommonAuthenticationToken.yaml
> +    description: The token's generation mode. A SecretApiKey must be used to login in passwordless mode.
Excellent input! Thank you 🙏

I've updated based on your comment

2022-08-11 18:42 UTC, jvc9109 commented on openapi/components/schemas/CustomerAuthentication/AuthenticationToken.yaml
> +    description: |-
@noon-dawg your description suggestion it is located in this file now. Thanks for your input!

2022-08-12 07:16 UTC, noon-dawg commented on openapi/components/schemas/CustomerAuthentication/AuthenticationToken.yaml
> +    description: |-
Happy to help! 🙏

2022-08-12 07:16 UTC, noon-dawg commented
LGTM!

2022-08-12 09:48 UTC, justnero submitted a review, later dismissed

2022-08-12 17:38 UTC, jvc9109 commented
@Rebilly/php  @Rebilly/js  please review.

2022-08-12 17:39 UTC, ashkarpetin approved these changes

2022-08-12 17:40 UTC, justnero approved these changes

2022-08-12 17:52 UTC, merged

2022-08-14 20:38 UTC, adamaltman commented on openapi/components/schemas/CustomerAuthentication/AuthenticationToken.yaml
> +    - $ref: ./TokenModes/passwordless.yaml
I think this is a bad idea. Can we discuss this further @jvc9109 ? 

I understand there is a preprocessor that builds the `mapping`. In this case, the `x-enum-mapping` doesn't save any time and it makes the definition more obscure and not in compliance with OpenAPI.

2022-08-14 20:39 UTC, adamaltman commented on openapi/components/schemas/Plans/FlexiblePlan.yaml
> +    readOnly: false
This doesn't make sense.

2022-08-14 20:45 UTC, adamaltman commented on openapi/paths/files@{id}@download.yaml
> +            format: binary
The content type seems wrong. It seems like this is for many types include `image/png` as the example shows. In this case, content should be a comma separate list of the possible types and could use *, such as application/json, image/*, text/csv.

2022-08-15 10:58 UTC, jvc9109 commented on openapi/components/schemas/CustomerAuthentication/AuthenticationToken.yaml
> +    - $ref: ./TokenModes/passwordless.yaml
I agree @adamaltman , this mapping can be simplified and use the regular discrimination mapping. I will prepare a PR

2022-08-15 11:08 UTC, ashkarpetin commented on openapi/components/schemas/CustomerAuthentication/AuthenticationToken.yaml
> +    - $ref: ./TokenModes/passwordless.yaml
`x-enum-mapping` is used in 5 places, @justnero @justnero should we remove it completely?

2022-08-15 11:16 UTC, jvc9109 commented on openapi/components/schemas/CustomerAuthentication/AuthenticationToken.yaml
> +    - $ref: ./TokenModes/passwordless.yaml
There are cases where it is necessary for correct sdk generation. For instance in `PaymentInstrument` since the `AlternativePaymentInstrument` enum has N different selectors. This custom mapping solution allow us to generate correctly the different options