Add usage records API
Rebilly/api-definitions pull request #992
Opened 2022-08-26 10:57 UTC by VladimirBerdnik

2022-08-29 07:34 UTC, 2e3s commented on openapi/openapi.yaml
> +  '/usages/{id}':
It seems confusing, `/order-item-usage` could be easier to understand. What about `/subscriptions/{id}/usage`? It seems like a part of orders.

2022-08-29 07:42 UTC, 2e3s commented on openapi/components/schemas/Usage.yaml
> +  planId:
A subscription can have a few items with the same plan, can't it?

2022-08-30 07:11 UTC, VladimirBerdnik commented on openapi/components/schemas/Usage.yaml
> +  planId:
No, it (currently) cannot

2022-08-30 12:28 UTC, adamaltman commented on plugins/products-bundler/mapping/Combined.yaml
> +      - Usage record
I don't think the tag should be `Usage record`, but instead `Usage`, just as we call them `Customers` and not `Customer record`.

2022-09-27 10:11 UTC, adamaltman commented on openapi/components/schemas/Plans/PlanTypes/SubscriptionOrderPlan.yaml
> +      Metered billing plan must be postpaid.
```suggestion
      Metered billing plans must be postpaid.
```

2022-09-27 10:12 UTC, adamaltman commented on openapi/components/schemas/Plans/PlanTypes/SubscriptionOrderPlan.yaml
> +          last: Last reported usage used to form an invoice item quantity
```suggestion
          sum: Sum of reported usage used as the invoice item quantity
          last: Last reported usage used as the invoice item quantity
```

2022-09-27 10:14 UTC, adamaltman commented on openapi/components/schemas/Usage.yaml
> +    description: Date and time to which a usage belongs. When not provided or empty, date and time of request is used.
```suggestion
    description: ISO 8601 date time formatted timestamp to which a usage belongs. When not provided or empty, date and time of the request is used as the default value.
```

2022-09-27 10:14 UTC, adamaltman commented on openapi/components/schemas/Usage.yaml
> +      - $ref: ./ServerTimestamp.yaml
```suggestion
    $ref: ./UpdatedTime.yaml
```

2022-09-27 10:18 UTC, adamaltman commented on openapi/openapi.yaml
> +      # TODO: update description and provide a link to documentation when added.
```suggestion
      Reports the product usage of a subscription item for metered billing purposes.
<!--      TODO: update description and provide a link to documentation when added. -->
```

2022-09-27 10:18 UTC, adamaltman commented on openapi/paths/usages.yaml
> +  summary: Retrieve a list of usage records
```suggestion
  summary: Retrieve usage records
```

2022-10-08 12:42 UTC, noon-dawg commented on openapi/paths/usages@{id}.yaml
> +      description: Usage record retrieved successfully.
nitpick: 'successfully' does not add to the sentence 
```suggestion
      description: Usage record retrieved.
```

2022-10-08 14:02 UTC, noon-dawg reviewed
Minor suggestions

2022-10-08 14:02 UTC, noon-dawg commented on openapi/paths/usages.yaml
> +      description: List of usage records retrieved succesfully.
nitpick: 'successfully' does not add to the sentence
```suggestion
      description: List of usage records retrieved.
```

2022-10-08 16:44 UTC, VladimirBerdnik commented on openapi/components/schemas/Plans/PlanTypes/SubscriptionOrderPlan.yaml
> +          sum: Sum of reported usage used as the invoice item quantity
@noon-dawg , thank you for notes!
As for me, the new version sounds a bit incorrect. It's not a usage of invoice item, it's usage of a product that will be set as invoice item quantity. Same for the `last` strategy

2022-10-10 10:31 UTC, VladimirBerdnik commented
devs please review

2022-10-10 12:15 UTC, noon-dawg commented
LGTM!

2022-10-12 11:47 UTC, adamaltman commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice for which usage is considered. This value is added when the invoice with usage is issued.
I feel this description should be more prescriptive. Maybe:
```suggestion
    description: ID of the invoice to apply usage. Use this field to add usage to an issued invoice.
```

2022-10-12 11:47 UTC, adamaltman commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice item for which usage is considered. This value is added when the invoice with usage is issued.
```suggestion
    description: ID of the invoice item to apply usage. Use this field to add usage to an issued invoice.
```

2022-10-12 11:51 UTC, adamaltman requested changes

2022-10-12 11:51 UTC, adamaltman commented on openapi/paths/usages.yaml
> +  operationId: GetUsagesCollection
```suggestion
  operationId: GetUsageCollection
```

We name it like `GetCustomerCollection` (not `GetCustomersCollection`).

2022-10-12 17:42 UTC, adamaltman commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice for which usage is considered. This value is added when the invoice with usage is issued.
I seemed to miss the read only nature of this and the next property. I adjusted my suggestion.

2022-10-12 17:55 UTC, noon-dawg commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice for which usage is considered. This value is added when the invoice with usage is issued.
Suggestion to avoid ending the first sentence with preposition 
```suggestion
    description: ID of the invoice to which usage is applied. This value is populated when the invoice is issued.
```

2022-10-12 17:57 UTC, noon-dawg commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice item for which usage is considered. This value is added when the invoice with usage is issued.
Suggestion to avoid ending the first sentence with preposition
(incorporates Adam's comment )
```suggestion
    description: ID of the invoice to which usage is applied. This value is populated when the invoice is issued.
```

2022-10-12 18:00 UTC, noon-dawg commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice for which usage is considered. This value is added when the invoice with usage is issued.
Suggestion to avoid ending the first sentence with preposition 
(incorporates Adam's comment )
```suggestion
    description: ID of the invoice to which usage is applied. This value is populated when the invoice is issued.
```

2022-10-12 18:01 UTC, noon-dawg commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice item for which usage is considered. This value is added when the invoice with usage is issued.
Suggestion to avoid ending the first sentence with a preposition
(incorporates Adam's comment )
```suggestion
    description: ID of the invoice to which usage is applied. This value is populated when the invoice is issued.
```

2022-10-13 13:36 UTC, noon-dawg commented on openapi/components/schemas/Usage.yaml
> +    description: ID of the invoice to which usage is applied. This value is populated when the invoice is issued.
typo: I missed this in my suggestion

Sorry about that

```suggestion
    description: ID of the invoice item to which usage is applied. This value is populated when the invoice is issued.
```

2022-10-13 14:58 UTC, adamaltman approved these changes

2022-10-13 15:08 UTC, noon-dawg commented
LGTM!

2022-10-13 15:09 UTC, ashkarpetin approved these changes

2022-10-13 16:28 UTC, merged